### ISSUE TITLE
Adicionar 19 novas cidades de sistemas replicáveis

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#1001]
Exemplo de raspador instar funcional: [sp_barao_de_antonina.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/sp/sp_barao_de_antonina.py)

## Descrição
As cidades abaixo utilizam o sistema replicável conhecido e já implementado Instar. A tarefa aqui é enviar PRs com todos os raspadores das cidades abaixo usando de referência o exemplo acima, que usa o mesmo sistema

Como estas cidades serão adicionadas ao projeto, cada PR precisa incluir, também, a modificação da [lista de spiders em funcionamento](https://github.com/okfn-brasil/querido-diario/blob/main/scripts/enabled_spiders.py)

### Task 1
Poloni	SP https://www.poloni.sp.gov.br/portal/diario-oficial
Santa Maria da Serra	SP https://www.santamariadaserra.sp.gov.br/portal/diario-oficial
Lagoinha	SP https://www.lagoinha.sp.gov.br/portal/diario-oficial
Luiziânia	SP https://www.luiziania.sp.gov.br/portal/diario-oficial

### Task 2
Planalto	SP https://www.planalto.sp.gov.br/portal/diario-oficial
João Ramalho	SP https://www.joaoramalho.sp.gov.br/portal/diario-oficial
Sebastianópolis do Sul	SP https://www.sebastianopolisdosul.sp.gov.br/portal/diario-oficial
Mira Estrela	SP https://www.miraestrela.sp.gov.br/portal/diario-oficial
Nova Luzitânia	SP https://www.novaluzitania.sp.gov.br/portal/diario-oficial

### Task 3
Águas de São Pedro	SP https://www.aguasdesaopedro.sp.gov.br/portal/diario-oficial
Floreal	SP	https://www.floreal.sp.gov.br/portal/diario-oficial
Taquaral	SP https://www.taquaral.sp.gov.br/portal/diario-oficial
Brejo Alegre	SP https://www.brejoalegre.sp.gov.br/portal/diario-oficial
Pontes Gestal	SP https://www.pontesgestal.sp.gov.br/portal/diario-oficial

### Task 4
Arapeí	SP https://www.arapei.sp.gov.br/portal/diario-oficial
Turiúba	SP https://www.turiuba.sp.gov.br/portal/diario-oficial
Dirce Reis	SP https://www.dircereis.sp.gov.br/portal/diario-oficial
União Paulista	SP https://uniaopaulista.sp.gov.br/portal/diario-oficial
Nova Castilho	SP	https://www.novacastilho.sp.gov.br/portal/diario-oficial

**Comment by tatilattanzi** [comment]
oi! estou resolvendo essa issue

**Comment by tatilattanzi** [comment]
done ✅

**Comment by trevineju** [comment]
uhu! brilhou demais! Já deixei eles aceitos. 
Passo a revisar em breve ❤️
