### ISSUE TITLE
[Manutenção] São José dos Basílios-MA

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#1008]
O [raspador para São José dos Basílios](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/ma/ma_sao_jose_dos_basilios.py) não está mais funcionando. 

O novo site publicador é https://diariooficial.saojosedosbasilios.ma.gov.br/diariooficial

A tarefa aqui é desenvolver o raspador para esse novo site. 

O arquivo do raspador descontinuado deve ser mantido e renomeado para `ma_sao_jose_dos_basilios_2015.py` e o novo raspador se chamar `ma_sao_jose_dos_basilios_2023.py`

**Comment by JohnatanLicar** [comment]
vou pegar essa issue

**Comment by IgorJanuario** [comment]
@trevineju Terminei hoje essa task.
https://github.com/okfn-brasil/querido-diario/pull/1030

Se quiser validar e caso esteja correto encerrar a task. Avisa por favor.

Esse site novo do São José dos Basílios-MA fez se necessário criar um novo spider.
