### ISSUE TITLE
[Novo spider base]: Barco Digital

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#1016]
### URL

https://barcodigital.com.br/#projetos

### Municípios replicados

```bash
1. https://diariooficial.araguaina.to.gov.br/diario-oficial
2. https://diariooficial.pontealtadotocantins.to.gov.br/diario-oficial 
3. https://www.tocantinopolis.to.gov.br/diario-oficial
4. https://www.sitionovodotocantins.to.gov.br/diario-oficial
```

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Detalhes do site de publicação

Possui paginação, Possui filtro por data

### Observações

As edições extras e suplementos parecem bem demarcados

### Não existe uma issue aberta sobre isso

- [X] Eu verifiquei e não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo sistema.

**Comment by trevineju** [comment]
Esta issue endereça também um problema de manutenção para o município de Araguaína-TO

**Comment by ddevdan** [comment]
Boa noite, to trabalhando nessa issue. @trevineju
