### ISSUE TITLE
[Novo spider]: Sampaio-TO

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#1022]
### URL da forma de consulta

https://diariooficial.sampaio.to.gov.br/pesquisar

### Período de publicação

04/05/2020 ate hje

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui paginação, Possui filtro por data

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by vbmendes** [comment]
Vou trabalhar nessa issue.
