### ISSUE TITLE
Aracaju/SE Spider

### ISSUE THREAD

**Issue by silasalvares** [okfn-brasil/querido-diario#105]
Hi everybody, I'm stuck trying to build the Aracaju City spider. This is the main site for the gazettes: http://sga.aracaju.se.gov.br:5011/legislacao/faces/diario_form_pesq.jsp. It's a JSP page and the requests must contain some session data. I could retrieve the gazettes through a direct link by the gazette official number (http://sga.aracaju.se.gov.br:5011/diarios/3970.pdf), in this case I don't have extra information, like publishing date for example. Is there a best approach to deal with this?

**Comment by danilolutz** [comment]
Hi @silasalvares.

You have tried this way: https://stackoverflow.com/a/48588048/1063970 or https://stackoverflow.com/a/25516223/1063970 ?

Since you know the start date you can set the form, send it, scrape the page and go to ahead page.

I hope this help. See you...

**Comment by cuducos** [comment]
Hi @silasalvares,

I do think going straight forward to the PDF links would be a difficult path: you'd have to extract all other info parsing the PDF.

There are techniques to deal with session data (as @danilolutz suggested – BTW thanks, mate!) and I strongly recommend this way. In addition do the `FormRequest` think the `Request` and `Response`  can exchange info using the [`meta` attribute](https://doc.scrapy.org/en/latest/topics/request-response.html?highlight=meta#request-objects) – and that pretty much can address the _requests must contain some session data_ issue.

Does that make sense?

**Comment by silasalvares** [comment]
Thanks guys! I'm trying to build the spider following the instructions. I'll post the results here as soon as I make progress.

**Comment by rennerocha** [comment]
Closing stale issue.
