### ISSUE TITLE
[Manutenção] Belo Horizonte - MG

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#1054]
O [raspador para Belo Horizonte-MG](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/mg/mg_belo_horizonte.py) não está mais coletando diários desde [11/10/23](https://queridodiario.ok.org.br/pesquisa?city=3106200&sort_by=descending_date)

## log
Na Zyte, o mais recente (7/12/23) job de raspagem dessa cidade tem as seguintes informações: 

Arguments	start_date=2023-12-06
Start time	2023-12-07 22:41:55 UTC
Finish time	2023-12-07 22:42:33 UTC
Runtime	        half a minute
Errors	        2 errors
Items	        0
Log	                [log_mg_belo_horizonte_660.txt](https://github.com/okfn-brasil/querido-diario/files/13620509/log_mg_belo_horizonte_660.txt)
Requests	[requests_mg_belo_horizonte_660.json](https://github.com/okfn-brasil/querido-diario/files/13620512/requests_mg_belo_horizonte_660.json)

## tarefa
É necessário fazer adaptações necessárias para que o código do raspador volte a funcionar.

Uma vez que a requisição no formato feito pelo raspador nas linhas 25 a 28 segue funcionando: 
~~~python
yield scrapy.Request(
                f"{base_url}?{urlencode(url_params)}",
                cb_kwargs={"gazette_date": date.date()},
            )
~~~
E prova disso são as requests válidas registradas no arquivo JSON anexado acima. O problema parece ser entre as linhas 37 e 40: 
~~~python
            gazette_hash = gazette["documento_jornal"]["nome_minio"]
            gazette_url = (
                f"https://api-dom.pbh.gov.br/api/v1/documentos/{gazette_hash}/download"
            )
~~~
para a obtenção do arquivo do diário.

**Comment by SchiavonJP** [comment]
Olá, 
Estou dando uma olhada e me parece que adicionaram um parametro na chamada 'prefix', que recebe uma string com a data do dia anterior ao do diário.

![image](https://github.com/okfn-brasil/querido-diario/assets/13931635/521aeef1-66cf-4ef8-b078-93bfdff70fc4)


Vou fazer o ajuste aqui.

**Comment by rennerocha** [comment]
@SchiavonJP 
O `prefix` na maioria das vezes é a data anterior no formato YYYYMMDD, mas em algumas não.
Porém, a API já retorna o valor de `prefix` a ser utilizado (ou ` None` se não for necessário).
Fiz essa modificação e agora o spider está funcionando 100%. 
Já iniciei um job a partir de setembro, só para garantir que vamos obter tudo que está faltando.

**Comment by SchiavonJP** [comment]
@rennerocha 
Aaaah, show de bola, não vi que o prefix estava no retorno. Valeu pela review!
