### ISSUE TITLE
[Novo spider]: Guaxupé-MG

### ISSUE THREAD

**Issue by patricia-salles** [okfn-brasil/querido-diario#1081]
### URL da forma de consulta

https://www.guaxupe.mg.gov.br/atos-oficiais

### Período de publicação

03/2020 até atualmente

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui paginação

### Observações

Possui paginação para uma segunda página, mas o acesso à essa página retorna "Ops"

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by patricia-salles** [comment]
Vou contribuir nessa issue.

**Comment by rochamatcomp** [comment]
@patricia-salles verifiquei o endereço do link da página 2 e está enviando para formulário, ao colocar o endereço atual funciona! Inclusive para a página 1.

https://www.guaxupe.mg.gov.br/atos-oficiais?pagina=1
https://www.guaxupe.mg.gov.br/atos-oficiais?pagina=2
