### ISSUE TITLE
[Mapeamento] Lista de municípios que usam DOEM

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#1089]
# Sobre essa tarefa
1. Apesar de aqui listadas, as URLs descontinuadas não serão integradas por enquanto, apenas as vigentes. 
2. Todos os sites a seguir devem parecer visualmente similares, porém é comum que municípios migrem a qualquer momento. Comente na issue se você se deparar com casos cujo layout do site tenha mudado.
3. Dica: Como todos estes municípios seguem o mesmo padrão, o código de seus raspadores também seguirão, tendo apenas algumas diferenças como nome, data, URL. Um *script* que cria arquivos de código a partir da lista abaixo, mudando apenas alguns campos, pode ajudar. 
4. Não é exigido contribuir com todas estas cidades de uma vez, ela pode ser concluída por partes.
5. Para mais informações, consulte a documentação sobre [sistemas replicáveis](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#as-classes-sistemagazettespider).

Mapeado em **fevereiro de 2024**

# URL vigente 

Tem diários atuais

| Código integrado ao repositório    | Município-UF | URL |
| -------- | ------- | ------- |
|        <li>- [x] </li>        |	Acajutiba	-	BA	|	https://doem.org.br/ba/acajutiba	|
|        <li>- [x] </li>        |	Alagoinhas	-	BA	|	https://doem.org.br/ba/alagoinhas	|
|        <li>- [x] </li>        |	Alcobaça	-	BA	|	https://doem.org.br/ba/alcobaca	|
|        <li>- [x] </li>        |	Angical	-	BA	|	https://doem.org.br/ba/angical	|
|        <li>- [x] </li>        |	Banzaê	-	BA	|	https://doem.org.br/ba/banzae	|
|        <li>- [x] </li>        |	Brotas de Macaúbas	-	BA	|	https://doem.org.br/ba/brotasdemacaubas	|
|        <li>- [x] </li>        |	Caetité	-	BA	|	https://doem.org.br/ba/caetite	|
|        <li>- [x] </li>        |	Campo Alegre de Lourdes	-	BA	|	https://doem.org.br/ba/campoalegredelourdes	|
|        <li>- [x] </li>        |	Campo Formoso	-	BA	|	https://doem.org.br/ba/campoformoso	|
|        <li>- [x] </li>        |	Canudos	-	BA	|	https://doem.org.br/ba/canudos	|
|        <li>- [x] </li>        |	Cícero Dantas	-	BA	|	https://doem.org.br/ba/cicerodantas	|
|        <li>- [x] </li>        |	Cipó	-	BA	|	https://doem.org.br/ba/cipo	|
|        <li>- [x] </li>        |	Cotegipe	-	BA	|	https://doem.org.br/ba/cotegipe	|
|        <li>- [x] </li>        |	Cristópolis	-	BA	|	https://doem.org.br/ba/cristopolis	|
|        <li>- [x] </li>        |	Cruz das Almas	-	BA	|	https://doem.org.br/ba/cruzdasalmas	|
|        <li>- [x] </li>        |	Esplanada	-	BA	|	https://doem.org.br/ba/esplanada	|
|        <li>- [x] </li>        |	Formosa do Rio Preto	-	BA	|	https://doem.org.br/ba/formosadoriopreto	|
|        <li>- [x] </li>        |	Inhambupe	-	BA	|	https://doem.org.br/ba/inhambupe	|
|        <li>- [x] </li>        |	Ipiaú	-	BA	|	https://doem.org.br/ba/ipiau	|
|        <li>- [x] </li>        |	Ipiranga	-	PR	|	https://doem.org.br/pr/ipiranga	|
|        <li>- [x] </li>        |	Irará	-	BA	|	https://doem.org.br/ba/irara	|
|        <li>- [x] </li>        |	Itaberaba	-	BA	|	https://doem.org.br/ba/itaberaba	|
|        <li>- [x] </li>        |	Itamaraju	-	BA	|	https://doem.org.br/ba/itamaraju	|
|        <li>- [x] </li>        |	Itapetinga	-	BA	|	https://doem.org.br/ba/itapetinga	|
|        <li>- [x] </li>        |	Itapicuru	-	BA	|	https://doem.org.br/ba/itapicuru	|
|        <li>- [x] </li>        |	Ituaçu	-	BA	|	https://doem.org.br/ba/ituacu	|
|        <li>- [x] </li>        |	Jaguaquara	-	BA	|	https://doem.org.br/ba/jaguaquara	|
|        <li>- [x] </li>        |	Juazeiro	-	BA	|	https://doem.org.br/ba/juazeiro	|
|        <li>- [x] </li>        |	Laje	-	BA	|	https://doem.org.br/ba/laje	|
|        <li>- [x] </li>        |	Lajedão	-	BA	|	https://doem.org.br/ba/lajedao	|
|        <li>- [x] </li>        |	Macajuba	-	BA	|	https://doem.org.br/ba/macajuba	|
|        <li>- [x] </li>        |	Mascote	-	BA	|	https://doem.org.br/ba/mascote	|
|        <li>- [x] </li>        |	Monte Santo	-	BA	|	https://doem.org.br/ba/montesanto	|
|        <li>- [x] </li>        |	Morro do Chapéu	-	BA	|	https://doem.org.br/ba/morrodochapeu	|
|        <li>- [x] </li>        |	Mucuri	-	BA	|	https://doem.org.br/ba/mucuri	|
|        <li>- [x] </li>        |	Nossa Senhora do Socorro	-	SE	|	https://doem.org.br/se/nossasenhoradosocorro	|
|        <li>- [x] </li>        |	Petrolina	-	PE	|	https://doem.org.br/pe/petrolina	|
|        <li>- [x] </li>        |	Prado	-	BA	|	https://doem.org.br/ba/prado	|
|        <li>- [x] </li>        |	Santa Cruz Cabrália	-	BA	|	https://doem.org.br/ba/santacruzcabralia	|
|        <li>- [x] </li>        |	Santa Luzia	-	BA	|	https://doem.org.br/ba/santaluzia	|
|        <li>- [x] </li>        |	Santa Rita de Cássia	-	BA	|	https://doem.org.br/ba/santaritadecassia	|
|        <li>- [x] </li>        |	Santo Estêvão	-	BA	|	https://doem.org.br/ba/santoestevao	|
|        <li>- [x] </li>        |	Sátiro Dias	-	BA	|	https://doem.org.br/ba/satirodias	|
|        <li>- [x] </li>        |	Senhor do Bonfim	-	BA	|	https://doem.org.br/ba/senhordobonfim	|
|        <li>- [x] </li>        |	Sento Sé	-	BA	|	https://doem.org.br/ba/sentose	|
|        <li>- [x] </li>        |	Tamboara	-	PR	|	https://doem.org.br/pr/tamboara	|
|        <li>- [x] </li>        |	Tapiramutá	-	BA	|	https://doem.org.br/ba/tapiramuta	|
|        <li>- [x] </li>        |	Teolândia	-	BA	|	https://doem.org.br/ba/teolandia	|
|        <li>- [x] </li>        |	Tucano	-	BA	|	https://doem.org.br/ba/tucano	|

**Comment by ddevdan** [comment]
Vou trabalhar no raspador da cidade Campo Alegre de Lourdes - BA	
cc @trevineju

**Comment by ddevdan** [comment]
Vou trabalhar no raspador da cidade Ipiranga - PR

**Comment by trevineju** [comment]
Todos os municípios da lista estão integrados 🎉
