### ISSUE TITLE
[Mapeamento] Lista de municípios que usam DOBR

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#1090]
# Sobre essa tarefa
1. Ela só pode ser trabalhada após o raspador base para o padrão estar integrado ao projeto. Ou seja, a issue #1017 estar completa. 
2. Apesar de aqui listadas, as URLs descontinuadas não serão integradas por enquanto, apenas as vigentes. 
3. Todos os sites a seguir devem parecer visualmente similares, porém é comum que municípios migrem a qualquer momento. Comente na issue se você se deparar com casos cujo layout do site tenha mudado.
4. Dica: Como todos estes municípios seguem o mesmo padrão, o código de seus raspadores também seguirão, tendo apenas algumas diferenças como nome, data, URL. Um *script* que cria arquivos de código a partir da lista abaixo, mudando apenas alguns campos, pode ajudar. 
5. Não é exigido contribuir com todas estas cidades de uma vez, ela pode ser concluída por partes.
6. Para mais informações, consulte a documentação sobre [sistemas replicáveis](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#as-classes-sistemagazettespider).

Mapeado em **fevereiro de 2024**

# URL vigente 

Tem diários atuais

| Código integrado ao repositório    | Município-UF | URL |
| -------- | ------- | ------- |
|        <li>- [x] </li>        |	Aguiarnópolis	-	TO	|	https://diariooficial.aguiarnopolis.to.gov.br/	|
|        <li>- [x] </li>        |	Campos Lindos	-	TO	|	https://camposlindos.diariooficialbr.com.br/	|
|        <li>- [ ] </li>        |	Caseara	-	TO	|	https://caseara.diariooficialbr.com.br/	|
|        <li>- [x] </li>        |	Goiatins	-	TO	|	https://goiatins.diariooficialbr.com.br/	|
|        <li>- [ ] </li>        |	Itapiratins	-	TO	|	https://itapiratins.diariooficialbr.com.br/	|
|        <li>- [ ] </li>        |	Miracema	-	TO	|	https://miracema.diariooficialbr.com.br/	|
|        <li>- [ ] </li>        |	Muricilândia	-	TO	|	https://muricilandia.diariooficialbr.com.br/	|
|        <li>- [x] </li>        |	Peixe	-	TO	|	https://peixe.diariooficialbr.com.br/	|
|        <li>- [ ] </li>        |	Santa Fé do Araguaia	-	TO	|	https://santafedoaraguaia.diariooficialbr.com.br/	|
|        <li>- [ ] </li>        |	Talismã	-	TO	|	https://talisma.diariooficialbr.com.br/	|
|        <li>- [x] </li>        |	Tocantínia	-	TO	|	https://tocantinia.diariooficialbr.com.br/	|
|        <li>- [x] </li>        |	Tupiratins	-	TO	|	https://tupiratins.diariooficialbr.com.br/	|

**Comment by jreagle** [comment]
# Update - Already integrated into the [Spiders Collection](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/to)

| Code | City  | Spyder |
| ------------- | ------------- | ------------- |
| | Aguiarnópolis	-	TO | [to_aguiarnopolis.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/to/to_aguiarnopolis.py)
| | Campos Lindos	-	TO | [to_campos_lindos.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/to/to_campos_lindos.py)
| | Goiatins	-	TO | [to_goiatins.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/to/to_goiatins.py)
| | Peixe	-	TO | [to_peixe.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/to/to_peixe.py)
| | Tocantínia	-	TO | [to_tocantinia.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/to/to_tocantinia.py)
| | Tupiratins	-	TO | [to_aguiarnopolis.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/to/to_aguiarnopolis.py)

# Update - Accepting assignment (@jreagle)

| Code | City  | Spyder |
| ------------- | ------------- | ------------- |
|1703909| Caseara	-	TO | Coming soon
|1710904| Itapiratins	-	TO | Coming soon
|1713205| Miracema	-	TO | Coming soon
|1713957| Muricilândia	-	TO | Coming soon
|1718865| Santa Fé do Araguaia	-	TO | Coming soon
|1720978| Talismã	-	TO | Coming soon

@trevineju Can I start contributing to the QD project here?

**Comment by trevineju** [comment]
> @trevineju Can I start contributing to the QD project here?

Pode sim! Te designei na tarefa!

**Comment by jreagle** [comment]
> Pode sim! Te designei na tarefa!

@trevineju confere lá a PR: https://github.com/okfn-brasil/querido-diario/pull/1288

Code | City | Spider
-- | -- | --
1703909 | Caseara	-	TO | https://github.com/okfn-brasil/querido-diario/pull/1288/commits/7869ee5be6119a1b58a7f4461cb6963840156392
1710904 | Itapiratins	-	TO | https://github.com/okfn-brasil/querido-diario/pull/1288/commits/2600325f93823b4bb82a4b15841dcc58010b6f81
1713205 | Miracema	-	TO | https://github.com/okfn-brasil/querido-diario/pull/1288/commits/08aa9ca5f4a2e3c3005e199f3ea6d2d180538814
1713957 | Muricilândia	-	TO | https://github.com/okfn-brasil/querido-diario/pull/1288/commits/8fa2556d75dd5b782213f211794f4cac4d9da61d
1718865 | Santa Fé do Araguaia	-	TO | https://github.com/okfn-brasil/querido-diario/pull/1288/commits/207825ba5c5fe3e8a7b921808eb51ed6a8513966
1720978 | Talismã	-	TO | https://github.com/okfn-brasil/querido-diario/pull/1288/commits/df030cab2edaf95b6b36c9eb50d84c5ae88c093b
