### ISSUE TITLE
[Revisão retroativa]: São José dos Campos/SP

### ISSUE THREAD

**Issue by almeidadm** [okfn-brasil/querido-diario#1123]
### Objetivo da Issue

A spider atual está defasada, pois consulta o domínio https://servicos2.sjc.sp.gov.br/, sendo que atualmente os boletins são disponibilizados através do site https://diariodomunicipio.sjc.sp.gov.br/

### URL

https://diariodomunicipio.sjc.sp.gov.br/

### É um município replicado?

Não, o código utiliza BaseGazetteSpider.

### Período de publicação

08/2015 até atualmente

**Comment by trevineju** [comment]
@almeidadm, nós adicionamos o raspador para São José dos Campos, com este mesmo link, há alguns dias (d49e98b04a98c752a63b9da4a8261eb1fccbf14f)
