### ISSUE TITLE
[Consulta retornando DO de cidade errada - produção]: Poá-SP

### ISSUE THREAD

**Issue by msc2020** [okfn-brasil/querido-diario#1136]
### URL da forma de consulta

https://queridodiario.ok.org.br/pesquisa?city=3539806

### Período de publicação

2024

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui paginação

### Observações

Quando pesquisamos por Poá-SP no site do site do Querido Diário (https://queridodiario.ok.org.br/pesquisa?city=3539806) aparece o link para acessar o Diário Oficial de outra cidade (Suzano-SP). O link atual está para: 
https://www.diariodesuzano.com.br/noticias/atos-oficiais/.

O correto seria o link para prefeitura de Poá-SP e não **Suzano**. Esse é o link do DO de Poá-SP atual (acessado hoje, 25-04-2024): https://poa.sp.gov.br/diario-oficial/

O link para o DO de Poá-SP poderia ser incluído.

Segue um print da tela:
![pesquisa_qd_poa-sp](https://github.com/okfn-brasil/querido-diario/assets/62213870/500cd7c3-23f1-4af9-b88d-51cc2d43d920)

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by trevineju** [comment]
@msc2020, foi corrigido. Obrigada

**Comment by msc2020** [comment]
@trevineju, obrigado.
