### ISSUE TITLE
[Mapeamento]: NucleoGov - Diario Fragmentado

### ISSUE THREAD

**Issue by xxggabriel** [okfn-brasil/querido-diario#1148]
### URL

https://acessoainformacao.pilar.go.gov.br/

### Municípios replicados

```bash
1. https://acessoainformacao.pilar.go.gov.br/cidadao/legislacao/decretos
2. https://acessoainformacao.senadorcanedo.go.gov.br/cidadao/legislacao/decretos
3. https://acessoainformacao.formosa.go.gov.br/cidadao/legislacao/decreto
```

### Formato da publicação

Os diários oficiais são publicados em PDF (texto), Os diários oficiais são publicados em PDF (imagem scanneada)

### Detalhes do site de publicação

Possui paginação, Possui filtro por data

### Observações

Estou abrindo esta issue para mapear ocorrências de padrões e documentar os casos em que a NucleoGov utiliza métodos diferentes para publicação de atos individuais (diário fragmentado).

Fiz o PR para o spider base da NucleoGov (PR #1147), e notei que eles têm outro sistema de publicações de atos individuais, como:

- decretos
- leis
- portarias

Qualquer informação adicional que puderem fornecer ou discutir sobre como lidar com esses diários fragmentados será muito útil.

### Não existe uma issue aberta sobre isso

- [X] Eu verifiquei e não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo sistema.

**Comment by trevineju** [comment]
Obrigada!
