### ISSUE TITLE
PB Campina Grande Executive Spider

### ISSUE THREAD

**Issue by thiagonobrega** [okfn-brasil/querido-diario#115]
I have started a spider to executive gazettes of campina grande/PB...

Soon I will send a pull request...

**Comment by giovanisleite** [comment]
Eu não encontrei um diário oficial, mas existe um semanário (https://campinagrande.pb.gov.br/semanario-oficial/) - Estava com receio do semanário ser um apanhado ou destaque de alguns atos.

------------------

I didn't find a daily document, but there is a weekly one (https://campinagrande.pb.gov.br/semanario-oficial/) - I wasn't sure that this was the official document of all the information or just highlights, but it looks like it is.
