### ISSUE TITLE
[Manutenção] Classe base AdminLTE quebrando a paginação

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#1171]
O raspador para Gurupi-TO está dando o seguinte erro em produção: 

> File "/app/__main__.egg/gazette/spiders/base/adminlte.py", line 40, in get_page_number
    stop = int(last_page)
           ^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

A tarefa aqui envolve dois aspectos:
1. investigar o que está acontecendo na página revisando a classe base [adminlte](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/base/adminlte.py) usando [Gurupi-TO](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/to/to_gurupi.py). 
2. Verificar como a correção em adminlte.py reflete em [Santana do Araguaia-PA](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/pa/pa_santana_do_araguaia.py), pois este raspador também utiliza adminlte como classe base, apesar de não estar dando erro em produção.

**Comment by claromes** [comment]
@trevineju Essa base foi escrita por mim. É ruim eu fazer essa revisão, já que o código é meu?

**Comment by claromes** [comment]
@trevineju Era só um "https". Resolvido.

**Comment by trevineju** [comment]
hahahaha ai, não acredito!!! @claromes
