### ISSUE TITLE
[Manutenção] Diversos municípios Siganet dando erro de DNS

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#1172]
Todos os municípios em produção que usam [siganet](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/base/siganet.py) estão quebrados em produção desde meados de maio/2024. Apontam o mesmo erro:

Afonso Cunha-MA: 
> [scrapy.downloadermiddlewares.retry] Gave up retrying <GET https://transparencia.afonsocunha.ma.gov.br/acessoInformacao/diario/diario/listarDiario > (failed 3 times): DNS lookup failed: no results for hostname lookup: [transparencia.afonsocunha.ma.gov.br](https://transparencia.afonsocunha.ma.gov.br/).

Axixá-MA:
> [scrapy.downloadermiddlewares.retry] Gave up retrying <GET https://transparencia.axixa.ma.gov.br/acessoInformacao/diario/diario/listarDiario > (failed 3 times): DNS lookup failed: no results for hostname lookup: [transparencia.axixa.ma.gov.br](https://transparencia.axixa.ma.gov.br/).

Boa Vista do Gurupi-MA:
> [scrapy.downloadermiddlewares.retry] Gave up retrying <GET https://transparencia.boavistadogurupi.ma.gov.br/acessoInformacao/diario/diario/listarDiario > (failed 3 times): DNS lookup failed: no results for hostname lookup: [transparencia.boavistadogurupi.ma.gov.br](https://transparencia.boavistadogurupi.ma.gov.br/).

Centro do Guilherme-MA:
> [scrapy.downloadermiddlewares.retry] Gave up retrying <GET https://transparencia.centrodoguilherme.ma.gov.br/acessoInformacao/diario/diario/listarDiario > (failed 3 times): DNS lookup failed: no results for hostname lookup: [transparencia.centrodoguilherme.ma.gov.br](https://transparencia.centrodoguilherme.ma.gov.br/).

Coroatá-MA:
> [scrapy.downloadermiddlewares.retry] Gave up retrying <GET https://coroata.ma.gov.br/diario/diario//listarDiario > (failed 3 times): DNS lookup failed: no results for hostname lookup: coroata.ma.gov.br.

Adicionalmente: `//` duplicado na URL

Maranhãozinho-MA:
> [scrapy.downloadermiddlewares.retry] Gave up retrying <GET https://transparencia.maranhaozinho.ma.gov.br/acessoInformacao/diario/diario/listarDiario > (failed 3 times): DNS lookup failed: no results for hostname lookup: [transparencia.maranhaozinho.ma.gov.br](https://transparencia.maranhaozinho.ma.gov.br/).

Nina Rodrigues-MA:
> [scrapy.downloadermiddlewares.retry] Gave up retrying <GET https://transparencia.ninarodrigues.ma.gov.br/acessoInformacao/diario/diario/listarDiario > (failed 3 times): DNS lookup failed: no results for hostname lookup: [transparencia.ninarodrigues.ma.gov.br](https://transparencia.ninarodrigues.ma.gov.br/).

São Vicente Ferrer-MA:
> [scrapy.downloadermiddlewares.retry] Gave up retrying <GET https://saovicenteferrer.ma.gov.br/diario/diario/listarDiario > (failed 3 times): DNS lookup failed: no results for hostname lookup: [saovicenteferrer.ma.gov.br](https://saovicenteferrer.ma.gov.br/).

Viana-MA:
> [scrapy.downloadermiddlewares.retry] Gave up retrying <GET https://transparencia.viana.ma.gov.br/acessoInformacao/diario/diario/listarDiario > (failed 3 times): DNS lookup failed: no results for hostname lookup: [transparencia.viana.ma.gov.br](https://transparencia.viana.ma.gov.br/).

Zé Doca-MA:
> [scrapy.downloadermiddlewares.retry] Gave up retrying <GET https://transparencia.zedoca.ma.gov.br/acessoInformacao/diario/diario/listarDiario > (failed 3 times): DNS lookup failed: no results for hostname lookup: transparencia.zedoca.ma.gov.br.

Todas as URLs hiperlinkadas acima existem e parecem conter diários recentes. É necessário investigar este comportamento.

**Comment by trevineju** [comment]
Não quis sair adicionando proxy em vários raspadores, por isso em #1177 experimentei em apenas um, Afonso Cunha-MA, para verificar se essa solução funcionaria.

Funcionou:
![image](https://github.com/okfn-brasil/querido-diario/assets/44185775/fdfae35c-738b-473f-b6ba-eedd3975f12f)
[requests_ma_afonso_cunha_491.json](https://github.com/user-attachments/files/15902076/requests_ma_afonso_cunha_491.json)

Visto que funcionou, fico com a duvida agora se é melhor adicionar a habilitação do proxy no arquivo da classe base siganet, assim todos os 10 casos listados são beneficiados -- mas outros no futuro também, talvez sem precisar -- ou se é melhor adicionar só nos raspadores individuais e tratar caso a caso. 

O que você acha, @ogecece?

**Comment by ogecece** [comment]
Melhor manter individual mesmo @trevineju :/ Dá um trabalhinho, mas é melhor não consumir recurso de proxy desnecessariamente

**Comment by trevineju** [comment]
@ogecece, beleza! obrigada
