### ISSUE TITLE
[Manutenção] Novo raspador para Maragogi-AL

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#1176]
Estamos sem dados de Maragogi-AL desde 15/abril/24. Este município não tem raspador próprio, pois fazia parte da associação de municípios, por isso, era coletado por [al_associacao_municipios.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/al/al_associacao_municipios.py)

Agora, os diários oficiais estão no endereço: https://maragogi.al.gov.br/diarios-oficiais/diario-oficial-2024

É necessário desenvolver um novo raspador para a URL

**Comment by gabrielqr** [comment]
Oii, estou tentando fazer esse :)

**Comment by trevineju** [comment]
> estou tentando fazer esse :)

boa, @gabrielqr! tem documentação aqui pra te ajudar: https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html

**Comment by gabrielqr** [comment]
@trevineju acredito que está pronto :) qualquer coisa me avisa
