### ISSUE TITLE
[Melhoria] Ajustar regex de coleta de metadado na classe base Adiarios

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#1187]
Conforme @rochamatcomp verificou em https://github.com/okfn-brasil/querido-diario/pull/1185#issuecomment-2210732124, ao executar o código 

``` python 
from datetime import date

from gazette.spiders.base.adiarios_v1 import BaseAdiariosV1Spider


class PbJacarauSpider(BaseAdiariosV1Spider):
    TERRITORY_ID = "2507309"
    name = "pb_jacarau"
    allowed_domains = ["jacarau.pb.gov.br"]
    BASE_URL = "https://www.jacarau.pb.gov.br"
    start_date = date(2019, 3, 7)
```
 aparece o erro:

> querido-diario/data_collection/gazette/spiders/base/adiarios_v1.py", line 41, in parse_page
    edition_number = re.search(r":\s*(\d+).*/", text).group(1)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

Os contextos em que esse erro aparece são: 

- Diário Oficial: EDIÇÃO ESPECIAL/2024
- Diário Oficial: EDIÇÃO ESPECIAL/2024 - Volume: 1 - Número: EDIÇÃO ESPECIAL de 16 de Abril de 2024 - EXECUTIVO 16/04/2024
- Diário Oficial: EDIÇÃO ESPECIAL/2024 - Volume: 1 - Número: EDIÇÃO ESPECIAL de 14 de Abril de 2024 - EXECUTIVO 14/04/2024
- Diário Oficial: EDIÇÃO ESPECIAL/2024 - Volume: 1 - Número: EDIÇÃO ESPECIAL de 1 de Abril de 2024 - EXECUTIVO 01/04/2024
- Diário Oficial: EDIÇÃO ESPECIAL/2024 - Volume: 1 - Número: EDIÇÃO ESPECIAL de 21 de Janeiro de 2024 - EXECUTIVO 21/01/2024
- Diário Oficial: EDIÇÃO ESPECIAL/2023 - - EXECUTIVO 30/11/2023
- Diário Oficial: EDIÇÃO ESPECIAL/2023 - DIÁRIO OFICIAL � EDIÇÃO ESPECIAL. - EXECUTIVO 23/11/2023
- Diário Oficial: EDIÇÃO ESPECIAL/2023 - DIÁRIO OFICIAL - EDIÇÃO ESPECIAL. - EXECUTIVO 19/11/2023
- Diário Oficial: EDIÇÃO ESPECIAL/2023 - EDIÇÃO ESPECIAL, DE 06 DE OUTUBRO DE 2023. - EXECUTIVO 06/10/2023
- Diário Oficial: EDIÇÃO ESPECIAL/2023 - DIÁRIO OFICIAL - EDIÇÃO ESPECIAL. - EXECUTIVO 26/04/2023
- Diário Oficial: EDIÇÃO ESPECIAL/2023 - DIÁRIO OFICIAL - EDIÇÃO ESPECIAL. - EXECUTIVO 20/04/2023
- Diário Oficial: EDIÇÃO ESPECIAL/2023 - DIÁRIO OFICIAL - EDIÇÃO ESPECIAL. - EXECUTIVO 02/01/2023
- Diário Oficial: EDIÇÃO ESPECIAL/2019 - PORTARIA Nº 118A, DE 07 DE MARÇO DE 2019 - NOMEAÇÃO DE MARLO SILVA DE LIMA. - EXECUTIVO 07/03/2019

## Tarefa 

É necessário atualizar o código de [adiarios_v1.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/base/adiarios_v1.py) para que o fluxo de coleta dos metadados, nesse tipo de situação, seja deixar `edition_number` vazio ( `edition_number = ""`) visto que a edição não tem número de fato, e trocar o campo `is_extra_edition` para `True` em caso da presença da palavra "especial"  

Visto que atualizar a classe base reflete em todos os raspadores que a utilizam, é importante testar a modificação com pb_jacarau e alguns outros raspadores do padrão, para confirmar.

**Comment by rochasigalei** [comment]
@trevineju posso resolver?
