### ISSUE TITLE
[Novo spider]: Maricá-RJ

### ISSUE THREAD

**Issue by slfabio** [okfn-brasil/querido-diario#1201]
### URL da forma de consulta

https://www.marica.rj.gov.br/jornal-oficial-marica/

### Período de publicação

julho/2006 até hoje

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui paginação, Possui filtro por data

### Observações

Edições ordinárias e extraordinárias são acessadas por links diferentes:
https://www.marica.rj.gov.br/jom/
https://www.marica.rj.gov.br/jom-especial/

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by janainamendes29** [comment]
Vou implementar esse Município

**Comment by slfabio** [comment]
Bom dia @trevineju,
uma dúvida: nessas issues de municípios que possuem sistemas próprios, a gente abre uma branch e um PR para município ou incluímios diversos municípios em um único PR?

**Comment by trevineju** [comment]
> Bom dia @trevineju, uma dúvida: nessas issues de municípios que possuem sistemas próprios, a gente abre uma branch e um PR por município ou incluímios diversos municípios em um único PR?

Bom dia, @slfabio. Nesse caso, uma branch/PR por município mesmo.
