### ISSUE TITLE
[Novo spider]: São João da Barra-RJ

### ISSUE THREAD

**Issue by slfabio** [okfn-brasil/querido-diario#1211]
### URL da forma de consulta

https://www.sjb.rj.gov.br/site/diarios_oficiais

### Período de publicação

janeiro/2019 até hoje

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui paginação

### Observações

Há um filtro por data, mas não funciona.
Os DOs passaram a ser publicados em documento único a partir de 16/01/2019. 
Anteriormente, os atos estão publicados individualmente em arquivos separados.

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by trevineju** [comment]
Issue substituída pela #1246
