### ISSUE TITLE
[Novo spider]: Teresópolis-RJ

### ISSUE THREAD

**Issue by slfabio** [okfn-brasil/querido-diario#1214]
### URL da forma de consulta

https://atos.teresopolis.rj.gov.br/diario

### Período de publicação

julho/2016 até hoje

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui filtro por data

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by Gabriel-gag** [comment]
Boa tarde, irei implementar esta issue.

**Comment by slfabio** [comment]
O site não disponibiliza link direto para download do PDF.
