### ISSUE TITLE
[Novo spider]: Magé-RJ

### ISSUE THREAD

**Issue by slfabio** [okfn-brasil/querido-diario#1219]
### URL da forma de consulta

https://mage.rj.gov.br/bio/

### Período de publicação

janeiro/2014 até hoje

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Observações

Edições quinzenais.
Edições anteriores a 2023 estão no link: https://mage.rj.gov.br/biosantigos/
Edições anteriores a 2014 estão PDF com conteúdo de imagem escaneada.

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by JP0ttoni** [comment]
vou implementar essa issue

**Comment by JP0ttoni** [comment]
boa tarde, o site não disponibiliza a data exata das edições, sendo assim não é possível separa por intervalos de tempo e nem separar por pastas dos dias.
