### ISSUE TITLE
[Novo spider]: Varre-Sai-RJ

### ISSUE THREAD

**Issue by slfabio** [okfn-brasil/querido-diario#1222]
### URL da forma de consulta

https://varresai.rj.gov.br/site/diarios_oficiais

### Período de publicação

setembro/2019 até hoje

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui paginação

### Observações

Mesmo layout de São João da Barra-RJ #1211 
Não abri issue sugerindo novo spider base pois no modelo informa que é necessário informar 3 prefeituras, no mínimo.

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by trevineju** [comment]
Issue substituída pela #1246
