### ISSUE TITLE
[Novo spider]: Carapebus-RJ

### ISSUE THREAD

**Issue by slfabio** [okfn-brasil/querido-diario#1223]
### URL da forma de consulta

https://carapebus.rj.gov.br/m/Diario_Oficial

### Período de publicação

junho/2021 até hoje

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui filtro por data

### Observações

Mesmo layout de Conceição de Macabu-RJ
Não abri issue sugerindo novo spider base pois no modelo informa que é necessário informar 3 prefeituras, no mínimo.

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by trevineju** [comment]
> Não abri issue sugerindo novo spider base pois no modelo informa que é necessário informar 3 prefeituras, no mínimo.

O 3 é meio arbitrário. Como temos mapeamentos que tem dezenas de municípios, escolhemos um numero mínimo para iniciar o desenvolvimento. Precisa, com certeza, ser mais de um caso pq se não, não precisaria de spider base.

Realmente é um padrão. Por isso substitui essa issue pela #1243
