### ISSUE TITLE
[Novo spider]: Conceição de Macabu-RJ

### ISSUE THREAD

**Issue by slfabio** [okfn-brasil/querido-diario#1224]
### URL da forma de consulta

https://www.conceicaodemacabu.rj.gov.br/m/Diario_Oficial

### Período de publicação

janeiro/2024 até hoje

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui filtro por data

### Observações

Mesmo layout de Carapebus-RJ #1223 
Não abri issue sugerindo novo spider base pois no modelo informa que é necessário informar 3 prefeituras, no mínimo.

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by trevineju** [comment]
Issue substituída pela #1243
