### ISSUE TITLE
[Manutenção] Corrigir raspador para Niterói-RJ

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario#1301]
O raspador para [Niterói-RJ](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/rj/rj_niteroi.py) não coleta diários em produção desde 2024-09-06. 

O site que funcionava em https://www.niteroi.rj.gov.br/do.html mudou para https://diariooficial.niteroi.rj.gov.br/ e as URLs de documento que atendiam o formato `http://www.niteroi.rj.gov.br/wp-content/uploads/do/{%Y}/{%m}_{%b}/{%d}.pdf` também mudaram. 

Por isso, é necessário:
- [ ] Reescrever o arquivo do raspador para atualizar seu código para coletar diários oficiais do novo site.

Missões secundárias (se der pra fazer também):
- [ ] Método `.parse()` está fazendo o papel de `.start_requests()`. Poderíamos fazer o uso mais [apropriado](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_requests) dos dois métodos e também remover o `.start_urls` que não está sendo usado.
- [ ] Lógica de iteração por datas no método `.parse()` poderia fazer uso de `dateutil.rrule` assim como é feito em [Rondonópolis-MT](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/rj/rj_niteroi.py)

**Comment by luandadantas** [comment]
Olá @ogecece!
Você já está trabalhando nessa issue? Caso não esteja, tenho interesse em contribuir

**Comment by trevineju** [comment]
oi, @luandadantas, pode fazer! vou te atribuir

**Comment by samueldsiqueira** [comment]
Bom dia, @luandadantas, tudo bem?
Gostaria de contribuir com projeto, sou iniciante!

**Comment by luandadantas** [comment]
Olá @samueldsiqueira! Tudo bem e você?
Também sou nova por aqui 😄  
Vou deixar aqui algumas sugestões que você pode seguir pra te ajudar a fazer sua primeira contribuição:
- Sugiro que faça o [folk](https://github.com/okfn-brasil/querido-diario/fork) do projeto na sua máquina 
- Siga as instruções que estão no [readme](https://github.com/okfn-brasil/querido-diario?tab=readme-ov-file#sum%C3%A1rio) 
- Configure o projeto na sua máquina, e tente [executar](https://github.com/okfn-brasil/querido-diario?tab=readme-ov-file#como-executar)
- Feito isso, dá uma olhada nas [issues](https://github.com/okfn-brasil/querido-diario/issues) do projeto e vê alguma que você tenha vontade ou curiosidade de fazer. (Importante validar se já não tem alguém trabalhando na issue que você escolher, qualquer coisa manda mensagem como fez aqui, mas na sua issue de interesse)
- E qualquer dúvida, fala com o @ogecece ou a @trevineju acredito que eles conseguem te orientar melhor 😄

**Comment by trevineju** [comment]
@luandadantas perfeitaaaa

**Comment by TLaidler** [comment]
Olá @ogecece  tudo bem? Esta issue ainda está aberta? Ainda posso contribuir?

**Comment by TLaidler** [comment]
Olá @ogecece , tudo bem? Não entendi, essa issue ainda está aberta? Cabe mais de um PR consertando o mesmo problema com finalidade de aprendizado? 

Abraços!

**Comment by trevineju** [comment]
> essa issue ainda está aberta? 

@TLaidler como você já fechou a PR e já comentou outra issue para fazer, entendo que já seguiu em frente, mas pra te responder... 

A issue fica aberta enquanto a PR não for aprovada (aliás, @luandadantas coloquei na fila de revisão e vou pegar para revisar nos próximos dias!). Então o ideal é ver se tem alguém atribuido e ler o histórico da conversa para entender se tá disponível ou não.

Se você ver uma issue em que alguém avisou que ia fazer ou já até tem uma PR vinculada, não vale a pena fazer retrabalho. Pode aprender fazendo alguma outra issue, visto que temos várias.

**Comment by TLaidler** [comment]
> > essa issue ainda está aberta?
> 
> @TLaidler como você já fechou a PR e já comentou outra issue para fazer, entendo que já seguiu em frente, mas pra te responder...
> 
> A issue fica aberta enquanto a PR não for aprovada (aliás, @luandadantas coloquei na fila de revisão e vou pegar para revisar nos próximos dias!). Então o ideal é ver se tem alguém atribuido e ler o histórico da conversa para entender se tá disponível ou não.
> 
> Se você ver uma issue em que alguém avisou que ia fazer ou já até tem uma PR vinculada, não vale a pena fazer retrabalho. Pode aprender fazendo alguma outra issue, visto que temos várias.

Entendido, muito obrigado pela atenção!
