### ISSUE TITLE
[Novo spider]: Cesário Lange-SP

### ISSUE THREAD

**Issue by lincolncpp** [okfn-brasil/querido-diario#1324]
### URL da forma de consulta

https://ecriediariooficial.com.br/cesariolange/

### Período de publicação

julho/2022 até o momento

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui paginação, Possui filtro por data

### Observações

Usa a plataforma eCrie

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by trevineju** [comment]
oi, @lincolncpp! O fato do site publicador ser `ecriediariooficial`, um dominio privado, ao invés de `algo.gov` me chamou atenção, no geral isso corresponde a um serviço publicador de documentos para muitos municipios... 
fecho essa issue pois foi substituida por #1327
