### ISSUE TITLE
[Novo spider]: Guareí-SP

### ISSUE THREAD

**Issue by lincolncpp** [okfn-brasil/querido-diario#1326]
### URL da forma de consulta

https://imprensaoficialmunicipal.com.br/guarei

### Período de publicação

fev/2019 até o momento

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui paginação, Possui filtro por data

### Observações

Tem filtro por data mas parece não funcionar. A paginação é feita de forma dinâmica no frontend, sem alterar a URL.

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by trevineju** [comment]
fecho essa também, pois esse sistema é o DOSP e esse município está mapeado na listagem #1087
