### ISSUE TITLE
[Novo spider]: Divinópolis-MG

### ISSUE THREAD

**Issue by laurafcamargos** [okfn-brasil/querido-diario#1328]
### URL da forma de consulta

https://www.diariomunicipal.com.br/amm-mg/

### Período de publicação

05/2010 até atualmente

### Formato da publicação

Os diários oficiais são publicados em outros formatos (ex. DOC, HTML, etc)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui filtro por data

### Observações

Existe vários filtros para realizar a busca e tudo é feito no sistema da Associação Mineira dos Municípios.

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by trevineju** [comment]
olá, @laurafcamargos! Nós já temos [o raspador para a associação de municípios de Minas Gerais](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/mg/mg_associacao_municipios.py). 

Por isso, fecho a issue. 

Muito obrigada
