### ISSUE TITLE
O sp_guaruja.py de Guarujá não está funcionando

### ISSUE THREAD

**Issue by fbrandao2k** [okfn-brasil/querido-diario#140]
Boa tarde,

O código de raspagem para a prefeitura de guarujá não está funcionando. Acredito que seja porque o site da prefeitura foi mudado faz pouco tempo e a estrutura do site do diário oficial foi mudada.

Muito obrigado.

**Comment by julianyraiol** [comment]
Oi, pessoal! Boa tarde!
Vi que o site da prefeitura está com uma estrutura diferente mesmo. 

Pensei em utilizar Selenium para fazer as interações com o calendário e fazer a raspagem dos diários oficiais. 

O que acham? 

http://www.guaruja.sp.gov.br/edicoes-diario-oficial/

**Comment by jvanz** [comment]
Oi @julianyraiol, muito legal ver que você tem interesse em ajudar! Ficamos muito felizes! 

Pq pretende utilizar o selenium? Atualmente utilizamos o scrapy e tem funcionado bem. Já tentou ver porque o spider não está funcionando?

Se você não sabe como o scrapy funciona, eu escrevi um artigo tentando ser o mais didático possível. Da uma olhada [aqui](http://jvanz.com/como-funciona-o-robozinho-do-serenata-que-baixa-os-diarios-oficiais.html#como-funciona-o-robozinho-do-serenata-que-baixa-os-diarios-oficiais). Talvez ajude.

Uma última coisa, o projeto pede que a comunicação seja feita em [inglês](https://github.com/okfn-brasil/serenata-de-amor/issues/87). Se você não se sente confortável, nos avise. Podemos ajudar com isso também. Você pode encontrar ajudar contatando os contribuidores diretamente ou procurando alguém o grupo do projeto no Telegram. O nome do grupo é "Serenata de Amor"

**Comment by julianyraiol** [comment]
Oi, @jvanz! 

Cheguei a trabalhar em um crawler com Selenium. Ele está nesse repositório [aqui](https://github.com/julianyraiol/diario-oficial-guaruja)

Beleza, vou utilizar o inglês :pig:

**Comment by jvanz** [comment]
> > Cheguei a trabalhar em um crawler com Selenium. Ele está nesse repositório [aqui](https://github.com/julianyraiol/diario-oficial-guaruja)
> 
> One of the problems of using the selenium is it requires a browser to work. In a production environment we do not have a browser, we do not even have a graphical interface. Which make impossible to run the selenium crawler.

@julianyraiol I just discover that the web browser driver allow to run it in headless mode (without graphical mode). So, my previous comment is not  right. I'm sorry for that.

However, I still believe that the scrapy spider should be our first choice. Just to keep the project more concise and easy to maintain. Are you willing to translate your to crawler to a spider? :)

**Comment by phrfpeixoto** [comment]
I'll try to look into this. I don't think Selenium is required here.

**Comment by phrfpeixoto** [comment]
PR Submitted.

**Comment by rennerocha** [comment]
Closing stale issue.
