### ISSUE TITLE
Como colaborar com o projeto?

### ISSUE THREAD

**Issue by alfakini** [okfn-brasil/querido-diario#158]
Olá pessoal!

Em 2018 fizemos um mutirão no Fab Lab Joinville para criar spiders para diversas cidades. Olhando por cima, tem uns 15 PRs abertos daquela época.

Gostaria de levar novamente o projeto para o laboratório semanal de Computação, onde trazemos projetos para que os participantes contribuam. Porém, não está muito claro para mim como podemos contribuir com ele.

Seria o caso de revisarmos os spiders com PR em aberto?

Ou então criar um portal para visualização dos diários oficiais?

Ou ainda, extrair dados dos diários já coletados?

Gostaria de poder contribuir com o projeto, e temos tempo e pessoas dispostas a colaborar.

Fico no aguardo de um retorno :)

Abraço!

**Comment by jvanz** [comment]
Oi @alfakini !

> Em 2018 fizemos um mutirão no Fab Lab Joinville para criar spiders para diversas cidades. Olhando por cima, tem uns 15 PRs abertos daquela época.
> 
> Gostaria de levar novamente o projeto para o laboratório semanal de Computação, onde trazemos projetos para que os participantes contribuam. Porém, não está muito claro para mim como podemos contribuir com ele.
> 
> Seria o caso de revisarmos os spiders com PR em aberto?

Acho que seria um ótimo começo. Na verdade, eu gostaria de fazer um limpeza nas PR abertas. Ver o que funciona ou que não funciona, arrumar e fazer a mesclagem. Acho que seria uma boa para quem estiver começando.

Além disso, adicionar novos spider é algo sempre necessário. Santa Catarina é o estado mais coberto no momento. Mas seria legal adicionar os municípios faltantes e retestar os que existem. ;)

> Ou então criar um portal para visualização dos diários oficiais?

Isso é uma discussão que começou alguns dias atrás. Da uma olhada na issue #157.
 
> Ou ainda, extrair dados dos diários já coletados?

Até onde eu sei não existe nenhum tipo de analise feita em cima dos diários das cidades. Se tiver alguém interessado. Manda ver.

**Comment by jvanz** [comment]
One more thing: https://github.com/okfn-brasil/serenata-de-amor/issues/87

**Comment by alfakini** [comment]
Thanks for the reply @jvanz. We will start by reviewing all spiders PRs in the next days :)

**Comment by jvanz** [comment]
@alfakini some news? Can I help you somehow?

**Comment by jvanz** [comment]
I think I should write a documentation about how to contribute to the project....

**Comment by chuvi** [comment]
Olá! Em relação às capitais que não aparecem na lista, tratam-se de casos em que há projetos em andamento ou em relação aos  quais não foi iniciado qualquer projeto? Meu interesse específico é por Porto Alegre/RS.

**Comment by jvanz** [comment]
As que não estão na lista é porque já existem. Porém, nada impede você de rodar o spider e ver se ainda funciona e arrumar se necessário. Ficaria muito grato se fizer isso com Porto Alegre. Mas também te encorajo a fazer para outras capitais. :)

**Comment by jvanz** [comment]
@chuvi As que não estão na lista é porque já existem. Porém, nada impede você de rodar o spider e ver se ainda funciona e arrumar se necessário. Ficaria muito grato se fizer isso com Porto Alegre. Mas também te encorajo a fazer para outras capitais. :)

**Comment by chuvi** [comment]
> @chuvi As que não estão na lista é porque já existem. Porém, nada impede você de rodar o spider e ver se ainda funciona e arrumar se necessário. Ficaria muito grato se fizer isso com Porto Alegre. Mas também te encorajo a fazer para outras capitais. :)

Obrigada pela resposta! Farei!

**Comment by Urahara** [comment]
Acho que poderiamos melhorar a forma do usuário contribuir (principalmente a parte de criação ou correção de bugs). Trabalhar utilizando usando apenas o shell do docker é complicado, com ajuda da IDE por ex (VisualStudio, Pycharm) já da uma maior liberdade pro usuário trabalhar.

**Comment by jvanz** [comment]
> Acho que poderiamos melhorar a forma do usuário contribuir (principalmente a parte de criação ou correção de bugs). Trabalhar utilizando usando apenas o shell do docker é complicado, com ajuda da IDE por ex (VisualStudio, Pycharm) já da uma maior liberdade pro usuário trabalhar.

Creio que a maior parte do pessoal que manda PR já utilize algum tipo de IDE.  Eu não uso IDE (uso vim). Ms toda contribuição para adicionar facilidades no projeto é bem vinda. As IDEs já tem integração com docker-compose e/ou docker? Que tipo de dificuldades vc está tendo com o docker? ;)
 
> E também em relação a algumas dependências por ex: scrapy-deltafetch que depende de ter instalado bsddb3 instalado. 

É por isso que é utilizado o docker. Nada precisa ser instalado na sua máquina. 

> Outra coisa acho que hoje em dia poderiamos adotar o Pipfile que é muito mais intuitivo (já cria o virtualenv, etc)

PR são sempre bem vindas! :)

**Comment by rennerocha** [comment]
Documentação para colaborar com o projeto está disponível em:
https://docs.queridodiario.ok.org.br/
