### ISSUE TITLE
Enable PDF upload to Google Cloud Storage

### ISSUE THREAD

**Issue by Irio** [okfn-brasil/querido-diario#16]
**This issue is intended for people with little to no experience with open source contributions.**

Nowadays, every time a Scrapy spider is run, the gazette PDF is saved and stored in the local filesystem, more specifically in the `/mnt/data/` folder.

https://github.com/okfn-brasil/diario-oficial/blob/490270da0201471b9968268cd2eb0e9bde272310/processing/data_collection/gazette/settings.py#L10

When in a development environment, we still want to have files stored in the local filesystem, in this same folder. When in a production environment, the file should be sent to Google Cloud Storage.

Ideally, this behavior should be defined by an environment variable such as `FILES_STORAGE`.

Scrapy's documentation on the topic:
https://doc.scrapy.org/en/latest/topics/media-pipeline.html#id1

**Comment by Irio** [comment]
All yours, @tramasoli. Open a pull request once you feel comfortable with the result.

**Comment by tramasoli** [comment]
Great! I'll do it then.
I'm not familiar with GCS API yet neither with this project, so I'll just ask a little patience from you guys as I'm doing this in my spare time :)

**Comment by Irio** [comment]
Since @tramasoli have not posted [updates for more than a month](https://github.com/okfn-brasil/diario-oficial/blob/8bd4846fac03f131a41799aac128b0db740c0717/CONTRIBUTING.md#starting-to-contribute), I'm happy to give the task to a new contributor.

**Comment by ilosamart** [comment]
Sorry :( I totally forgot this :(

**Comment by danielSbastos** [comment]
Hi, can I try to solve this?

**Comment by rennerocha** [comment]
@danielSbastos go ahead!!!

**Comment by rennerocha** [comment]
We will use Digital Ocean Spaces to store downloaded data in production, so this issue is outdated.
