### ISSUE TITLE
Production infrastrucure configuration

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario#160]
We need to have scripts to setup and configure a production environment for running the spider. 

My suggestion is use [Ansible](https://github.com/ansible/ansible) for that job. We can used to configure, install and update the servers running the workloads. It is easy to use and does not require anything installed in the server. All configuration is done via ssh.

Related to issue #157

**Comment by jvanz** [comment]
I suggest to have a separated repository for this scripts and files.

**Comment by jvanz** [comment]
https://github.com/jvanz/serenata-automation

**Comment by jvanz** [comment]
I'm running the spider on a production server! :)

```
root@ubuntu-s-4vcpu-8gb-nyc1-01:~# find /var/diario/data/ -name "*.txt" | wc -l 
93595
```

93595 file downloaded so far.

**Comment by sergiomario** [comment]
@jvanz Did you run the spiders with a start date?

**Comment by jvanz** [comment]
Nops, they are downloading all the files for the first time. Thus, I think we can test the cache middleware and the performance of the machine running almost all the spider at the same time.

**Comment by giuliocc** [comment]
@jvanz tu acha que essa issue ainda é relevante ou já cobrimos o necessário pra infra de prod nesse repo?

---

### English

@jvanz do you think this issue is still relevant or did we cover the necessary for production infrastructure in this repo?

**Comment by rennerocha** [comment]
We have a production infra already in place. This is not relevant now. If we want to do changes in our production environment, we need to open a new issue for that.
