### ISSUE TITLE
WebUI to find and visualize the gazettes

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario#161]
In order to have the gazettes available to the public, we need to have a WebUI to allow the user to search the files by city and dates. The initial idea is using Django for that. 

Related to issue #157

**Comment by alexandrevicenzi** [comment]
@jvanz perhaps it would make sense to create a Web App using React or Vue and connecting it to an API. 

API could be also used by others such as a data source on Spark, on Jupyter or mobile apps, or other tools.

WDYT?

**Comment by jvanz** [comment]
> @jvanz perhaps it would make sense to create a Web App using React or Vue and connecting it to an API.
> 
> API could be also used by others such as a data source on Spark, on Jupyter or mobile apps, or other tools.
> 
> WDYT?

Yes. That's the plan. The API is under development. The current version is a simple REST API query the gazettes from a ES index. But nobody is coding the web interface. ;)

**Comment by alexandrevicenzi** [comment]
@jvanz do we have any mockups or ideas of how it should look like? I may be able to spin a barebone project to start the UI.

- React or Vue?
- Material design or Bootstrap?

I find it easier to use something that is already in place, like MD or BS4.

We would also need a new repository for UI.

**Comment by jvanz** [comment]
@sergiomario can help on that. I do not know if there is a mock up already. I do not think so... but he knows more about that.

**Comment by sergiomario** [comment]
@alexandrevicenzi indeed, We need a new repository for this.

- React or Vue?
    - I like the Vue framework in a generic way, but I need opinions from people more experts in front-end to make this choice compared to React.
- Material design or Bootstrap?
    - Bootstrap @ArianeCamilo? (We use the bootstrap base on all okbr static pages).

**Comment by giuliocc** [comment]
Closing this because the UI is finally done (https://queridodiario.ok.org.br) \o/. Please refer to [querido-diario-frontend](https://github.com/okfn-brasil/querido-diario-frontend) (or the equivalent Front End for Querido Diário).
