### ISSUE TITLE
Feira de Santana's gazette not working after city hall website changes

### ISSUE THREAD

**Issue by anapaulagomes** [okfn-brasil/querido-diario#176]
FYI: Feira de Santana's city hall made changes to their website certificate. The [city's spider](https://github.com/okfn-brasil/diario-oficial/blob/master/processing/data_collection/gazette/spiders/ba_feira_de_santana.py) isn't working after this change (made around the 5 of June).

**Comment by anapaulagomes** [comment]
We have been using [this spider in our repo too](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/master/scraper/spiders/gazette.py). I appreciate any ideas on how to solve this issue (in case we find a solution first, I'll give you an update).

**Comment by Laerte** [comment]
Hi! @anapaulagomes 

The problem is in the certificate, it is poorly configured and it only accepts insecure ciphers that most libraries do not support nowadays.

You can take a look on SSL Labs report [here](https://www.ssllabs.com/ssltest/analyze.html?d=www.diariooficial.feiradesantana.ba.gov.br).

I tried out using `curl`, `wget` and also `requests` module and nothing works because of the cipher suite, we can't even get a handshake properly.

I believe that this change was not intentional.

**Comment by anapaulagomes** [comment]
Thanks for the update, @Laerte. I've updated the issue description to be fair. [Here](https://github.com/scrapy/scrapy/issues/2916#issuecomment-643675542) instructions of how to make it work (I haven't manage to do it yet).

**Comment by anapaulagomes** [comment]
I just opened a request to the city hall to make it available by machine again. Usually, they ignore the requests but let's see how it goes.

**Comment by Laerte** [comment]
Using the cURL command that they give works fine here. I will do more tests today and update here if I can make it work.

**Comment by Laerte** [comment]
Hi @anapaulagomes!

Based on the thread that you mentioned i was able to create [Dockerfile](https://github.com/Laerte/diario-oficial-bad-ssl/blob/master/Dockerfile) that install a custom OpenSSL version (1.0.2g) and also compile Python 3.6.2 using the same version of OpenSSL.

I also copied the  spider to container and [set it up](https://github.com/Laerte/diario-oficial-bad-ssl/blob/master/gazette/gazette/settings.py#L91) the parameter `DOWNLOADER_CLIENT_TLS_METHOD` to use `TLSv1.0`.

Can you clone the [repository](https://github.com/Laerte/diario-oficial-bad-ssl.git) and then run on your side and see if works for you?

You can use make file: `make build` and them `make run` to get up and running! :)

Knowing that we have to manually compile Python using a custom version of OpenSSL that supports those insecure ciphers, do you have any idea how we can integrate this to project? 

Thanks!

**Comment by anapaulagomes** [comment]
Well done, @Laerte! 🥇 It works like a charm. I have no idea how we can integrate it into this project. But I'm asking around. Let's see if we can come up with a solution for it.

**Comment by jvanz** [comment]
Hmm, the first workaround that come to my mind is create another container image with another version of the openSSL and document why it exists to make everybody aware of that.  We can even add a make target to use this custom container and keep the old container image as the default. Something like this:

`make run_spider_insecure`

Similar to what we have [today](https://github.com/okfn-brasil/diario-oficial/blob/main/Makefile#L20)

Furthermore, move the custom TLS configuration that you have in the project [to the spider](https://docs.scrapy.org/en/latest/topics/settings.html#settings-per-spider). Thus, we keep all the other spider using the default value as usual.

**Comment by anapaulagomes** [comment]
Yesterday we complained once more about this situation on Twitter and it seems that something has changed: now it is possible to crawl the gazette's website again (still an insecure page though). :)
Since the change was made yesterday and the secretary said that the IT team should be done by the end of this week, I'll keep a close eye on it (you never know, right?). I'll keep you posted.

**Comment by anapaulagomes** [comment]
The crawler is working so far. :) Thank you all!
