### ISSUE TITLE
Rio Branco spider

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario#179]
Add an spider for Rio Branco, capital of Acre

**Comment by rennerocha** [comment]
All cities of Acre shares the same gazette located in http://www.diario.ac.gov.br/ .
How do you want to handle this scenario?

**Comment by jvanz** [comment]
Yeah, @julianyraiol was working on this. I believe we can use a spider for the whole state and documented this somewhere. Extract specific city data we need a post processing process which will require more than a single spider.

**Comment by giuliocc** [comment]
Hey, @rennerocha! Wanna get a look at #195 and give some feedback too? I'm currently trying to solve this issue.

**Comment by rennerocha** [comment]
Closing stale issue.
