### ISSUE TITLE
Macapá spider

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario#180]
Add an spider for Macapá, capital of Amapá

**Comment by phrfpeixoto** [comment]
I'll be working on this one. Or at least I'll try.

**Comment by rennerocha** [comment]
@phrfpeixoto there is already a PR open of a Macapá spider almost ready for merge.

**Comment by phrfpeixoto** [comment]
Oh, sure. My bad, I didn't see that reference up there.
