### ISSUE TITLE
Texto do arquivo CONTRIBUTING.md está desatualizado

### ISSUE THREAD

**Issue by sergiomario** [okfn-brasil/querido-diario#203]
Texto atual:
`At this moment, the project aims for the 100 top Brazilian municipalities by population, collecting all the gazettes since 2015. If you want to help us reach this goal, we're tracking the progress of crawlers in CITIES.md file. Have a look at it if you want to know where contributors are already working.`

**Qual o problema?**
O objetivo de escrever *crowlers* para as 100 cidades mais populosas não faz mais sentido para o projeto.

**Qual a solução?**
Definir uma outra meta, ex: 1000 cidades aleatórias do Brasil, ou todas as cidades com mais de 100 mil habitantes.

**Comment by gabrielbchacon** [comment]
Fiz uma pesquisa meio rápida aqui pensando na sua proposta. Em 2019 tínhamos 324 municípios dentro dessa faixa acima dos 100 mil habitantes, correspondendo a algo próximo de 60% da população. Ainda não tenho noção da dificuldade de replicar os crowlers para dizer se isso é viável ou não, mas me parece uma boa próxima meta. Gosto do corte por habitante porque norteia o projeto para impactar o maior número de pessoas. 

A depender da força de trabalho que existe para esse projeto podemos pensar em perfilar as cidades e definir uma abrangência por perfil de cidade. Por exemplo: (usando o corte por habitante) Escrever crowlers para 50% dos municípios pequenos, médios e grandes. A ideia de criar perfil ajuda a não "marginalizar" municípios menores que podem se beneficiar da coleta dessas informações.

**Comment by jvanz** [comment]
Acho focar nas cidades com maior número de habitantes é uma boa ideia.  Se quiser abre um PR atualizando o documento, ficamos gratos. :)

O que vc acha @sergiomario ?

**Comment by sergiomario** [comment]
Concordo!

**Comment by giuliocc** [comment]
Com o censo dos sistemas de diário municipais estabelecendo que o objetivo é listar todos os diários do _executivo_, então as metas do projeto poderiam ser então:

1. Capitais
2. Cidades com 100mil+ habitantes
3. Todos os diários municipais do poder executivo

?

**Comment by jvanz** [comment]
> Com o censo dos sistemas de diário municipais estabelecendo que o objetivo é listar todos os diários do _executivo_, então as metas do projeto poderiam ser então:
> 
>     1. Capitais
> 
>     2. Cidades com 100mil+ habitantes
> 
>     3. Todos os diários municipais do poder executivo
> 
> 
> ?

Eu diria que o foco poderia estar nas duas primeiras opções. Todos os municípios é um objetivo de muito longo prazo  e outras prioridade podem surgir nesse meio tempo. Por isso, acho que as duas primeiras opções já são um objetivo bem ambicioso considerando nosso atual número de pessoas contribuidoras.
