### ISSUE TITLE
Create Issues and Pull Request templates

### ISSUE THREAD

**Issue by davibusanello** [okfn-brasil/querido-diario#204]
### Reasons: 

- Reduces the starting curve to new contributors and improve the quality of life of the maintainers.

- A minimum pattern for creating an issue or pull request

### How to

[Using templates to encourage useful issues and pull requests](https://docs.github.com/en/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests)

### Doubts:

- [ ] What is the minimum required information to create a new issue or a new pull request?

**Comment by giuliocc** [comment]
Hi @davibusanello ! Great suggestion :)

I personally like the idea if they are clear and objective. Do you have any in mind?

**Comment by jvanz** [comment]
As the project is not sooo active, there is no recurrent  reported issues. So, we do not need to create to much bureaucracy yet. But I think we can start with something like bug report. For example, report if a spider is not working or any other issue the user is facing our project. 

For pull request I think we can add some template for new spiders and another for other changes.  Actually, we can have one template asking for the user well define what the purpose of the PR.

**Comment by giuliocc** [comment]
Those would be great templates to start ;)

**Comment by rennerocha** [comment]
Split this issue in two: https://github.com/okfn-brasil/querido-diario/issues/610 and https://github.com/okfn-brasil/querido-diario/issues/611, so they can be worked separately.
