### ISSUE TITLE
Docket-console Makefile

### ISSUE THREAD

**Issue by camilafracaro** [okfn-brasil/querido-diario#207]
Olá! Participei do Sprint hoje e sou uma das usuárias de Windows 7. Fiz o download do Docket Toolbox e fui rodar o makefile manualmente.
Quando chega na parte de make seed, eu consigo rodar o primeiro comando, mas o segundo dá esse erro:
"Starting diario-oficial_postgres_1 ... done
wait-for-it: waiting 15 seconds for postgres:5432
wait-for-it: timeout occurred after waiting 15 seconds for postgres:5432
" does not existtabase "gazette
"

Alguma luz em como fazer funcionar? Esse era o problema que o Vanz disse que estava tendo?

**Comment by jvanz** [comment]
Sim, creio que **pode** ser relacionado ao que estava enfrentando também. Acho que encontrei uma solução para o problema e estou testando ela. Porém, no comando 'make' existe um segundo erro que está sendo resolvido pela @brunanayara . Mas esse segundo erro não deveria impedir de rodar o spider. @camilafracaro , assim que terminar os meus testes, eu aviso. Assim você pode testar por ai também.

**Comment by jvanz** [comment]
@camilafracaro can you test it again with the latest version?

**Comment by camilafracaro** [comment]
Oi @jvanz,
Eu coloquei lá no Telegram e o erro é o mesmo de antes. Eu tentei rodar o make sql antes pra ver se tinha algo a ver com isso, mas não deu certo tb. Parece que está faltando eu rodar algo antes, mas não sei o que é. 
Agora pelo menos eu baixei um programa que funciona com o Make do Mac que se der certo eu coloco lá no Readme. Assim pelo menos não preciso ficar rodando manualmente.
Aliás, isso era uma dúvida que eu tinha, toda vez que vamos rodar o spider, temos que rodar o make, certo?

**Comment by jvanz** [comment]
> Oi @jvanz,
> Eu coloquei lá no Telegram e o erro é o mesmo de antes. Eu tentei rodar o make sql antes pra ver se tinha algo a ver com isso, mas não deu certo tb. Parece que está faltando eu rodar algo antes, mas não sei o que é.
> Agora pelo menos eu baixei um programa que funciona com o Make do Mac que se der certo eu coloco lá no Readme. Assim pelo menos não preciso ficar rodando manualmente.

Documentar o que foi preciso para rodar no seu ambiente é sempre legal. Removemos a base de dados no projeto. O make não configura mais a base de dados. Se o seu projeto ainda está tentando preparar o PostgreSQL você está com o projeto desatualizado. 

> Aliás, isso era uma dúvida que eu tinha, toda vez que vamos rodar o spider, temos que rodar o make, certo?

Não. Você precisar rodar os `make setup` apenas uma vez. Você só precisa rodar novamente caso queira recriar os containers.
