### ISSUE TITLE
Travis is failing due lack of .env file

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#218]
After creating a new PR, Travis [build failed](https://travis-ci.org/github/okfn-brasil/querido-diario/builds/719457384)

This is the error:
`ERROR: Couldn't find env file: /home/travis/build/okfn-brasil/querido-diario/.env`

As I just introduce a new spider and did no changes in project infrastructure, it is very unlikely that it is related to my PR.

**Comment by jvanz** [comment]
The issue is caused by a recent change in the Makefile, when we added the `destroy` target. The `destroy` is executed before the `setup` target then the `.env` file is not there yet. Causing the error. I've push a fix for that. ;)
