### ISSUE TITLE
Hints for people using Windows

### ISSUE THREAD

**Issue by raimundomarciano** [okfn-brasil/querido-diario#222]
# Hints for people using Windows

Some people using Windows reported difficulties installing some dependencies, such as Docker. I have used WSL with Ubuntu 20.04 LTS, which is like a mini-Linux besides my Windows 10. 

If you are doing the same, here are two suggestions:

- Update WSL to WSL 2 before trying to install Docker / Docker-composer. It may be a lengthy process but it seems to solve some connection problems. [Microsoft's tutorial](https://docs.microsoft.com/pt-br/windows/wsl/install-win10) is quite nice to follow.
- Install [Docker Desktop](https://www.docker.com/products/docker-desktop). It should be running and the option concerning integration with WSL2 must be active for things to work properly. Pay attention to the fact that Docker Desktop is activated as a common Windows application, so go for it as you would for any Windows program, do not try to open it from your WSL terminal. If you face problems like 

> 'Couldn't connect to Docker daemon at http+docker://localhost - is it running?'  

It is likely that your Docker Desktop is not running.

# Dicas para pessoas tentando usar o projeto no Windows 

Algumas pessoas reportaram algumas dificuldades quando tentam executar alguns passos, como instalar o Docker. Estou usando o WSL com o Ubuntu 20.04 LTS, que é basicamente um mini-Linux junto com meu Windows 10.

Se você também usa o WSL, duas sugestões:

- Atualize para o WSL 2 antes de tentar instalar o Docker / Docker-composer. Esse processo demorou bastante aqui, mas aparentemente é a solução para alguns problemas de conexão que aparecem no processo de instalação. Achei o [tutorial da Microsoft](https://docs.microsoft.com/pt-br/windows/wsl/install-win10) bem bacana.
- Instale o [Docker Desktop](https://www.docker.com/products/docker-desktop). É importante que ele esteja rodando e com a opção de integração com o WSL2 ativada para que as coisas funcionem direitinho. O Docker Desktop é aberto usando o próprio Windows, não o terminal do WSL.  Se quando você for rodar o "make setup" no WSL aparecer: 

> 'Couldn't connect to Docker daemon at http+docker://localhost - is it running?'  

É bem capaz que seja algum problema com o Docker Desktop (ele não esteja rodando ou não esteja com a integração com o WSL2 ativa).

**Comment by jvanz** [comment]
Please, add tips  in some documentation file in the project. Open a PR for that. ;)

**Comment by alexandrevicenzi** [comment]
I created #266 to start some sort of documentation.

**Comment by rennerocha** [comment]
Closed by https://github.com/okfn-brasil/querido-diario/issues/266
