### ISSUE TITLE
Adicionar link dos diários oficiais no Wikipedia das Prefeituras?

### ISSUE THREAD

**Issue by georgevbsantiago** [okfn-brasil/querido-diario#234]
Tenho utilizado o o [link do Wikipedia ](https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_da_Bahia_por_popula%C3%A7%C3%A3o_(2019)) para buscar os diários oficiais das prefeituras municipais por ordem decrescente de população. 

Seria interessante fazer um script para inserir o link do diário oficial nas informações das respectivas prefeituras municipais?
Ex: [Salvador](https://pt.wikipedia.org/wiki/Salvador). Consta o endereço principal da Prefeitura e da Câmara. Seria interessante acrescentar e manter atualizado o endereço do diário oficial?
Ou, ainda, uma página no Wikipedia relacionando o município e os seus respectivos diários oficiais (Prefeitura, Câmara....)?

**Comment by chicocvenancio** [comment]
Recomendo que discutam isso antes na Wikipédia. Além de ser necessário respeitar a política de bots, não tenho certeza se o link para o diário municipal será desejável.
