### ISSUE TITLE
Update scrapy

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario#240]
We've requested a [feature](https://github.com/scrapy/scrapy/issues/4677) in the scrapy lib. They implemented that for us. Check if it is already released and update the version in use in our project. After the update, we can remove this [hack](https://github.com/okfn-brasil/querido-diario/blob/main/processing/data_collection/gazette/pipelines.py#L120-L152),

**Comment by rennerocha** [comment]
We are using a Scrapy version that was released 11 months ago. There are many improvements and bug fixes during this time that is a good reason to update it to the latest version. I will work on that today.

**Comment by rennerocha** [comment]
Scrapy version [was updated](https://github.com/okfn-brasil/querido-diario/pull/242), so we don't need this hack anymore. However, I noticed that `QueridoDiarioFilesPipeline` and `RequestWithItem` are never used in the code, so they can be simply removed. I will open a new issue so we can configure the pipeline to store the files following a pattern based on item.

**Comment by jvanz** [comment]
> o
For documentation and project history reasons:

Actually, they was used in a integration test with Digital Ocean Spaces. But I did not enable it by default because it was not necessary. As the scrapy fix came first the production environment we can delete the code as you said.
