### ISSUE TITLE
Automatically sort imports in pre-commit to follow PEP8 rules

### ISSUE THREAD

**Issue by Jefersonalves** [okfn-brasil/querido-diario#241]
Currently, `black` is executed in the pre-commit stage, but it didn't change the order of the imports.
This issue is about how to handle with this problem in the pre-commit stage.

[PEP8](https://www.python.org/dev/peps/pep-0008/#imports) recommends that imports be ordered as follows:

1. Standard library imports.
2. Related third party imports.
3. Local application/library specific imports.

@rennerocha suggested using [isort](https://github.com/PyCQA/isort), where its execution would come before `black`

**Comment by rennerocha** [comment]
The way `black` and `isort` formats the imports differs, so `isort` **needs** to be executed **before** `black`, or else build will fail.

**Comment by jaswdr** [comment]
I want to work on this issue, will send a PR soon

**Comment by jaswdr** [comment]
@rennerocha PR sent, waiting for review

**Comment by phalmeida67** [comment]
> a

Sabem me informar quando irão disponibilizar os dados do CNPJ liberados na Receita Federal?
