### ISSUE TITLE
Add spider monitoring

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#248]
During the discussions of #247 a suggestion was made to verify the ratio `number_of_requests / items_scraped`. A higher ratio may be a sign that the spider is doing more requests than necessary and it can be a performance issue.

[Spidermon](https://spidermon.readthedocs.io/en/latest/) is an extension designed for spider monitoring that allows us to create custom monitors that will be executed every time a spider is executed.

It will be interesting to include this monitoring tool to the project and later, when the project is in production, add more checks that would ensure that everything will be working fine.

Suggested steps for this issue:
- [ ] Add Spidermon as project dependency and enable it in the project
- [ ] Create a new Monitor Suite
- [ ] Create a new monitor that will check the ratio `number_of_requests / items_scraped`. This monitor will fail if the ratio is higher than a configurable threshold (so we can define different threshold for different spiders if needed)

**Comment by rennerocha** [comment]
@andrewmiko 

If you have any problem configuring Spidermon just let me know. Following Spidermon [tutorial](https://spidermon.readthedocs.io/en/latest/getting-started.html) should be enough for you to understand how to enable it and create one basic monitor.

For this issue, it is not necessary yet to define actions to be taken when the monitor fail. This will be decided later when we have spiders running in production.

**Comment by andrewmiko** [comment]
OK. Sounds very good. Please assign this issue to me. I'll try to work on it later this week. 👍

**Comment by andersonberg** [comment]
Is this issue being handled yet? If not, can I start it?

**Comment by andrewmiko** [comment]
@andersonberg I think that you can take this one. Currently, I'm busy in other projects. Cheers.

**Comment by andersonberg** [comment]
Thank you, @andrewmiko

**Comment by rennerocha** [comment]
Closed by #304
