### ISSUE TITLE
Avoid downloading PDFs while testing

### ISSUE THREAD

**Issue by phrfpeixoto** [okfn-brasil/querido-diario#256]
The current code for the the `ExtractTextPipeline` blindly accesses the first element on the `item['files']` list, on line 37:

https://github.com/okfn-brasil/querido-diario/blob/a241eba2d41c2dca9bfa70565f954e6c2dfcc3f3/processing/data_collection/gazette/pipelines.py#L25-L41

This prevents the developer from crawling gazettes while avoiding downloading large PDF files (which on some sites can be slow), which is very useful while writing the spider code and testing agains the live website.

**Comment by phrfpeixoto** [comment]
Similar bug in `SQLDatabasePipeline`

**Comment by jvanz** [comment]
Text extraction has been removed form the pipeline. Closing this issue
