### ISSUE TITLE
Monitor if returned items follows expected field type

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#267]
With Spider monitoring in place (#248), we will be able to start monitoring if the items that we are returning matches a specific schema ([as it is explained here](https://spidermon.readthedocs.io/en/latest/item-validation.html#with-schematics)). This will avoid problems like https://github.com/okfn-brasil/querido-diario/pull/263/files .

Tasks needed:
- [ ] If #248 is not implemented yet, enable Spidermon into the project. If it is implemented, just need to do the next task;
- [ ] Add monitor that check if all returned fields matches a well defined schema

**Comment by andersonberg** [comment]
I can work on this issue. I can start creating the schema while https://github.com/okfn-brasil/querido-diario/issues/248 is not completed

**Comment by rennerocha** [comment]
Closed by https://github.com/okfn-brasil/querido-diario/pull/304 .
