### ISSUE TITLE
Onde estão os dados?

### ISSUE THREAD

**Issue by JoaoCarabetta** [okfn-brasil/querido-diario#279]
Tem um banco de dados que está sendo atualizado com o resultado dos crawlers?

**Comment by jvanz** [comment]
Por enquanto não. Estamos desenvolvendo um API que vai posibilitar encontrar os diarios. Mas por enquanto, não está no ar. Se você precisar de algum diario, é necessário rodar manualmente.

**Comment by renatopaivabv** [comment]
É possível que disponibilizem junto aos dados do Brasil.io?

**Comment by giuliocc** [comment]
> É possível que disponibilizem junto aos dados do Brasil.io?

Eu entendi essa pergunta como "se os dados coletados por esse projeto podem ser disponibilizados no Brasil.io". No momento não há planos para isso. Talvez num futuro onde o banco de dados estivesse bem consolidado e fosse do interesse dos dois projetos. Mas, o plano agora nesse sentido é disponibilizar a API e ir trabalhando para melhorar a qualidade da informação extraída.

**Comment by JoaoCarabetta** [comment]
Gente, estava pensando aqui, será que não tem como rodar os crawlers com o github actions? Aí ele podia salvar os dados em algum outro repositório que nem o pessoal do covid19br https://github.com/covid19br/eSUS-VE

**Comment by jvanz** [comment]
> Gente, estava pensando aqui, será que não tem como rodar os crawlers com o github actions? Aí ele podia salvar os dados em algum outro repositório que nem o pessoal do covid19br https://github.com/covid19br/eSUS-VE. O bom disso é que o custo é zero :)

Github actions tem um limite no tempo de execução para repositórios no plano gratuito. 

Estou fechando a issue. Acredito que a dúvida foi respondida. Caso contrário, nos avise. Reabra ou abra outra issue. Obrigado
