### ISSUE TITLE
GazetteDateFilteringPipeline

### ISSUE THREAD

**Issue by netoferraz** [okfn-brasil/querido-diario#285]
Hello, guys! My first interaction in the project. I have a question about the parameter `start_date`. If any spider who does not have `start_date `(datetime.date type) declared in your own code and someone put it through scrapy tool (-a start_date=2020-10-01, for instance), the interpreter will cast this parameter to string, right?

If I am not wrong, we'll raise a `TypeError` on `GazetteDateFilteringPipeline` because start_date is a string and date from Item is a date object.
```
class GazetteDateFilteringPipeline:
    def process_item(self, item, spider):
        if hasattr(spider, "start_date"):
            if spider.start_date > item.get("date"): 
                raise DropItem("Droping all items before {}".format(spider.start_date))
        return item
```

**Comment by rennerocha** [comment]
`start_date` will always be a `date` and no error will be raised if the spider inherits from `BaseGazetteSpider`. 

Even if the spider doesn't have it explicitly defined, we cast the string into a `date` on `BaseGazetteSpider` [init method](https://github.com/okfn-brasil/querido-diario/blob/main/processing/data_collection/gazette/spiders/base.py#L16) that guarantee that it will work correctly in the pipeline.

**Comment by netoferraz** [comment]
> `start_date` will always be a `date` and no error will be raised if the spider inherits from `BaseGazetteSpider`.
> 
> Even if the spider doesn't have it explicitly defined, we cast the string into a `date` on `BaseGazetteSpider` [init method](https://github.com/okfn-brasil/querido-diario/blob/main/processing/data_collection/gazette/spiders/base.py#L16) that guarantee that it will work correctly in the pipeline.

@rennerocha thank you for the explanation. I do not have any questions further. So, you can close this issue.
