### ISSUE TITLE
Add base spider for Diário Oficial Eletrônico dos Municípios

### ISSUE THREAD

**Issue by anapaulagomes** [okfn-brasil/querido-diario#300]
Different cities are under http://doem.org.br/ domain. We could benefit from it having a base spider for this source.

Examples (only from Bahia):

* Acajutiba BA
* Alagoinhas BA
* Cachoeira BA
* Campo Formoso BA
* Catu BA
* Ipiaú BA
* Itapetinga BA
* Juazeiro BA
* Mucuri BA
* Porto Seguro BA
* Ribeira do Pombal BA
* Santo Amaro BA
* Senhor do Bonfim BA
* São Gonçalo dos Campos BA
* Tucano BA

**Comment by rodbv** [comment]
Eu tô a fim de tentar resolver essa issue, se alguém mais estiver interessado me avisa, vamos trabalhar juntos :)

---

I'm planning to give this a shot, if anyone else is interested let me know, let's work together on it :)

**Comment by anapaulagomes** [comment]
What about you, @georgevbsantiago? ☝🏽

**Comment by georgevbsantiago** [comment]
Eu fiz um Scraping em Linguagem R para mapear os municípios com diário ativo nesta plataforma. Encontrei a lista abaixo. Já cadastrei alguns no Censo, mas ainda falta cadastrar outros.
Veja. Eu faço alguns Web Scrapings, mas não manjo de javascript. O que tento fazer é contornar o problema. No caso dos diários abaixo, ao analisar o código do javascript percebi que é possível alterar o URL dos botões para fazer o download do link do PDF.

Em linguagem R seria asssim:

`url <- "http://www.doem.org.br/ba/barrocas/diarios"

requisicao_html <- httr::GET(url)

scraping_html <- xml2::read_html(requisicao_html )

links_html <- scraping_html %>%
              rvest::html_nodes(".btn-default.pull-right") %>%
              rvest::html_attr("href")

links_diarios <- links_html %>%
                 stringr::str_replace("previsualizar", "baixar") %>%
                 stringr::str_replace("&_cb", "?_cb") %>%
                 stringr::str_replace("\\?filename=", "/")

nomes_diarios <- links_html %>%
                 stringr::str_extract("DOE.*.(pdf|PDF)")

data_publicacao_diarios <- scraping_html %>%
                   rvest::html_nodes(".data-diario") %>%
                   rvest::html_text(., trim = TRUE) %>%
                   lubridate::dmy()`

Só não sei ainda como seria m python :)

http://www.doem.org.br/ba/barrocas/diarios
http://www.doem.org.br/ba/canudos/diarios
http://www.doem.org.br/ba/banzae/diarios
http://www.doem.org.br/ba/acajutiba/diarios
http://www.doem.org.br/ba/alagoinhas/diarios
http://www.doem.org.br/ba/barradochoca/diarios
http://www.doem.org.br/ba/cacule/diarios
http://www.doem.org.br/ba/camamu/diarios
http://www.doem.org.br/ba/catolandia/diarios
http://www.doem.org.br/ba/cicerodantas/diarios
http://www.doem.org.br/ba/itapetinga/diarios
http://www.doem.org.br/ba/ituacu/diarios
http://www.doem.org.br/ba/juazeiro/diarios
http://www.doem.org.br/ba/mucuri/diarios
http://www.doem.org.br/ba/santacruzcabralia/diarios
http://www.doem.org.br/ba/senhordobonfim/diarios
http://www.doem.org.br/ba/tabocasdobrejovelho/diarios
http://www.doem.org.br/ba/alcobaca/diarios
http://www.doem.org.br/ba/antoniocardoso/diarios
http://www.doem.org.br/ba/cachoeira/diarios
http://www.doem.org.br/ba/catu/diarios
http://www.doem.org.br/ba/inhambupe/diarios
http://www.doem.org.br/ba/irara/diarios
http://www.doem.org.br/ba/laje/diarios
http://www.doem.org.br/ba/macajuba/diarios
http://www.doem.org.br/ba/mascote/diarios
http://www.doem.org.br/ba/medeirosneto/diarios
http://www.doem.org.br/ba/prado/diarios
http://www.doem.org.br/ba/ribeiradopombal/diarios
http://www.doem.org.br/ba/santoamaro/diarios
http://www.doem.org.br/ba/santoestevao/diarios
http://www.doem.org.br/ba/sentose/diarios
http://www.doem.org.br/ba/tucano/diarios
http://www.doem.org.br/ba/ipiau/diarios
http://www.doem.org.br/ba/teolandia/diarios
http://www.doem.org.br/ba/florestaazul/diarios
http://www.doem.org.br/ba/brotasdemacaubas/diarios
http://www.doem.org.br/ba/campoformoso/diarios

**Comment by anapaulagomes** [comment]
Arrasou, @georgevbsantiago! Se quiserem tentar, posso ajudar tirando alguma dúvida que surja.

**Comment by georgevbsantiago** [comment]
> Arrasou, @georgevbsantiago! Se quiserem tentar, posso ajudar tirando alguma dúvida que surja.

Pode fazer as honras. kkkkkkkk
Tô fazendo os meus Web Scrapings em R. Minha curva de aprendizado em Python ainda vai demorar um pouco. kkkkk

**Comment by georgevbsantiago** [comment]
ah, esqueci de comentar que já tô vendo um função para pegar o mês de início de forma automatizada. O site parece bem tranquilo de raspar.

**Comment by rodbv** [comment]
Boa! Nesse fim-de-semana devo dar uma olhada, vai ser muito legal se der pra trazer tanto município com uma caixa d'agua só 😆

**Comment by georgevbsantiago** [comment]
@rodbv , quando estava rodando o meu Web Scraping com R, encontrei alguma páginas que destoavam do padrão CCS proposto inicialmente (exemplos abaixo). O que fiz foi filtrar os links capturados para pegar somente os que tinham a string "diarios/previsualizar" no url. No meu caso, funcionou adequadamente. 

http://doem.org.br/ba/irece/diarios/2012/4
http://doem.org.br/ba/irece/diarios/2012/12
http://doem.org.br/ba/canudos/diarios/2015/1

Ex:
![image](https://user-images.githubusercontent.com/22058152/97806886-a9f5b600-1c3c-11eb-8564-4360511881ca.png)

**Comment by rodbv** [comment]
Boa @georgevbsantiago vou ajustar o código, valeu!

Tb estou procurando alguma edição marcada como "extra" para ver qual é o padrão.

Abs!

**Comment by rodbv** [comment]
@georgevbsantiago tava dando uma olhada no meu código e ele pega os links com o atributo `title` igual a "Baixar Publicação", o que parece funcionar também, os demais links tem `title` "Visulizar" (sim, com esse errinho de digitação).

Abs!

**Comment by georgevbsantiago** [comment]
> @georgevbsantiago tava dando uma olhada no meu código e ele pega os links com o atributo `title` igual a "Baixar Publicação", o que parece funcionar também, os demais links têm `title` "Visulizar" (sim, com esse errinho de digitação).
> 
> Abs!

Entendi. Você usou o xPath algo assim:
`//a[title="Baixar Publicação"]`

Eu tinha usado CSS. Por isso, tive que fazer a adequação.
