### ISSUE TITLE
Do we still need the master branch?

### ISSUE THREAD

**Issue by anapaulagomes** [okfn-brasil/querido-diario#309]
I'm only raising this question because I pull code from `master` instead of `main` by mistake. 😓

**Comment by rennerocha** [comment]
No, we don't ...

**Comment by anapaulagomes** [comment]
Thanks, @rennerocha! Could you delete it then? Or maybe @sergiomario... Much appreciated!

**Comment by sergiomario** [comment]
Done! Master branch was deleted
