### ISSUE TITLE
Add spider Sorocaba/SP

### ISSUE THREAD

**Issue by DanielMJoao** [okfn-brasil/querido-diario#314]
I'd like to work on Sorocaba/SP:
http://noticias.sorocaba.sp.gov.br/jornal/

**Comment by DanielMJoao** [comment]
What should I do if there's no day avaiable on the website (link nor text)?

For example, please follow the link bellow:
http://noticias.sorocaba.sp.gov.br/jornal/?ano=2020+Marco

The only way to know that the "Decreto 25663 2020 - Calamidade" is from day 21 is by clicking on it (inside the pdf itself). Should I return "None" as date on the gazette or should I assign it a specific day on that month (like 01/03/2020)?

**Comment by jvanz** [comment]
You have the dates in the HTML: 
![image](https://user-images.githubusercontent.com/1514798/97377763-84188c00-189f-11eb-8422-906dae40ae0a.png)

You need to parse the text from the HTML and extract the date from there.

**Comment by DanielMJoao** [comment]
Vou escrever em português para evitar mau entendimento.

A grande maioria dos diários é como você mencionou. Já fiz o script e parece funcionar, extraindo informações de onde você mostrou.

No entanto, minha pergunta foi **o que devo fazer com os arquivos em que o dia não está expresso**. Por exemplo, no link que postei, há um arquivo chamado "Decreto 25663 2020 - Calamidade". Veja como é nos moldes da imagem que você enviou:
![image](https://user-images.githubusercontent.com/42386804/97443437-c70f4980-1909-11eb-9a3e-cc35d364aacd.png)

Este decreto é do dia 21, e a única forma de saber isso é abrindo o arquivo.

Opções que imagino:
- Não adicionar como diário
- Adicionar como diário, retornando data "None" => parece dar erro
- Adicionar como diário, retornando uma data específica padrão (no caso, 01/03/2020, primeiro dia do mês)

Poderiam me ajudar com o tema? Obrigado.

**Comment by rennerocha** [comment]
@jvanz tem alguém na OKFN que possa dar um suporte sobre isso?

Na minha opinião, **Decreto** não é um **Diário Oficial** e sim outro tipo de publicação oficial que não está no escopo desse projeto. Então eu simplesmente ignoraria ele e retornaria apenas os Diários de verdade.

**Comment by jvanz** [comment]
> @jvanz tem alguém na OKFN que possa dar um suporte sobre isso?
> 
> Na minha opinião, **Decreto** não é um **Diário Oficial** e sim outro tipo de publicação oficial que não está no escopo desse projeto. Então eu simplesmente ignoraria ele e retornaria apenas os Diários de verdade.

Vou falar com o pessoal e aviso por aqui mais tarde.

**Comment by giuliocc** [comment]
O pessoal da OKFN falou que decreto municipal faz parte do conteúdo de diário oficial :/ Fui checar em alguns documentos de outras cidades e encontrei decretos também.

Nesse caso sugiro deixar a extração de data para a etapa de processamento e aqui a gente dar um jeito de deixar passar datas parciais ou vazias, como o @DanielMJoao  sugeriu.

Esse sistema tem um problema sério pra extração de datas pelo que estou vendo. O formato do título e das datas varia muito. Talvez um bom caminho seria usar o filtro pra fixar mês e ano e tentar extrair o dia. E caso não consiga, a gente teria que ter um jeito de passar as datas incompletas ou vazias.

@rennerocha @jvanz , o que acham?

**Comment by jvanz** [comment]
Sim, tbm conversei com eles e me falaram a mesma coisa. (Alias, obrigado por ir atrás disso tbm :) )

Nesse caso, não dá nem pra relacionar a outros diário da mesma página. Pq é um diário realmente separado.
