### ISSUE TITLE
Should we add instructions to create a virtual environment before running "make setup"?

### ISSUE THREAD

**Issue by rodbv** [okfn-brasil/querido-diario#320]
The instructions on README.md suggest to run `make setup` without a virtual environment, which will run `pip3 install` on the user's machine, not isolated in a virtual environment, and is prone to dependency conflicts etc.

We should leverage the benefits of virtual environments, and ask the user to create and activate one before they run `make setup`.

If this makes sense I'm glad to send this PR with instructions for Mac/Linux and Windows users.

**Comment by rennerocha** [comment]
@rodbv hopefully this was fixed after https://github.com/okfn-brasil/querido-diario/pull/323 were merged.
I will close this issue. Please open it again if you think we still need to change the documentation.
