### ISSUE TITLE
Add spider for Bento Gonçalves - RS

### ISSUE THREAD

**Issue by jobedylbas** [okfn-brasil/querido-diario#322]
Hi, 

According to the [CITIES.md](https://github.com/okfn-brasil/querido-diario/blob/main/CITIES.md) there is no crawler, issue or PR for Bento Gonçalves in RS.
I also searched opened, closed Issues and PRs on Github, but I didn't find nothing related to Bento Gonçalves.

The Official Gazette could be found here: [http://www.bentogoncalves.rs.gov.br/diario-oficial](http://www.bentogoncalves.rs.gov.br/diario-oficial)

If I'm incorrect and already exists a spider for Bento Gonçalves, please let me know.

Also, I would like to work in this issue.

**Comment by rodbv** [comment]
Hey @jobedylbas I don't think there's a spider for Bento Gonçalves, at least by looking at the spiders directory.

I'd say go for it! if you have any question I'm glad to help, although I'm also a newcomer here :) Cheers

**Comment by rodbv** [comment]
PR #329

**Comment by rennerocha** [comment]
Closing stale issue.
