### ISSUE TITLE
Review instructions for Windows users

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#342]
After https://github.com/okfn-brasil/querido-diario/pull/341 is merged, we don't rely on Docker to run the project, so it is very likely that the instructions to create development environment for Windows users (https://github.com/okfn-brasil/querido-diario/blob/main/windows_users.md) are not valid anymore.

We need to review these instructions and update them accordingly. Bonus point if we can have these instruction in English and Portuguese.

**Comment by hugohfsouza** [comment]
325 / 5000
Resultados de tradução
Hi

My name is Hugo Fumero. I am a student of the master's degree in computer science at the federal technological university of paraná.

I participate in the discipline of free software and would like to start contributing to this project. Can I start with this activity?

Do you have any communication channel (slack, whats, telegram etc)?

**Comment by hugohfsouza** [comment]
@rennerocha

**Comment by giuliocc** [comment]
Sure @hugohfsouza ! In the last sprint for this project we tried to make a tutorial for the installation instructions but couldn't find the time to convert it into a PR. If it helps, you could use it as a base for this task.

[Link for the tutorial](https://docs.google.com/document/d/1XIDNokbIpp9fqyvGokiPIrLSM3BIjDYqxxL4w8WapvQ/edit?usp=sharing).

Also, if you prefer to talk in Portuguese you are welcome to :)

**Comment by hugohfsouza** [comment]
Pode deixar então. Vou trabalhar nesta issue.

obrigado

**Comment by hugovelasco** [comment]
@hugohfsouza and I have talked to each other in private and we decided that I'll assume this task from now on.
Both of us are part of the same student group in UTFPR.
Thank you in advance!

**Comment by hugovelasco** [comment]
Hi @giuliocc!
I've turned this issue into a PR (https://github.com/okfn-brasil/querido-diario/pull/444).
Bye!
