### ISSUE TITLE
Araçatuba - SP spider

### ISSUE THREAD

**Issue by ddreyf** [okfn-brasil/querido-diario#352]
Workshop CODA Br - 
https://imprensaoficialmunicipal.com.br/aracatuba

**Comment by ddreyf** [comment]
Vamos Lá, 
Encarando o desafio de seguir os trilha para promover para Araçatuba, Plano de trabalho para os próximos 46 dias.

- Revisar a Oficina no CODA, 
- Infra da Maquina GitHub, conferir Pyton.. 
- Revisar Issues de outros diários do Estado de São Paulo, especialmente na Alta Noroeste Paulista.
- Identificar parceiros-colaboradores na cidade e região para compor a iniciativa colaborativa 
- Identificar linhas de colaboração nas Issues.
- Dedicar tempo diário para estudo das Linguagem que sustentam o trabalho

**Comment by ddreyf** [comment]
Prezado @jvanz, grato pelo add lá em 21/11/2020. 
Final de semestre foi uma loucura a parte na vida de professor-remoto, pouco andei com minha listinha acima.
Começo pelo agradecimento a tu!

**Comment by rennerocha** [comment]
Closing stale issue.
