### ISSUE TITLE
Create base spider for portaldatransparencia.com.br

### ISSUE THREAD

**Issue by rodbv** [okfn-brasil/querido-diario#353]
Several cities use portaldatransparencia.com.br to host their gazettes, e.g [BA/Varzea do Poço](http://ba.portaldatransparencia.com.br/prefeitura/varzeadopoco/).

It would be nice to create a base spider like FecamBaseSpider, so that it would be easy to create spiders for these cities by just inheriting the base spider, setting territory ID, url for the city and so on.

A list of all cities that use this platform can be found here: http://atmtec.org.br/#publicacao

Note that some cities only have old gazettes there, but some are still using it. If one  decides to also create a few spiders in the PR related to this issue, it's worth  checking which cities are actively using the platform.

**Comment by rodbv** [comment]
Criei um crawler para checar quais cidades nessa plataforma estão ativas: https://github.com/rodbv/portal-da-transparencia

A intenção é criar um "base spider" para depois poder usá-lo nas 26 cidades que deram positivo na checagem:

| territory_id      | state | city                      | url                                                                        |
|---------|-------|---------------------------|----------------------------------------------------------------------------|
| 2901403 | BA    | Angical                   | http://ba.portaldatransparencia.com.br/prefeitura/angical/                 |
| 3300225 | RJ    | Areal                     | http://rj.portaldatransparencia.com.br/prefeitura/areal/                   |
| 3506102 | SP    | Bebedouro                 | http://sp.portaldatransparencia.com.br/prefeitura/bebedouro/               |
| 2904209 | BA    | Botuporã                  | http://ba.portaldatransparencia.com.br/prefeitura/botupora/                |
| 3300704 | RJ    | Cabo Frio                 | http://rj.portaldatransparencia.com.br/prefeitura/cabofrio/                |
| 2907558 | BA    | Caturama                  | http://ba.portaldatransparencia.com.br/prefeitura/caturama/                |
| 3300951 | RJ    | Comendador Levy Gasparian | http://rj.portaldatransparencia.com.br/prefeitura/comendadorlevygasparian/ |
| 2908606 | BA    | Conde                     | http://ba.portaldatransparencia.com.br/prefeitura/conde/                   |
| 3514106 | SP    | Dois Córregos             | http://sp.portaldatransparencia.com.br/prefeitura/doiscorregos/            |
| 2913002 | BA    | Ibitiara                  | http://ba.portaldatransparencia.com.br/prefeitura/ibitiara/                |
| 2607307 | PE    | Ipubi                     | http://pe.portaldatransparencia.com.br/prefeitura/ipubi/                   |
| 2917359 | BA    | Jaborandi                 | http://ba.portaldatransparencia.com.br/prefeitura/jaborandi/               |
| 2923035 | BA    | Novo Horizonte            | http://ba.portaldatransparencia.com.br/prefeitura/novohorizonte/           |
| 2923605 | BA    | Paramirim                 | http://ba.portaldatransparencia.com.br/prefeitura/paramirim/               |
| 2924801 | BA    | Piritiba                  | http://ba.portaldatransparencia.com.br/prefeitura/piritiba/                |
| 4121505 | PR    | Rebouças                  | http://pr.portaldatransparencia.com.br/prefeitura/reboucas/                |
| 2926905 | BA    | Rio do Pires              | http://ba.portaldatransparencia.com.br/prefeitura/riodopires/              |
| 2928109 | BA    | Santa Maria da Vitória    | http://ba.portaldatransparencia.com.br/prefeitura/santamariadavitoria/     |
| 2928406 | BA    | Santa Rita de Cássia      | http://ba.portaldatransparencia.com.br/prefeitura/santaritadecassia/       |
| 3305406 | RJ    | Sapucaia                  | http://rj.portaldatransparencia.com.br/prefeitura/sapucaia/                |
| 1600709 | AP    | Tartarugalzinho           | http://ap.portaldatransparencia.com.br/prefeitura/tartarugalzinho/         |
| 2932804 | BA    | Utinga                    | http://ba.portaldatransparencia.com.br/prefeitura/utinga/                  |
| 2933059 | BA    | Várzea da Roça            | http://ba.portaldatransparencia.com.br/prefeitura/varzeadaroca/            |
| 2933109 | BA    | Várzea do Poço            | http://ba.portaldatransparencia.com.br/prefeitura/varzeadopoco/            |
| 2933455 | BA    | Wanderley                 | http://ba.portaldatransparencia.com.br/prefeitura/wanderley/               |
| 4314548 | RS    | Pinto Bandeira            | http://rs.portaldatransparencia.com.br/prefeitura/pintobandeira/           |

**Comment by trevineju** [comment]
A partir de https://github.com/okfn-brasil/querido-diario/issues/919, estamos automatizando o mapeamento de sistemas. Fecho esta issue, uma vez que os esforços estão concentrados lá.
