### ISSUE TITLE
Python.h: Arquivo ou diretório inexistente

### ISSUE THREAD

**Issue by adorilson** [okfn-brasil/querido-diario#361]
I've followed the commands to development environment and got the error below: 

```    
module.c:1:10: fatal error: Python.h: Arquivo ou diretório inexistente
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

To fix, I only installed python3-dev package with my distro manager package. 

How to add this instruction on README in a distro independent  way?

**Comment by giuliocc** [comment]
I think you could start a Troubleshooting section and mention this. I think that just referencing it as `python3-dev` is distro-independent enough to make a google search easier. Unless you want to give some examples (python3-dev, libpython3-dev, python3-devel, etc.).
