### ISSUE TITLE
Problem spider Assis/SP

### ISSUE THREAD

**Issue by luxu** [okfn-brasil/querido-diario#371]
Guys this site has the following problem: the diaries before 03/24/2017 only bring the link without publication date (as you can check the link: [diario-assis](https://www.assis.sp.gov.br/diario)) found in the PDF, the only way a friend of the community thought to get this date is by downloading the file and using metadata to get it, obviously it can't be done like this ... if you have any suggestions I'm open to listening. Thanks.

**Comment by tiagofer** [comment]
Olá Luxu! Não sei se é possível fazer isto diretamente no spider, mas eu fiz um teste aqui com o código abaixo e foi possível puxar a data de dentro do PDF. No código eu fiz um teste para o ano de 2016. Veja se isto ajuda.

```
import re
import urllib
import pdftotext
for i in range(139,280):
    urllib.request.urlretrieve(f'https://www.assis.sp.gov.br/diario_impresso/2016/2{i}.pdf','diario.pdf')
    with open('diario.pdf','rb') as f:
        gazette = pdftotext.PDF(f)
    print(re.search('\d* de [janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro]* de \d*',gazette[0]).group(0))
```

**Comment by luxu** [comment]
> Olá Luxu! Não sei se é possível fazer isto diretamente no spider, mas eu fiz um teste aqui com o código abaixo e foi possível puxar a data de dentro do PDF. No código eu fiz um teste para o ano de 2016. Veja se isto ajuda.
> 
> ```
> import re
> import urllib
> import pdftotext
> for i in range(139,280):
>     urllib.request.urlretrieve(f'https://www.assis.sp.gov.br/diario_impresso/2016/2{i}.pdf','diario.pdf')
>     with open('diario.pdf','rb') as f:
>         gazette = pdftotext.PDF(f)
>     print(re.search('\d* de [janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro]* de \d*',gazette[0]).group(0))
> ```

Essa lib **pdftotext** no windows não funciona...vlw msm assim!!

**Comment by tiagofer** [comment]
> > Olá Luxu! Não sei se é possível fazer isto diretamente no spider, mas eu fiz um teste aqui com o código abaixo e foi possível puxar a data de dentro do PDF. No código eu fiz um teste para o ano de 2016. Veja se isto ajuda.
> > ```
> > import re
> > import urllib
> > import pdftotext
> > for i in range(139,280):
> >     urllib.request.urlretrieve(f'https://www.assis.sp.gov.br/diario_impresso/2016/2{i}.pdf','diario.pdf')
> >     with open('diario.pdf','rb') as f:
> >         gazette = pdftotext.PDF(f)
> >     print(re.search('\d* de [janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro]* de \d*',gazette[0]).group(0))
> > ```
> 
> Essa lib **pdftotext** no windows não funciona...vlw msm assim!!

Poxa vida, não sabia. Até tinha visto na documentação dela a forma de rodar no Windows, porém não testei. A outra lib que avaliei foi a _pypdf2_, porém ela não reconhecia o trecho do PDF onde está a data do Diário, dai não dava pra pegar.

**Comment by giuliocc** [comment]
@luxu o problema encontrado aqui é similar ao reportado em #314. Acredito que a solução iria pelo mesmo caminho. Teríamos que ter uma maneira de deixar passar datas incompletas ou vazias aqui e deixar o projeto que irá cuidar do processamento dos documentos inferir essa data do texto (parecido com o que o @tiagofer fez)

**Comment by rennerocha** [comment]
Closing stale issue.
