### ISSUE TITLE
Add spider for São Paulo - SP

### ISSUE THREAD

**Issue by nfraprado** [okfn-brasil/querido-diario#380]
According to CITIES.md there still isn't any spider for São Paulo, so I'll work in adding it.

The gazette can be found at http://www.docidadesp.imprensaoficial.com.br/Busca.aspx (as already tracked by the [census](https://censo.ok.org.br/andamento/?region=sudeste&page=4)).

#7 was regarding an alternative information source that isn't the gazette, and as mentioned there, it isn't the focus right now, so I'm creating this issue to track the progress on the spider to retrieve the gazette for São Paulo.

**Comment by JTrevine** [comment]
A prefeitura de SP passou, neste ano, a publicar uma vitrine de APIs para vários 'serviços'. [Notícia](http://www.capital.sp.gov.br/noticia/vitrine-de-apis-disponibiliza-dados-do-diario-oficial-da-cidade-de-sao-paulo) | [Vitrine](https://apilib.prefeitura.sp.gov.br/store/vitrine) 
O [Diário Oficial](https://apilib.prefeitura.sp.gov.br/store/apis/info?name=Diario_Oficial&version=v1&provider=admin) é uma das novas APIs. 

Necessita melhor estudo da ferramenta, mas gostaria de deixar registrado no histórico aqui.
