### ISSUE TITLE
portugues

### ISSUE THREAD

**Issue by Ahava0803** [okfn-brasil/querido-diario#382]

**Comment by jvanz** [comment]
There is not relevant information in the issue. Closing it. Feel free to reopen it when you have more information. 

Não existe informações relevantes nessa issue. Vou fecha-la. Sinta-se a vontade para reabri-la com mais informações.

**Comment by Ahava0803** [comment]
Enviado do meu smartphone Samsung Galaxy.


-------- Mensagem original --------
De: José Guilherme Vanz <notifications@github.com>
Data: 21/11/20 19:57 (GMT-03:00)
Para: okfn-brasil/querido-diario <querido-diario@noreply.github.com>
Cc: Ahava0803 <pbvaldirsaldaterra@hotmail.com>, Author <author@noreply.github.com>
Assunto: Re: [okfn-brasil/querido-diario] portugues (#382)


There is not relevant information in the issue. Closing it. Feel free to reopen it when you have more information.

Não existe informações relevantes nessa issue. Vou fecha-la. Sinta-se a vontade para reabri-la com mais informações.
