### ISSUE TITLE
multiple-gazette sites / sites com vários diários

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#394]
Oi! A equipe das Embaixadoras/Censo dos Diários vem localizando alguns sites (de serviços de empresas, no geral) que oferecem muitos Diários ao mesmo tempo. Para fins de registro destes sites, mas também pensando que pode ser interessante priorizar seus raspadores (alguns já desenvolvidos, inclusive), foi sugerido criar uma issue para listar. Aqui está! (:

**Comment by JTrevine** [comment]
DiOE - Diário Oficial Eletrônico #298

**Comment by JTrevine** [comment]
DiOE - Diário Oficial Eletrônico

**Comment by JTrevine** [comment]
Fecam - Federação Catarinense de Municípios 

PR #135

**Comment by JTrevine** [comment]
Instar Internet 

PR #232

**Comment by JTrevine** [comment]
Associação Transparência Municipal 

PR #389

**Comment by JTrevine** [comment]
DOEM - Diário Oficial Eletrônico dos Municípios 

PR #383

**Comment by JTrevine** [comment]
SIGPub - Sistema Gerenciador de Publicações Legais 

PR #195

**Comment by JTrevine** [comment]
Portal da Transparência

PR #353

**Comment by JTrevine** [comment]
e-Atos - Publicações Municipais

https://publicacoesmunicipais.com.br/eatos/

**Comment by rennerocha** [comment]
Portal Fácil

https://www.portalfacil.com.br/portfolio

**Comment by bcbernardo** [comment]
Autopage Informática (IONEWS)

[https://autopage.inf.br/](https://autopage.inf.br/)

**Comment by bcbernardo** [comment]
DexaTec

http://dexatec.com/

**Comment by bcbernardo** [comment]
IPM Brasil

http://www.ipmbrasil.org.br/diario-oficial

**Comment by bcbernardo** [comment]
> 
> 
> e-Atos - Publicações Municipais
> 
> https://publicacoesmunicipais.com.br/eatos/

This also has an API documentation: https://publicacoesmunicipais.com.br:8443/docs/index.html

**Comment by valessiobrito** [comment]
www.acessoinformacao.com.br

**Comment by trevineju** [comment]
A partir de #919, estamos automatizando o mapeamento de sistemas. Fecho esta issue, uma vez que os esforços estão concentrados lá.
