### ISSUE TITLE
Prefeituras com DO Padrão - Estado da Bahia

### ISSUE THREAD

**Issue by georgevbsantiago** [okfn-brasil/querido-diario#401]
Olá, Pessoal

Resolvi criar essa issue, pois identifiquei várias prefeituras no Estado da Bahia que usam os serviços de algumas poucas empresas (IMAP, IBDM, IPM...). Acredito que essa issue (com os dados apresentados abaixo) possa contribuir no cadastramento do censo e na elaboração das spiders-modelo.

OBS: Caso essa issue não siga algum estrutura/padrão/nomenclatura... do projeto, os administradores podem solicitar ou promover as modificações que entenderem adequadas.

OBS2: Cada análise abaixo segue com um dataframe contendo variáveis (codigo_ibge; codigo_siafi; nm_municipio; url; tipo, data_do_antigo) que dão acesso ao diário oficial da respectiva Prefeitura. Estruturei os dados assim para iniciar um discussão e estratégia sobre a viabilidade/possibilidade de inserir esses dados diretamente no Banco de Dados do projeto. Das informações exigidas no censo, apenas não tenho a "Qual a data do arquivo mais antigo disponível online?" para todos os casos, mas pretendo fazer um complemento no script para obter essa informação. Já em relação a variável do formulário "Qual o formato dos arquivos?", daria para presumir a partir da análise amostral. Pelo que tenho visto, todos os casos poderiam ser enquadrados como "PDF imagem".

OBS3: Como só sei programar em Linguagem R, consegui fazer o levantamento dos dados de forma automatizada, mas não terei como ajudar na elaboração dos spiders-padrão (embora, acredito que já existam spiders prontos de algumas das prefeituras indicadas abaixo contemplando as empresas  (IMAP, IBDM, IPM...).

**IMAP:**
- Essa empresa talvez seja a maior prestadora de serviços de diários oficiais no Estado da Bahia. Até então, identifiquei que ela fornece **4 tipos de sites - com endereços diferente e estruturas html/css bem similares -**  (ver exemplos abaixo) para **197 prefeituras**. A mesma prefeitura pode ter o mesmo diário disponibilizado simultaneamente em mais de uma estrutura que a empresa fornece (ver exemplo abaixo).

- Link dos Dados: [df_imap_FULL.zip](https://github.com/okfn-brasil/querido-diario/files/5673748/df_imap_FULL.zip)

- Exemplo dos 4 tipos de sites fornecidos pela empresa:
TIPO 1: https://www.elisiomedrado.ba.gov.br/Site/DiarioOficial
TIPO 2: http://www.nordestina.ba.io.org.br/diarioOficial
TIPO 3: https://sai.io.org.br/ba/itacare/Site/DiarioOficial
TIPO 4: https://dom.imap.org.br/sitesMunicipios/imprensaOficial.cfm?varCodigo=679

- Exemplo de prefeitura que tem o mesmo diário disponibilizado simultaneamente em 3 tipos de sites da empresa:
https://dom.imap.org.br/sitesMunicipios/imprensaOficial.cfm?varCodigo=699
http://www.santoantoniodejesus.ba.io.org.br/diarioOficial
https://sai.io.org.br/ba/santoantoniodejesus/Site/DiarioOficial

- Análise: Ao realizar o mapeamento das prefeituras que divulgavam, em 2020, os seus diários com a IMAP, identifiquei que:
. O TIPO 4 abrange 197 prefeituras (fazendo um paralelo com a Teoria dos Conjuntos, seria o nosso universo);
. O TIPO 1 é um subconjunto com 126 prefeituras;
. O TIPO 2 é um subconjunto com 44 prefeituras;
. O TIPO 3 é um subconjunto com 59 prefeituras;
Obs: Como apontado acima, em regra, o mesmo diário oficial divulgado com o TIPO 4 pode ser divulgado simultaneamente em em outros TIPOS (1, 2 e 3).
__________________________________________________________________

**IBDM:**
- Até então, identifiquei que ela fornece **2 tipos de sites - com endereços diferente e estruturas html/css bem similares -**  (ver exemplos abaixo) para **47 prefeituras**. Aparentemente, o diário oficial só é divulgado em um único tipo de site.

- Link dos Dados: [df_ibdm_full.zip](https://github.com/okfn-brasil/querido-diario/files/5673846/df_ibdm_full.zip)

- Exemplo dos 2 tipos de sites fornecidos pela empresa:
TIPO 1: http://www.doem.org.br/ba/senhordobonfim/diarios
TIPO 2: http://www.doem.org.br/ba/itabuna/diarios

- Análise: Ao realizar o mapeamento das prefeituras que divulgavam, em 2020, os seus diários com a IBDM, identifiquei que:
. O TIPO 1 abrange 38 prefeituras;
. O TIPO 2 abrange 9 prefeituras;

#300  (Nesta issue, a @anapaulagomes tinha apontado, com dados do censo, que várias prefeituras da Bahia utilizavam o diário oficial da empresa IBDM. Além disso, o @rodbv criou um modelo de spider para os diários oficiais da IBDM).
__________________________________________________________________

**IPM:**
(Em levantamento)
__________________________________________________________________

**IMPRENSA OFICIAL** 
(Em levantamento)

__________________________________________________________________
Outras informações:
#394  (Nesta issue, já há um levantamento inicial de várias empresas que prestam serviços de diários oficial para várias municípios do Brasil).

**Comment by anapaulagomes** [comment]
Boa, @georgevbsantiago! No #354 eu adicionei spiders de cidades que usam o imprensaoficial.org. Pelo meu levantamento eram umas 30 e poucas mas que mantém atualizado mesmo são as do PR.

**Comment by trevineju** [comment]
A partir de #919, estamos automatizando o mapeamento de sistemas. Fecho esta issue, uma vez que os esforços estão concentrados lá.
