### ISSUE TITLE
Add spider for São Bernardo do Campo - SP

### ISSUE THREAD

**Issue by gsusin** [okfn-brasil/querido-diario#409]
According to CITIES.md there still isn't any spider for São Bernardo do Campo - SP, so I'll work in adding it.

The gazette can be found at https://www.saobernardo.sp.gov.br/web/sbc/todas-as-edicoes (as already tracked by the census). Their first data is from 2002-05-03 and they always use PDF.

**Comment by trevineju** [comment]
Fechando a issue por já existir uma para o mesmo município
