### ISSUE TITLE
Check why we are downloading exe files. 

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario#414]
I was taking a look in the text extractor running in our infrastructure and I noticed this:

```
Jan 28 00:00:15 staging.jarbas.serenata.ai podman[25570]: WARNING:root:Could process gazette: 2211001/2005-12-30/056d0e649a21965f6a5aea901cd1df50694d4700.exe. Cause: Unsupported file type: application/x-dosexec
Jan 28 00:00:17 staging.jarbas.serenata.ai podman[25570]: WARNING:root:Could process gazette: 2211001/2005-07-01/565753758b2f29c60c7a8a1c794dc9e00735f8f9.exe. Cause: Unsupported file type: application/x-dosexec
Jan 28 00:00:17 staging.jarbas.serenata.ai podman[25570]: WARNING:root:Could process gazette: 2211001/2005-01-28/a917d8afa0ead205794937add8c2c34d1ea89578.exe. Cause: Unsupported file type: application/x-dosexec
Jan 28 00:00:18 staging.jarbas.serenata.ai podman[25570]: WARNING:root:Could process gazette: 2211001/2005-04-01/e13d63832d0f8d30a4bc3311be701db8c5e83af2.exe. Cause: Unsupported file type: application/x-dosexec
Jan 28 00:00:18 staging.jarbas.serenata.ai podman[25570]: WARNING:root:Could process gazette: 2211001/2005-02-25/f79d4c2a9445439841b1e518ac3c41ee7fb7aea7.exe. Cause: Unsupported file type: application/x-dosexec
Jan 28 00:00:20 staging.jarbas.serenata.ai podman[25570]: WARNING:root:Could process gazette: 2211001/2005-02-11/be89dadc0ccbd004f5e810e688a9a72d5f5f0091.exe. Cause: Unsupported file type: application/x-dosexec
```

For some reason, the file scraped is a exe file. I would like to ask to double check if the [spider](https://github.com/okfn-brasil/querido-diario/blob/054e8e36701e798132ce3a06ac6916e947099849/data_collection/gazette/spiders/pi_teresina.py)(pi_teresina.py) is working 100%. I won't be surprise if the exe is really from the site as a gazette file. However, we should ensure if this is the case or not.

Take care if you download the files. The exe files could be malicious.

**Comment by athossampayo** [comment]
I checked Terezinha Gazette and found that the files are really there. You can check using this curl:
```
curl "http://dom.pmt.pi.gov.br/lista_diario.php" ^
  -H "Connection: keep-alive" ^
  -H "Cache-Control: max-age=0" ^
  -H "Upgrade-Insecure-Requests: 1" ^
  -H "Origin: http://dom.pmt.pi.gov.br" ^
  -H "Content-Type: application/x-www-form-urlencoded" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36" ^
  -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" ^
  -H "Referer: http://dom.pmt.pi.gov.br/lista_diario.php" ^
  -H "Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7" ^
  --data-raw "filtra_num=&filtra_data=11^%^2F02^%^2F2005&filtra_dataf=&filtra_descr=" ^
  --compressed ^
  --insecure
``` 

The response will have only one file indexed: [DOM1029-1-11022005](http://dom.pmt.pi.gov.br/admin/upload/DOM1029-1-11022005.exe) and it is a .exe file. I scanned it in VirusTotal and the result was that one engine flagged it as malware. Don't know if it is a false positive though. What should be done? Allow the spider to download it or filter .exe files?

**Comment by jaswdr** [comment]
@athossampayo I've tried the command you pasted and got normal HTML:

[output.txt](https://github.com/okfn-brasil/querido-diario/files/6074624/output.txt)

But looking at the website certificate there is something strange, it is registered for `www.example.com` and is a self-signed certificate. See the details [here](https://www.sslshopper.com/ssl-checker.html#hostname=https://dom.pmt.pi.gov.br/lista_diario.php)

What I suspect with this is that the website was hacked, the .exe was added and now the IT department is trying to fix this ASAP, but probably they didn't have much knowledge about how to setup a webserver.

What do you think @jvanz ?

**Comment by jvanz** [comment]
Yeah, this is weird to me as well. I was talking with the OKBR yesterday about that. We will notify the city about this asap. I will keep the issue updated

**Comment by jvanz** [comment]
I've just sent a message to the technical director of the company responsible for the gazettes website and open a ticket in Teresina's  ombudsman

**Comment by jaswdr** [comment]
@jvanz the website is back to normal, maybe makes sense to close this issue?
