### ISSUE TITLE
es_associacao_municipios might be refactorable to SC Fecam's template

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario#425]
Both systems are made by the same consortium.

The way that the [es_associacao_municipios spider](https://diariomunicipales.org.br/?r=site/page&view=entidades) and [fecam spiders](https://diariomunicipal.sc.gov.br/site/?r=site/page&view=entidades) are made available seems pretty much the same.

If refactorable, this would make it easier to know which territories in ES are covered.

**Comment by trevineju** [comment]
Fechando esta issue, pois não são mais iguais. Na página referenciada da associação de municípios de ES consta uma nota de migração e já temos um PR que integra o novo sistema #745
