### ISSUE TITLE
First Contribuition

### ISSUE THREAD

**Issue by HenriqueRicardoFigueira** [okfn-brasil/querido-diario#431]
hi, i would like to start contributing to the project. I saw that the issues with the label "good first issue" are apparently resolved, I noticed that the city of Duque de Caxias needs to be implemented. Can I start with it?

**Comment by rennerocha** [comment]
Hello @HenriqueRicardoFigueira , thanks for your interest in contributing with the project. 
We already have a PR for Duque de Caxias (https://github.com/okfn-brasil/querido-diario/pull/102). However, it looks like the original author will not continue the work and solve the issues other reviewers found.
You could use this PR as reference or create a new spider from scratch (if it makes sense). When done create a new PR, so we can review it.

**Comment by HenriqueRicardoFigueira** [comment]
Okay, I'm going to work on that. Thanks  @rennerocha.
