### ISSUE TITLE
Sincronizar issues e PRs abertos de adição de spider | Sync open issues and PRs of spider additions

### ISSUE THREAD

**Issue by hugohfsouza** [okfn-brasil/querido-diario#440]
Pessoal, boa noite. 

Notei que há uma falta de sincronia entre as Issues e PRs abertos que notificam a inserção ou a intenção de trabalhar em uma nova cidade. Em um outro PR(https://github.com/okfn-brasil/querido-diario/pull/432) foi sugerido uma ideia de deixar automático este processo. 

Gostaria de abrir uma discussão para sugestões e ideia de como deveria funcionar tal processo.

**Comment by giuliocc** [comment]
Sobre o problema dos PRs sem issues, acho que templates de PRs de adição de raspadores e issues de intenção de desenvolvimento de raspadores e uma github action pra adicionar uma issue, caso ela não exista, quando um PR for adicionado poderia resolver... eu acho. Os templates poderiam identificar sobre qual(is) cidade(s) o PR se refere.

Adicionar a tag correta de desenvolvimento de spider nos PRs e issues também seria interessante.

Se a gente tivesse essas padronizações, então o status "soon" do `CITIES.md` não seria mais necessário, eu acho. Bastaria linkar na documentação um filtro nas issues para saber as "intenções de trabalho" e um filtro nos PRs para saber as "spiders parcialmente implementadas".

Pensei nisso agora, se tiverem ideias melhores ou encontrarem cãibras mentais no raciocínio mandem ver. Esse é um problema muito relevante pra novas contribuidoras. Obrigado por levantar essa bola!

**Comment by giuliocc** [comment]
@thaioliva
