### ISSUE TITLE
Add Diadema scrapy (How to?)

### ISSUE THREAD

**Issue by danielbom** [okfn-brasil/querido-diario#459]
Bom tarde. Estou conhecendo o repositório, pois gostaria de poder contribuir para o projeto. Passei algum tempo olhando o código e alguns `pull requests` para tentar entender como poderia fazer isso. 

Li o README.md, rodei alguns exemplos na minha máquina (rj_niteroi, mg_betim, df_brasilia) para ver os resultados. Obtive alguns PDFs com um assunto muito distante da minha área. A partir de alguns `pull requests` percebi que era necessário encontrar informações sobre "ato do executivo" e "ato do legislativo".

O código em si parece simples. Acessei alguns dos `pull requests` que passei para ver pelo navegador. E comecei a me questionar como encontrar as URLs para fazer estas requisições. Observando o arquivo CITIES.md, rolei o mouse e encontrei a cidade de olinda que ainda é uma tarefa pendente, então pensei em começar por ela.

Fiz pesquisas do tipo "orgão oficial olinda" e encontrei o [site da cidade](https://www.cmdiadema.sp.gov.br). Comecei a investigar onde eu poderia encontrar os dados coletados pelo querido-diario, contudo não me pareceu tão simples. Por enquanto, acredito que essa seja o real desafio deste projeto. Observando os PRs fiquei curioso como algumas URLs para PDFs foram encontrados. Naveguei pelo site base de um PR e não encontrei uma forma achar aquelas URLs.

Resolvi escolher outra cidade. Escolhi Diadema. Fiz uma nova pesquisa no google com a mesma intenção anterior e encontrei o [site da cidade](https://www.cmdiadema.sp.gov.br). Vasculhei o site e encontrei um possível local com os dados exigidos pelo projeto em https://www.cmdiadema.sp.gov.br/index.php?exe=projetos_lidos&page=1. Queria confirmar com alguém sobre isto e caso esta não seja uma página válida, queria saber o que eu posso ainda não ter entendido (Dica/Conselho). Caso seja válida, abrirei um PR com o Spider desta cidade.

**Comment by anapaulagomes** [comment]
Oi, @danielbom! Escrevi um [texto](https://www.anapaulagomes.me/pt-br/2020/10/quero-tornar-di%C3%A1rios-oficiais-acess%C3%ADveis.-como-come%C3%A7ar/) sobre como encontrar esses links escondidos. Lá você encontra informações sobre como raspar o HTML e como verificar as requests que saíram do site.

No caso de Diadema, parece que a cidade usa o site Imprensa Oficial. Eu abri um [PR](https://github.com/okfn-brasil/querido-diario/pull/354) por lá com um spider base para cidades desse site. Já está perto de ser mergeado (certo @giuliocc? 😂) então você poderia dar uma olhada e testar com a cidade. O link que você compartilhou é de projetos da Câmara e não do DO.

No caso de Olinda parece que o site utilizado é esse [aqui](http://www.diariomunicipal.com.br/amupe/), que já é raspado por esse [spider](https://github.com/okfn-brasil/querido-diario/blob/ba6d24598e6c948b5559827c738433ba72c976f4/data_collection/gazette/spiders/pe_associacao_municipios.py). Sim, o CITIES.md precisa ser atualizado. Vou tentar dar uma força nisso!

Qualquer dúvida, manda pra gente.

**Comment by danielbom** [comment]
Muito obrigado pela resposta @anapaulagomes, seu texto me ajudou muito! Acredito que seria super interessante possuir algum arquivo ou seção no README.md com links como esse. Apesar das possíveis questões que isso pode gerar, seria de grande ajuda para quem está conhecendo o repositório pelo repositório. Alias, criei um PR #460 com um spider para Guaraçaí com questões muito importantes e gostaria muito de ouvir sua opinião sobre os pontos levantados.

**Comment by anapaulagomes** [comment]
Obrigada, @danielbom! Fico feliz que tenha sido útil. Fica a vontade pra abrir um PR pra gente. Vou dar uma olhada no seu PR.

**Comment by anapaulagomes** [comment]
@danielbom meu PR foi mergeado. Agora você pode tentar implementar o spider de Diadema de maneira bem simples! 😄

**Comment by danielbom** [comment]
Nice!
