### ISSUE TITLE
Como testar raspadores mas rápido? | How can we test spiders faster?

### ISSUE THREAD

**Issue by anapaulagomes** [okfn-brasil/querido-diario#463]
I'd like to create a script or at least a list of good practices to improve the process of reviewing spiders.
I found these tips from @giuliocc [in this comment](https://github.com/okfn-brasil/querido-diario/pull/443#pullrequestreview-656256682):

- `-o output.jsonlines`: Exports the output items to `data_collection/output.jsonlines` (useful to review if the items are being scraped as intended)
- `-s LOG_FILE=logs.txt`: Logs will be redirected to `data_collection/logs.txt` (useful to review if anything strange during the crawl occurred)
- `-s FILES_STORE=""`: Disables file downloading (useful to run the entire crawl and not fill your hard drive hehe)

I was thinking that maybe having a script to extract some metrics could be useful. Here the metrics I have in mind:

* Last edition date
* Average of gazettes by month/year
* Exceptions and validation errors

What else do you get?

![](https://media.giphy.com/media/l4Ho3Kc7aAo8hIlFe/giphy.gif)

**Comment by trevineju** [comment]
i'm closing this issue cause i restarted this conversation recently in other one, in portuguese.
