### ISSUE TITLE
Traduzir CONTRIBUTING | Translate CONTRIBUTING

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/querido-diario#496]
O CONTRIBUTING do repositório está em inglês, para manter a documentação do repositório bilíngue ele precisa ser traduzido pro português.

Encorajado por okfn-brasil/querido-diario-comunidade#4.

---

### English

The repo's CONTRIBUTING is in English and to keep the documentation bilingual it should be translated to Portuguese.

Encouraged by okfn-brasil/querido-diario-comunidade#4.

**Comment by thiago-paim** [comment]
Acredito que isto tenha sido feito no PR abaixo:
https://github.com/okfn-brasil/querido-diario/pull/495

Podemos fechar esta issue?
