### ISSUE TITLE
Referenciar CODE_OF_CONDUCT de querido-diario-comunidade | Refer to querido-diario-comunidade's CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/querido-diario#497]
O repositório [querido-diario-comunidade](https://github.com/okfn-brasil/querido-diario-comunidade/) contém o CODE_OF_CONDUCT que é o mesmo para todos os repositórios do QD (para não precisarmos manter o Código em vários repos distintos).

Nesse caso, aqui nesse repo precisamos apenas referenciar num arquivo `CODE_OF_CONDUCT.md` o CODE_OF_CONDUCT do querido-diario-comunidade.

Isso pode ser feito tanto em inglês quando em português quando essa issue okfn-brasil/querido-diario-comunidade#3 estiver pronta :)

Encorajado por okfn-brasil/querido-diario-comunidade#4.

---

### English

The repo [querido-diario-comunidade](https://github.com/okfn-brasil/querido-diario-comunidade/) contains the CODE_OF_CONDUCT which is the same for every repo of QD (so we don't need to maintain the Code in many distinct repos).

In this case, in this repo we only need to reference it in a file `CODE_OF_CONDUCT.md` the CODE_OF_CONDUCT in querido-diario-comunidade.

This can be done in English as well as in Portuguese when this issue okfn-brasil/querido-diario-comunidade#3 is ready :)

Encouraged by okfn-brasil/querido-diario-comunidade#4.

**Comment by trevineju** [comment]
PR que resolve esta issue: #605
