### ISSUE TITLE
Vincular metas do repositório no guia de contribuição | Link repo's milestones in the contribution guide

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario#499]
As [metas do repositório](https://github.com/okfn-brasil/querido-diario/milestones) ficam meio escondidas na interface do Github e poderíamos apresentar o link para elas no guia de contribuição.

---

### English

The [project's milestones](https://github.com/okfn-brasil/querido-diario/milestones) are a bit hidden in Github's interface and we could present the link to them in the contribution's guide.

**Comment by BrenoFariasdaSilva** [comment]
Olá.
Tenho interesse em realizar esta issue. Poderia atribuí-la a mim, por favor?

**Comment by BrenoFariasdaSilva** [comment]
Eu criei um Pull Request que visa resolver esta issue. O PR é o de número #1080. Por favor, deem uma olhada quando possível. Obrigado!
