### ISSUE TITLE
Add spider for Jaboatão dos Guararapes - PE

### ISSUE THREAD

**Issue by tcurvelo** [okfn-brasil/querido-diario#516]
Jaboatão dos Guararapes - PE is a city with a 600K+ population (https://cidades.ibge.gov.br/brasil/pe/jaboatao-dos-guararapes/panorama)

Official Gazette can be found here: https://diariooficial.jaboatao.pe.gov.br/

**Comment by giuliocc** [comment]
### Português

Fechado por #227 .

### English

Closed by #227 .
