### ISSUE TITLE
Adicionar instruções sobre `end_date`

### ISSUE THREAD

**Issue by anapaulagomes** [okfn-brasil/querido-diario#528]
Nem todos os spiders tem um valor para esse atributo mas, já que queremos tornar algo obrigatório, deveríamos adicionar na documentação.

**Comment by rennerocha** [comment]
Informação sobre `end_date` adicionada na documentação do projeto:
https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#filtro-por-data
