### ISSUE TITLE
Código de cidades duplicados | Duplicate cities IDs

### ISSUE THREAD

**Issue by lguima** [okfn-brasil/querido-diario#542]
Os códigos das últimas cidades estão duplicados:

![Screenshot from 2022-03-18 15-39-19](https://user-images.githubusercontent.com/1562097/159064422-e974eec2-7308-4a34-b080-76ee5154d24c.png)

**Esse dado é apenas visualização aqui no repositório ou é usado em algum outro lugar que alterando podeia ter impacto?**

_Referências_
- [CITIES.md](https://github.com/okfn-brasil/querido-diario/blob/main/CITIES.md)
- https://github.com/okfn-brasil/querido-diario/commit/090ba3bcbdae8db14e333149195428776d71d318#diff-d01568f6003704abfd13aab1c395cbf432f6d44433305ce3216bdff1f2ae42e9R2342

---

**English**

The IDs of the last cities are duplicated:

![Screenshot from 2022-03-18 15-39-19](https://user-images.githubusercontent.com/1562097/159064422-e974eec2-7308-4a34-b080-76ee5154d24c.png)

**Is this data just visualization here in the repository or is it used somewhere else that changing it could have an impact?**

_References_
- [CITIES.md](https://github.com/okfn-brasil/querido-diario/blob/main/CITIES.md)
- https://github.com/okfn-brasil/querido-diario/commit/090ba3bcbdae8db14e333149195428776d71d318#diff-d01568f6003704abfd13aab1c395cbf432f6d44433305ce3216bdff1f2ae42e9R2342

**Comment by giuliocc** [comment]
### Português

@lguima esse ID não é usado. Os IDs até o 100 indicavam a posição no ranking populacional e após isso foi assumindo a ordem de inserção no projeto. Penso que precisamos migrar esse `CITIES.md` para uma solução mais no estilo de #426 . 

Por mim, podemos fechar a issue, o que acha?

### English

@lguima this ID is not used. The IDs until 100 signify the position of the city in the populational ranking and after that it became the project's insertion order of scrapable cities. I think we should migrate this `CITIES.md` to a solution like #426 .

In my opinion we cloud close this issue, what do you think?

**Comment by lguima** [comment]
Ah, beleza então!

---

**English**

Got it, alright then!
