### ISSUE TITLE
Diário de João Pessoa (PB) quebra com páginas intermediárias para baixar o documento | João Pessoa's (PB) gazette website breaks with intermediate pages to download the document

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario#545]
### Português

No dia 22/03/22 o documento na [lista de publicações](http://antigo.joaopessoa.pb.gov.br/semanariooficial/) da cidade não é diretamente acessível, mas passa por uma página intermediária. Isso faz com que o documento real não seja extraído mas sim o HTML da página intermediária.

### English

In 22/03/22 the document in the cities' [gazette publications list](http://antigo.joaopessoa.pb.gov.br/semanariooficial/) is not directly accessible but instead has an intermediate page. That makes the real document not to be extracted but the intermediate page HTML instead.

**Comment by valeriow** [comment]
Estou vendo. Na verdade, parece que esse spider não está respeitando corretamente os parâmetros de data de início e fim. Vou aproveitar para corrigir isso também.

**Comment by valeriow** [comment]
Essa demanda não faz sentido no atual spider porque ele mudou em 28/04/22 no  commit  62c25adc8020ad3840f586606b879d150b3648b1
"Update João Pessoa-PB spider after website changed
[João Pessoa](https://www.joaopessoa.pb.gov.br/noticias/prefeitura-de-joao-pessoa-vai-implantar-diario-oficial-eletronico/) changed the system that displays the gazettes. So we need to rewrite the spider to get all gazettes after 28/03/2022."

**Comment by valeriow** [comment]
Aberto PR #893
