### ISSUE TITLE
Add Bom Jardim de Minas - MG in Spyder

### ISSUE THREAD

**Issue by alexandreandrade1** [okfn-brasil/querido-diario#565]
Hello,

According to CITIES.md there is no spider for Bom Jardim de Minas - MG.

The Official Diary can be found on https://www.bomjardimdeminas.mg.gov.br/diariobj/

I'm working on that.

**Comment by rennerocha** [comment]
If you are still working on this issue, when it is done, you can just create a PR for the code. No need for a specific issue for the city.
