### ISSUE TITLE
Fix Araguaina-TO spider after layout change

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#572]
Code of [Araguaina-TO](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/to_araguaina.py) is not collecting any spider. Current version is accessing `Busca Avançada` that allows us to search text content, however it doesn't allow us to simply search by date without providing a search string.

We have `Busca por Data` link that make it possible to search by date only. Spider code needs to use that link.

Logs of last production job (with the failure):
[log_to_araguaina_94.txt](https://github.com/okfn-brasil/querido-diario/files/8984953/log_to_araguaina_94.txt)

**Comment by rafaelhfreitas** [comment]
I'll check this issue.

**Comment by rafaelhfreitas** [comment]
I updated my repositorie and executed the spyder on my local machine.
![image](https://user-images.githubusercontent.com/21064382/189383922-b88cb84c-376f-4af2-957b-a85a3079a757.png)


The execution log present one error in test  "Comparison Between Executions/Days without gazettes", but i think is possible a city doesn't have a gazette in last 5 days ? 
 
Checking production logs, the error is a url had response 503.
@rennerocha can i create a function to check error, like e.g mg_uberlandia ? to check code 503 ? 
With incremental gazettes, in this case, we'll never get this gazette again if the page return answer 200 ? 

`https://diariooficial.araguaina.to.gov.br/Pesquisa/?De=24/06/2022&Ate=25/06/2022`

Today, this page is answering.
![image](https://user-images.githubusercontent.com/21064382/189383184-48e3ae9f-efaa-4db6-9330-eeee52209bda.png)

**Comment by trevineju** [comment]
Após ajustes, o raspador está funcionando
