### ISSUE TITLE
Teresina-PI is not collecting gazettes

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#573]
Teresina-PI is not collecting gazettes for weeks.

"It works in my machine" :rofl: so one guess is that they are blocking access of our spider that is running in Scrapy Cloud datacenters (located in Germany). It would be good to confirm if this is the case.

[log_pi_teresina_543.txt](https://github.com/okfn-brasil/querido-diario/files/8984963/log_pi_teresina_543.txt)

**Comment by begnini** [comment]
Tested with `wget` command in 3 different datacenters:

- Hetzner - Germany - connection refused
- Digital Ocean - USA - connection refused
- Amazon - Brazil - connected

**Comment by trevineju** [comment]
Já resolvido pelo be7d00ed5526f8111090fbb105aad4ff50aef53e
