### ISSUE TITLE
Certificado SSL

### ISSUE THREAD

**Issue by lcsvillela** [okfn-brasil/querido-diario#604]
Boa noite pessoal, tudo bem?

Alguns sites se comunicam diretamente com uma API externa para pegar os dados que serão exibidos na página, nessa situação pode ocorrer que quem desenvolveu o sistema restrinja a requisição apenas a que utilizam o certificado específico. Para contornar isso, podemos instalar a lib do openssl e pegar do front o SSL para depois fazer as requisições.

Como faz para instalarmos o openssl no projeto? Basta commitar com ele já importado?

**Comment by rennerocha** [comment]
Qual cidade está exigindo isso? Nunca vi essa necessidade antes.

**Comment by lcsvillela** [comment]
Cidade de hortolândia

É um caso semelhante a este: https://lcsvillela.com/extraindo-dados-vacinacao-maranhao.html

**Comment by rennerocha** [comment]
Eu fiz um teste utilizando `scrapy shell` com as URLs da cidade de Hortolândia-SP. Não houve nenhum erro de SSL ao se conectar com o site e baixar os arquivos PDF.

Testei com `requests` e o problema de verificação de certificado (CERTIFICATE_VERIFY_FAILED) aconteceu. Isso pode ser resolvido apenas adicionando uma flag no `requests.get` para não verificar a validade do certificado (`requests.get(url, verify=False)`) - https://requests.readthedocs.io/en/latest/user/advanced/?highlight=verify#ssl-cert-verification

O Scrapy já deixa de fazer essa verificação automaticamente, então esse problema não ocorre. Caso ocorra em outro cenário, o ideal é criar um spider da cidade com problema, abrir um PR e aí discutimos as possíveis soluções nesse PR.
