### ISSUE TITLE
Revisão do readme.md

### ISSUE THREAD

**Issue by silotto** [okfn-brasil/querido-diario#608]
## Problema de revisão de documentação - readme.md:

Tendo contrastado as informações apresentadas no repositório oficial com os campos solicitados no modelo de [readme.md](https://github.com/EL-BID/Temptilla-de-repositorio/blob/master/README.md) encontraram os seguintes pontos para melhorar:

- [ ] Adicione o logotipo para identificar o projeto.
- [ ] Adicione uma imagem ou gif do projeto para identificar sua principal funcionalidade.
- [ ] Incluir badges com o estado de desenvolvimento, licença, versão, cobertura, social ou outros. Esta ferramenta pode ser útil: https://shields.io/ (tutorial recomendado: https://www.youtube.com/watch?v=SIh5MQoQLPs)
- [ ] Forneça uma tabela com links para cada seção para funcionar como um índice.
- [ ] Especifique os pré-requisitos necessários para executar o projeto (ambiente, bibliotecas, dependências, entre outros), e forneça comandos de instalação para eles.
- [ ] Especifique se as variáveis de ambiente são necessárias e em qual parte da arquitetura elas são colocadas.
- [ ] Adicione uma lista de etapas que permitam a instalação e utilização do projeto localmente.
- [ ] Adicione o comando de execução para testes de unidade.
- [ ] Mencione as tecnologias utilizadas e adicione links referentes à documentação de cada uma.
- [ ] Se necessário, adicione trechos de código com exemplos de uso.
- [ ] Adicionar seção de autores.
- [ ] Adicione uma seção com o processo detalhado para contribuir com o projeto.
- [ ] Adicione uma seção especificando a licença de código aberto que está sendo usada redirecionando para o arquivo LICENSE.md.

**Comment by rennerocha** [comment]
Obrigado pelas sugestões. A documentação do projeto está sendo migrada aos poucos para https://github.com/okfn-brasil/querido-diario-comunidade e publicadas em https://docs.queridodiario.ok.org.br/pt/latest/ e algumas das sugestões já estão sendo implementadas lá.

**Comment by giuliocc** [comment]
@silotto estamos revisando toda nossa documentação dos repositórios do Querido Diário este mês, nos preparando para a Hacktoberfest \o/

Gostaria de convidar você e/ou qualquer pessoa do @EL-BID a revisitar o projeto no início de outubro para checar as mudanças pois a maioria dos pontos abordados já estavam em nossa linha de alterações a serem realizadas, como o Renne comentou.

Agradecemos muito o apoio do BID ao projeto e iniciativas como essa de incentivar os projetos apoiados a seguirem bons padrões de projeto de código aberto.
