### ISSUE TITLE
Belém-PA

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#613]
Necessita verificar se spider existente continua funcionando.

**Comment by gbonesso** [comment]
Rodei o raspador, está funcionando. Para testar rodei sem filtro para data e o resultado foi:

> 2022-09-30 15:28:05 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
> {'downloader/request_bytes': 913995,
>  'downloader/request_count': 4191,
>  'downloader/request_method_count/GET': 4191,
>  'downloader/response_bytes': 3834162184,
>  'downloader/response_count': 4191,
>  **'downloader/response_status_count/200': 4185**,
>  'downloader/response_status_count/406': 6,
>  'elapsed_time_seconds': 1246.912202,
>  'file_count': 4183,
>  'file_status_count/downloaded': 4183,
>  'finish_reason': 'finished',
>  'finish_time': datetime.datetime(2022, 9, 30, 18, 28, 5, 680793),
>  'item_dropped_count': 6,
>  'item_dropped_reasons_count/DropItem': 6,
>  'item_scraped_count': 4183,
>  'log_count/DEBUG': 12558,
>  'log_count/ERROR': 1,
>  'log_count/INFO': 55,
>  'log_count/WARNING': 27,
>  'memusage/max': 157442048,
>  'memusage/startup': 91344896,
>  'request_depth_max': 1,
>  'response_received_count': 4191,
>  'scheduler/dequeued': 2,
>  'scheduler/dequeued/memory': 2,
>  'scheduler/enqueued': 2,
>  'scheduler/enqueued/memory': 2,
>  'spidermon/validation/fields': 33512,
>  'spidermon/validation/fields/errors': 6,
>  'spidermon/validation/fields/errors/field_too_short': 6,
>  'spidermon/validation/fields/errors/field_too_short/files': 6,
>  'spidermon/validation/items': 4189,
>  'spidermon/validation/items/dropped': 6,
>  'spidermon/validation/items/errors': 6,
>  'spidermon/validation/validators': 1,
>  'spidermon/validation/validators/item/jsonschema': True,
>  'start_time': datetime.datetime(2022, 9, 30, 18, 7, 18, 768591)}


Bate com a contagem de arquivos no diretório:

> (.venv) BarbaMacMini@Mac-mini-de-Gustavo data_collection % find data -type f | wc -l
>     **4185**

O diário mais antigo era de 01/02/2005

**Comment by giuliocc** [comment]
Como a execução completa está funcionando e em produção não tem apresentado problemas. Estou fechando a issue. Obrigado @gbonesso !
