### ISSUE TITLE
Campinas-SP

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#614]
Desenvolver um novo spider para substituir o existente que não está mais funcionando atualmente.
Diários Oficiais podem ser localizados em:
https://portal.campinas.sp.gov.br/diario-oficial

**Comment by bbertolani** [comment]
Fui da uma fuçada achei esse request. 
https://portal-api.campinas.sp.gov.br/api/v1/publicacoes-dom/all/200301?_format=json
https://portal-api.campinas.sp.gov.br/api/v1/publicacoes-dom/all/{YEAR}{MONTH}?_format=json

`[
{
"dom_id": "8020",
"dom_edicao": "8116",
"dom_data_pub": "31/01/2003",
"dom_data_pub_semana": "sexta-feira",
"dom_data_pub_completa": "31/01/2003 - sexta-feira",
"dom_arquivo": "/sites/default/files/publicacoes-dom/dom/320601713.pdf",
"dom_extra_arquivo": ""
},
{...`

https://portal-api.campinas.sp.gov.br/sites/default/files/publicacoes-dom/dom/320601713.pdf

**Comment by danielfireman** [comment]
Muito bacana, @bbertolani ! 

@rennerocha posso realizar a modificação no código do spider?

**Comment by giuliocc** [comment]
@danielfireman à vontade!
