### ISSUE TITLE
Osasco-SP

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#622]
PR existente: https://github.com/okfn-brasil/querido-diario/pull/522
Código do PR existente funciona, porém não possui filtro de datas (start_date e end_date) para reduzir a quantidade de requests e extrair apenas os períodos solicitados.

**Comment by valeriow** [comment]
> PR existente: #522 Código do PR existente funciona, porém não possui filtro de datas (start_date e end_date) para reduzir a quantidade de requests e extrair apenas os períodos solicitados.

Testei o código do PR #522 e está funcionando corretamente e filtrando pelas datas. Existe outro problema além do mencionado?

**Comment by valeriow** [comment]
Aberto PR #890.
