### ISSUE TITLE
Serra-ES

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#628]
Diários Oficiais disponíveis em:
https://ioes.dio.es.gov.br/diariodaserra

**Comment by ayharano** [comment]
Olá.

Só para avisar que tem um PR funcional e aproveitar a pergunta que fiz lá e trazer para cá:

a partir de quantas cidades que usam um mesmo spider base seria bom refatorar e usar a estratégia descrita no README?
