### ISSUE TITLE
Porto Velho-RO

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#632]
Spider existente funciona, porém não possui filtro de datas (start_date e end_date) para reduzir a quantidade de requests e extrair apenas os períodos solicitados.

**Comment by gbonesso** [comment]
Pelo que pude pesquisar o site da prefeitura de Porto Velho (https://transparencia.portovelho.ro.gov.br/DOM) o spider implementado só funciona até 12/07/2018. Após isso Porto Velho aderiu a uma associação de municípios que publicam os dados conjuntamente ([veja aqui...](https://www.diariomunicipal.com.br/arom/pesquisar?busca_avancada%5B__paper%5D=1&busca_avancada%5BentidadeUsuaria%5D=24707&busca_avancada%5Bnome_orgao%5D=&busca_avancada%5Btitulo%5D=&busca_avancada%5Btexto%5D=&busca_avancada%5BdataInicio%5D=01%2F07%2F2018&busca_avancada%5BdataFim%5D=20%2F09%2F2022&g-recaptcha-response=03AIIukzjkxOAod0MRb9RnMvuu8W0k9JBSOfaZ7orQ7VMqqATiQEZNx0q3LCwGIdQNAv-WiD0custcmLTZTbFbIOzSrQbK0S9rpyIlqUPN1eA51TmzpYhW7Oj5k43pTntYQ4H6gJsiqFfq5vcFttu-f_CkkoUkyTy7OEnQM-U4wJc9kRgYRoi_LC8jRpFd6pCojObjx1B65LJWDyTvPtp5D9zHft0ZKDXoSfOjFzOnXeZVa3mIupS9XFqpmoQVcmFnA0-0XlmkJpBzYEEXiY094ad5QGaA1WbrQT52XGg_CjmSBqUM0wzQMeIIxs6zt_joQzXNRg3FhdR_hLs6UsPtCM8IfAwefCcHeN3Fjz9rXZ1w9YvJM3DgAECPt6Mw6Y1W1TkP3wzguLsWkgaHkqShJ-w99VmRp-vRiQzAxQsvgnQTXa7ssqvVpy41MZABBDTQDH3ST5eb6Qtu4f3aaUpFPh3G8SjTaWDOPiSezS_3Fzn9cRb_OmFqMaamhyprbv5XRt_Nsqz5Moom2uiHX4E8UxuGLDi_FqlRVQg3r9wXFtqetz6WYqe_d5Y&busca_avancada%5B_token%5D=GvoTI2tz_OidtvA9ejYeE0LzNkaScHXpcB8EkTEfF_o#))

**Comment by victorleal** [comment]
> Pelo que pude pesquisar o site da prefeitura de Porto Velho (https://transparencia.portovelho.ro.gov.br/DOM) o spider implementado só funciona até 12/07/2018. Após isso Porto Velho aderiu a uma associação de municípios que publicam os dados conjuntamente ([veja aqui...](https://www.diariomunicipal.com.br/arom/pesquisar?busca_avancada%5B__paper%5D=1&busca_avancada%5BentidadeUsuaria%5D=24707&busca_avancada%5Bnome_orgao%5D=&busca_avancada%5Btitulo%5D=&busca_avancada%5Btexto%5D=&busca_avancada%5BdataInicio%5D=01%2F07%2F2018&busca_avancada%5BdataFim%5D=20%2F09%2F2022&g-recaptcha-response=03AIIukzjkxOAod0MRb9RnMvuu8W0k9JBSOfaZ7orQ7VMqqATiQEZNx0q3LCwGIdQNAv-WiD0custcmLTZTbFbIOzSrQbK0S9rpyIlqUPN1eA51TmzpYhW7Oj5k43pTntYQ4H6gJsiqFfq5vcFttu-f_CkkoUkyTy7OEnQM-U4wJc9kRgYRoi_LC8jRpFd6pCojObjx1B65LJWDyTvPtp5D9zHft0ZKDXoSfOjFzOnXeZVa3mIupS9XFqpmoQVcmFnA0-0XlmkJpBzYEEXiY094ad5QGaA1WbrQT52XGg_CjmSBqUM0wzQMeIIxs6zt_joQzXNRg3FhdR_hLs6UsPtCM8IfAwefCcHeN3Fjz9rXZ1w9YvJM3DgAECPt6Mw6Y1W1TkP3wzguLsWkgaHkqShJ-w99VmRp-vRiQzAxQsvgnQTXa7ssqvVpy41MZABBDTQDH3ST5eb6Qtu4f3aaUpFPh3G8SjTaWDOPiSezS_3Fzn9cRb_OmFqMaamhyprbv5XRt_Nsqz5Moom2uiHX4E8UxuGLDi_FqlRVQg3r9wXFtqetz6WYqe_d5Y&busca_avancada%5B_token%5D=GvoTI2tz_OidtvA9ejYeE0LzNkaScHXpcB8EkTEfF_o#))

Fui verificar e já existe um script para coletar informações da associação de municípios de Rondônia [aqui](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/ro_associacao_municipios.py), o que deve contemplar esse problema.

**Comment by trevineju** [comment]
Conforme comentado, Porto Velho publica em diário agregado sendo, por enquanto, incompatível
