### ISSUE TITLE
Caxias do Sul-RS

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#634]
Spider existente funciona, porém não possui filtro de datas (start_date e end_date) para reduzir a quantidade de requests e extrair apenas os períodos solicitados.

**Comment by gbonesso** [comment]
Implementei o filtro de data e corrigi o download de PDF, nos meus testes não estava funcionando. PR https://github.com/okfn-brasil/querido-diario/pull/651
