### ISSUE TITLE
Tratamento para diários extraordinários

### ISSUE THREAD

**Issue by ayharano** [okfn-brasil/querido-diario#656]
Enquanto eu estava vendo os spiders com issues abertas, vi que tem alguns exemplares de diários que não são o padrão para a data estabelecida.

Exemplos:

- `sp_sorocaba`

<img width="924" alt="Screen Shot 2022-09-30 at 17 56 59" src="https://user-images.githubusercontent.com/13336/193354954-e02e3f4d-34ed-410f-81d3-a55bb959ad85.png">

- `rj_duque_de_caxias` [[URL específica](http://duquedecaxias.rj.gov.br/portal/2017.html)]

<img width="1030" alt="Screen Shot 2022-09-30 at 18 06 26" src="https://user-images.githubusercontent.com/13336/193356199-0ab1e9b2-feb6-4b4a-8356-30ecff78415f.png">

Procurei no material textual do próprio repositório bem como de issues abertas e não encontrei nenhuma orientação a respeito.

Tem algum posicionamento a respeito no sentido de:

1. coleta todos os diários possíveis
2. coleta somente os diários regulares de cada data
3. alguma outra opção

?

Uma questão derivada: qual é a melhor forma para relatar esses pontos de dúvida? Via GitHub seja [Issues](https://github.com/okfn-brasil/querido-diario/issues), seja [Discussions](https://github.com/okfn-brasil/querido-diario/discussions); via Discord da OKFN-BR; ou algum outro meio?

**Comment by trevineju** [comment]
No momento, @ayharano o discord é a melhor sugestão se você achar que a questão de bloqueia demais de fazer sua contribuição. Parte dos acúmulos sobre o projeto estão mais avançados que nossos registros aqui no GitHub (como você mesmo interagiu no PR de atualização do README, estamos trabalhando nisso). Lá você terá uma resposta mais rápida.

**Comment by trevineju** [comment]
Oi! Então... Adotamos a (1) coleta todos os diários possíveis. 
Você achou o caso de edição regular ou extraordinária, mas tem casos também que o diário é executivo e legislativo junto, por exemplo.
Para ambos os casos (se é edição normal ou extra, se do poder executivo ou legislativo) tem campo pra você indicar eles. 

Temos uma docs que apresenta questões desse tipo: https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos
