### ISSUE TITLE
Poor site of Duque de Caxias - RJ

### ISSUE THREAD

**Issue by AlvaroLQueiroz** [okfn-brasil/querido-diario#66]
The site has two format of links and file name for the gazettes.
1. http://duquedecaxias.rj.gov.br/portal/boletim-oficial/2015/01-Janeiro/
2. http://duquedecaxias.rj.gov.br/portal/arquivos/2018/fevereiro/

The first format is for gazzetes under 2017 and is veeery incomplete. Is missing a LOT of gazzetes.

The second format is for gazzetes of 2017 and above. In this format there is no way to get the day of the gazzete.

It's necessary enter in contact with the city hall. What would be better, a project representative to contact the city hall or me?

**Comment by cuducos** [comment]
> The second format is for gazzetes of 2017 and above. In this format there is no way to get the day of the gazzete.

The day is in the PDF, isn't it? If not, can you link a PDF missing the date?

Regarding the different URLs, que can have `start_urls` that yields the proper URL according to the date… does that make sense?

**Comment by danilolutz** [comment]
Can I help with or assume this Spider?

**Comment by AlvaroLQueiroz** [comment]
Yes @danilolutz , you can take this.

**Comment by danilolutz** [comment]
Thanks a lot @AlvaroLQueiroz

**Comment by rennerocha** [comment]
Closing stale issue.
