### ISSUE TITLE
Cruzeiro do Sul-AC

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#663]

**Comment by ruancomelli** [comment]
Pesquisei a disponibilidade de diários oficiais do município de Cruzeiro do Sul (AC). No site [oficial da prefeitura](https://www.cruzeirodosul.ac.gov.br/), há um link que redireciona o usuário para o [acervo de diários oficiais do Acre](http://diario.ac.gov.br/). Esses diários oficiais são publicados em conjunto, isto é, vários municípios publicam em um mesmo documento.
Parece possível construir um crawler que extraia os documentos do acervo, mas, após isso, seria necessária a segmentação do arquivo PDF para separar as informações de cada município. Creio que isso esteja fora da capacidade tecnológica do projeto no momento.

**Comment by trevineju** [comment]
Como mencionado acima por @ruancomelli, ainda que este município seja viável de raspar (no diário do Estado do Acre) o projeto ainda não ter arquitetura para segmentá-lo; por isso fecho a issue até termos condições de retomá-la
