### ISSUE TITLE
Sorriso-MT

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#665]

**Comment by ayharano** [comment]
O mais próximo de diário oficial que encontrei foi essa URL: https://diariomunicipal.org/mt/amm/publicacoes/?q=%22Prefeitura%20Municipal%20de%20Sorriso%22

**Comment by trevineju** [comment]
Issue sendo fechada pois o município publica diários junto à Federação das Associações de Municípios do MT. Uma vez que tenhamos um segmentador para o diário da associação, esta issue poderá ser retomada
