### ISSUE TITLE
Cáceres-MT

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#666]

**Comment by ayharano** [comment]
N[o mapa de site da prefeitura](https://www.caceres.mt.gov.br/Mapa-Site/) não consta um link sobre diários oficiais.

Em https://diariomunicipal.org/mt/amm/publicacoes/?e=450, tem como entrada a `Prefeitura Municipal de Cáceres`, mas precisaria verificar se possuem um diário unificado a ser extraído.

**Comment by trevineju** [comment]
Issue sendo fechada pois o município publica diários junto à Federação das Associações de Municípios do MT. Uma vez que tenhamos um segmentador para o diário da associação, esta issue poderá ser retomada
