### ISSUE TITLE
Manacapuru-AM

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#668]

**Comment by ayharano** [comment]
No site d[a prefeitura](https://www.manacapuru.am.gov.br/), consta um link sobre diário oficial para https://diariomunicipalaam.org.br/

Manacapuru é uma das opções da página e precisaria verificar se possui um diário oficial unificado da própria cidade

**Comment by trevineju** [comment]
Issue sendo fechada pois o município publica diários junto à Associação de Municípios do AM. Uma vez que tenhamos um segmentador para o diário da associação, esta issue poderá ser retomada
