### ISSUE TITLE
Itaituba-PA

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#669]
# Análise dos sistemas de publicação

## Sistema 1

Data da análise: 18/10/22

URL da página inicial: https://www.diariomunicipal.com.br/famep/

- [X] Publica atualmente
- [X] Possui publicações em datas que só podem ser encontradas neste sistema

### Formas de consulta

URL da forma de consulta: https://www.diariomunicipal.com.br/famep/
- [ ] Possui paginação
- [ ] Possui filtro por data
- [ ] Possui captcha (ou recaptcha)
- [X] Documento publicado é uma edição completa de diário oficial
- [ ] Documento publicado possui atos oficiais apenas deste município
- [X] Documento publicado em formato PDF (texto), DOC ou TXT
- [ ] Documento publicado em formato PDF (imagem), HTML, JSON, arquivo de imagem, etc. 

Observações: Município publica junto com outros municípios na associação de municípios (FAMEP). Documento acessível através da seleção de uma data no calendário.

---

URL da forma de consulta: https://www.diariomunicipal.com.br/famep/pesquisar
- [X] Possui paginação
- [X] Possui filtro por data
- [X] Possui captcha (ou recaptcha)
- [ ] Documento publicado é uma edição completa de diário oficial
- [X] Documento publicado possui atos oficiais apenas deste município.
- [ ] Documento publicado em formato PDF (texto), DOC ou TXT
- [X] Documento publicado em formato PDF (imagem), HTML, JSON, arquivo de imagem, etc. 

Observações: A busca avançada permite selecionar apenas publicações da prefeitura do município. Porém, possui diversas características que não se adequam bem ao projeto, incluindo a presença de recaptcha.

**Comment by trevineju** [comment]
Issue sendo fechada pois o município publica diários junto à Federação das Associações de Municípios do Pará - FAMEP. Uma vez que tenhamos um segmentador para o diário da associação, esta issue poderá ser retomada
