### ISSUE TITLE
Itacoatiara-AM

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#670]

**Comment by MateusSantosMeuBem** [comment]
Foram feitas as pesquisas pelas formas de publicação do diário oficial. Encontrou-se, porém a publicação é feita em conjunto com outros municípios.

Link do endereço para se buscar os diários oficiais onde Itacoatiara pode estar: https://diariomunicipalaam.org.br/ 
Todo o histórico de publicações pode ser encontrado nesse mesmo endereço.

**Comment by trevineju** [comment]
Issue sendo fechada pois o município publica diários junto à Associação de Municípios do AM. Uma vez que tenhamos um segmentador para o diário da associação, esta issue poderá ser retomada
