### ISSUE TITLE
Breves-PA

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#671]

**Comment by ayharano** [comment]
N[a página da prefeitura](https://breves.pa.gov.br/), existe um link de Diário Oficial, mas não foi possível navegar para outra página. Existe alguma âncora na página, mas a primeira vista, não encontrei como acessar.

**Comment by trevineju** [comment]
O município aparenta não publicar um diário oficial único, publicando atos oficiais fragmentados em seu site. O Querido Diário ainda não trata esse tipo de publicação, por isso fecho a issue até termos condições de retomá-la
