### ISSUE TITLE
Bacabal-MA

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#673]

**Comment by LuccaBortoloso** [comment]
Estou trabalhando nesta Issue

**Comment by rennerocha** [comment]
Diário Disponível em:
https://www.bacabal.ma.gov.br/diario
Porém a peridiocidade de publicação é baixa. Não sei se está 100% correto, mas é o que temos disponível oficialmente.

**Comment by rennerocha** [comment]
A cidade de Codá-MA (#682 ) utiliza o mesmo sistema. É possível fazer um spider base e replicar para as duas cidades.
