### ISSUE TITLE
Tangará da Serra-MT

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#674]

**Comment by ayharano** [comment]
Aparentemente não possui um diário oficial unificado e o nome do município consta como uma das opções em https://diariomunicipal.org/mt/amm/publicacoes/?e=341

**Comment by trevineju** [comment]
Issue sendo fechada pois o município publica diários junto à Federação das Associações de Municípios do MT. Uma vez que tenhamos um segmentador para o diário da associação, esta issue poderá ser retomada
