### ISSUE TITLE
Tailândia-PA

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#676]

**Comment by MateusSantosMeuBem** [comment]
O diário oficial é publicado de maneira muito segmentada no próprio site da prefeitura de Tailândia, porém, sem uma forma de organização adequada para se informar ao raspador. Ademais, os arquivos são digitalizados, e dos poucos arquivos que são disponibilizados em um único arquivo, esses ainda ficam alocados no Google Drive.

Link do diário: https://www.tailandia.pa.gov.br/category/atos/
