### ISSUE TITLE
Parintins-AM

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#679]

**Comment by ayharano** [comment]
[O site da prefeitura](https://parintins.am.gov.br/) possui um link de Diário Oficial em https://www.diariomunicipal.com.br/aam/ e aparentemente é um diário de associação de municípios.

**Comment by trevineju** [comment]
Issue sendo fechada pois o município publica diários junto à Federação das Associações de Municípios do AM. Uma vez que tenhamos um segmentador para o diário da associação, esta issue poderá ser retomada
