### ISSUE TITLE
Tucuruí-PA

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#680]

**Comment by ayharano** [comment]
N[a página da prefeitura](https://tucurui.pa.gov.br/), não foi possível encontrar um link para diários oficiais.

N[a página de diários da associação de municípios da FAMEP](https://www.diariomunicipal.com.br/famep/pesquisar), `Prefeitura Municipal de Tucuruí` é uma das opções disponíveis. Precisaria verificar se existe um diário oficial unificado para o município.
