### ISSUE TITLE
Bragança-PA

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#686]

**Comment by ayharano** [comment]
Dentro do site d[a prefeitura](https://braganca.pa.gov.br/), não encontrei nada a respeito.

Encontrei esse site https://www.ioepa.com.br/pesquisa/?q=%22Prefeitura%20Municipal%20de%20Bragan%C3%A7a%22&di=00010101&df=20991201 mas não sei quão relevante seria.

**Comment by trevineju** [comment]
O município aparenta não publicar um diário oficial único, publicando atos oficiais fragmentados em seu site. O Querido Diário ainda não trata esse tipo de publicação, por isso fecho a issue até termos condições de retomá-la
