### ISSUE TITLE
São Félix do Xingu-PA

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#688]

**Comment by ayharano** [comment]
Não encontrei diários oficiais unificados. Do site d[a prefeitura](https://www.sfxingu.pa.gov.br/), encontrei algumas listagens de publicações:

- [Decretos e Legislações](https://www.sfxingu.pa.gov.br/decretos-e-legislacao/)
- [Edital de Notificação](https://www.sfxingu.pa.gov.br/edital-de-notificacao/)

**Comment by trevineju** [comment]
Issue sendo fechada pois o município publica diários junto à Federação das Associações de Municípios do Pará - FAMEP. Uma vez que tenhamos um segmentador para o diário da associação, esta issue poderá ser retomada
