### ISSUE TITLE
Marituba-PA

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#689]

**Comment by ayharano** [comment]
Aparentemente não tem um diário oficial unificado. Segue a página de publicações pela página da prefeitura: https://marituba.pa.gov.br/site/c/publicacoes/

**Comment by trevineju** [comment]
Issue sendo fechada pois o município publica diários junto à Federação das Associações de Municípios do Pará - FAMEP. Uma vez que tenhamos um segmentador para o diário da associação, esta issue poderá ser retomada
