### ISSUE TITLE
Sinop-MT

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#691]

**Comment by ayharano** [comment]
O link mais próximo d[o mapa do site da prefeitura](https://www.sinop.mt.gov.br/Mapa-Site/), indica um link de [Portal da Transparência](https://www.gp.srv.br/transparencia_sinop/servlet/home_portal_v2), mas lá não consta sobre diários oficiais.

Em https://diariomunicipal.org/mt/amm/publicacoes/?e=344, `Prefeitura Municipal de Sinop` é uma das opções, então precisaria avaliar se é possível extrair um diário oficial unificado do município.

**Comment by fernandoemm** [comment]
A Prefeitura Municipal de Sinop publica o Diário Oficial dentro do Diário do Tribunal de Contas do Mato Grosso desde 1º de julho de 2017. https://servicos.tce.mt.gov.br/diario#/home

Até essa data, os diários eram publicados no Jornal Oficial Eletrônico dos Municípios de Mato Grosso, no site da Associação Mato-Grossense dos Municípios (AMM). https://diariomunicipal.org/mt/amm/edicoes/

**Comment by trevineju** [comment]
Estou fechando esta issue pois o formato de publicação do município seja na AMM ou no TCE são diários agregados, não compatíveis com o projeto no momento
