### ISSUE TITLE
Abaetetuba-PA

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#692]

**Comment by ayharano** [comment]
O resultado cacheado do Google para [o link da prefeitura](https://www.abaetetuba.pa.gov.br/) indica a existência de um link para Diário oficial, mas eu não consegui acessar a página da prefeitura

**Comment by trevineju** [comment]
Issue sendo fechada pois o município publica diários junto à Federação das Associações de Municípios do Pará - FAMEP. Uma vez que tenhamos um segmentador para o diário da associação, esta issue poderá ser retomada
