### ISSUE TITLE
Castanhal-PA

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#694]

**Comment by ayharano** [comment]
O site d[a prefeitura](http://www2.castanhal.pa.gov.br/) indica uma URL https://sites.google.com/castanhal.pa.gov.br/diariooficialdecastanhal/inicio que exige efetuar algum tipo de login

**Comment by bwstefano** [comment]
Verifiquei hoje e não há mais necessidade de senha. A página é construída com o Google Sites e todas as edições do Diário Oficial são disponibilizadas em PDF com links do Google Drive desde 5 de dezembro de 2010.
