### ISSUE TITLE
Várzea Grande-MT

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#699]

**Comment by ayharano** [comment]
Não encontrei um diário oficial unificado. O mais próximo que encontrei foi https://diariomunicipal.org/mt/amm/publicacoes/?e=334

**Comment by trevineju** [comment]
Issue sendo fechada pois o município publica diários junto à Federação das Associações de Municípios do MT. Uma vez que tenhamos um segmentador para o diário da associação, esta issue poderá ser retomada
