### ISSUE TITLE
Portal da transparência - São Paulo/SP

### ISSUE THREAD

**Issue by brunolellis** [okfn-brasil/querido-diario#7]
A cidade de São Paulo disponibiliza os dados de compras e licitações no Portal da Transparência nos formatos csv, xls e ods desde 2005.
Link: http://transparencia.prefeitura.sp.gov.br/contas/Paginas/ComprasLicitacoes.aspx

Estou criando esta issue apenas para documentar e avaliar qual seria a melhor opção para armazenar um dado mais estruturado (comparando com os pdfs das demais cidades).

**Comment by Irio** [comment]
@brunolellis Esses arquivos apresentam as mesmas informações que o Diário Oficial? É atualizado com a mesma frequência?

**Comment by brunolellis** [comment]
@Irio, olhando com mais detalhes, tenho a impressão que todas as licitações estão descritas no arquivo csv. 
Não consegui descobrir a periodicidade de divulgação. Pelo nome do arquivo, creio que seja mensal: `Extrato de Contrato - Janeiro_2016 a Março_2018.csv` 

Obs: não trabalho nessa área de órgãos públicos e nem tenho experiência nesta área, portanto posso estar completamente errado nas considerações.

**Comment by brunolellis** [comment]
O download do pdf de cada DO pode ser bem mais trabalhoso, pois não existe (não encontrei) um pdf contendo todas as páginas do DO.
 
O que existe é 1 arquivo pdf para cada página do DO daquele dia. Ou seja, no dia 20/4/2018, o DO possui 142 páginas e, portanto, 142 pdfs. :open_mouth:

**Comment by williamcspereira** [comment]
Complementando a informação sobre o download do PDF ser restrito por página, encontrei um padrão na publicação dos arquivos, o que pode ajudar na coleta. Este padrão foi encontrado somente nos DO's publicados a partir de 30/01/2018.

ex.:  diário oficial (cidade) do dia 27/04/2018

http://diariooficial.imprensaoficial.com.br/doflash/prototipo/ **2018** / **Abril** / **27** / **cidade** / **pdf** / **pg_0001.pdf**
http://diariooficial.imprensaoficial.com.br/doflash/prototipo/2018/Abril/27/cidade/pdf/pg_0002.pdf
http://diariooficial.imprensaoficial.com.br/doflash/prototipo/2018/Abril/27/cidade/pdf/pg_0003.pdf
...

**Comment by alfakini** [comment]
@Irio Você acha que é uma boa abordagem seguirmos pegando o diário oficial mas concatenar todas as páginas em um único PDF?

**Comment by JaTvoiRabotnik** [comment]
@williamcspereira , esse formato funcionava ano passado tambem. O fato que so da pra pegar diarios desse ano me faz concluir que a imprensa oficial anda deletando os PDFs.

**Comment by nfraprado** [comment]
I was surprised to see that São Paulo still didn't have a spider done. Is someone already working on that or is it free for grabs?

The census already has this [Diário Oficial page](http://www.docidadesp.imprensaoficial.com.br/Busca.aspx) mapped. 

From what I understood from the discussion in this issue, there's also [another page](http://transparencia.prefeitura.sp.gov.br/contas/Paginas/ComprasLicitacoes.aspx) that shows a lot of information (although perhaps not all of it) already in the csv format. That said, accessing the page now, shows that its last update was on 2019, while the Diário Oficial one keeps being updated everyday, so it is my understanding that we still want to do a spider for the Diário Oficial page and parse the pdfs.

**Comment by giuliocc** [comment]
### English

@nfraprado go for it :)

About the other page, right now we are focusing strictly on Gazettes. Don't worry about that for now.

---
### Português

@nfraprado pode pegar :)

Sobre a outra página, no momento estamos focando apenas em Diários Oficiais. Não se preocupe com ela por enquanto.

**Comment by jvanz** [comment]
Can we close this issue?

**Comment by jvanz** [comment]
Oh... I just noticed the #380. Closing this one.
