### ISSUE TITLE
Rio Branco-AC

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#701]

**Comment by ruancomelli** [comment]
Pesquisei a disponibilidade de diários oficiais do município de Rio Branco (AC). No [site oficial da prefeitura](http://www.riobranco.ac.gov.br/), há um link para consulta no seu [portal da transparência](http://transparencia.riobranco.ac.gov.br/consulta/). Ao pesquisar "diário oficial", o site retorna diversas entradas (vide, por exemplo, a [Portaria 192/2022](http://transparencia.riobranco.ac.gov.br/ato-legal/ver/5418/)). Várias dessas entradas (nem todas) possuem um link no campo "Documento" que levam a um trecho escaneado de um diário oficial (vide, por exemplo, o [documento para a Portaria 192/2022](http://transparencia.riobranco.ac.gov.br/arquivo?id=5442)).

De forma similar ao que eu [observei para Cruzeiro do Sul (AC)](https://github.com/okfn-brasil/querido-diario/issues/663#issuecomment-1282609522), esse documento parece um trecho dos [diários oficiais do Acre](http://diario.ac.gov.br/), que incluem entradas para vários (todos?) municípios, e também requeriria a segmentação do PDF para separar informações de municípios diferentes.

A construção de um crawler parece viável, mas a extração automática de informações ainda requer a segmentação do documento para diferentes municípios.

**Comment by trevineju** [comment]
Como mencionado acima por @ruancomelli, ainda que este município seja viável de raspar (no diário do Estado do Acre) o projeto ainda não ter arquitetura para segmentá-lo; por isso fecho a issue até termos condições de retomá-la
