### ISSUE TITLE
[Revisão retroativa] Spider mg_governador_valadares com problemas

### ISSUE THREAD

**Issue by Renatochaz** [okfn-brasil/querido-diario#736]
O spider de mg_governador_valadares não está mais trazendo diários. Além disso, a chave usada para definir a data de publicação do diário traz algumas datas inconsistentes.

Estou abrindo um PR linkando essa issue que corrige esses problemas e abstrai a lógica desse spider para um spider base, que também é usado para as cidades de mg_manhuaçu e ma_sao_jose_do_ribamar.

**Comment by trevineju** [comment]
Fecho a issue pois o município está contemplado na listagem de mapeamento em #1083
