### ISSUE TITLE
[Novo spider base] DIOENET

### ISSUE THREAD

**Issue by ayharano** [okfn-brasil/querido-diario#752]
### URL

https://plenussistemas.dioenet.com.br/

### Municípios replicados

```bash
1. https://plenussistemas.dioenet.com.br/list/taubate
2. https://plenussistemas.dioenet.com.br/list/pedra-branca-do-amapari
3. https://plenussistemas.dioenet.com.br/list/paraiso-das-aguas
```

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Detalhes do site de publicação

Possui paginação

### Observações

Para mais informações, consulte a documentação sobre [sistemas replicáveis](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#as-classes-sistemagazettespider).

### Não existe uma issue aberta sobre isso

- [X] Eu verifiquei e não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo sistema.

**Comment by LuccaBortoloso** [comment]
Estou trabalhando nesta Issue

**Comment by trevineju** [comment]
Muito obrigada @LuccaBortoloso! 

Quando você enviar o PR para o spider base, não precisa enviar os spiders para todas essas cidades junto, apenas alguns (dois ou três, a sua escolha :3), para validar a abstração e te poupar de ter que testar um monte de spider ao mesmo tempo. 

Sugiro isso apenas temporariamente. Como a contribuição de um sistema publicador abre a possibilidade aumentar muito as cidades no Querido Diário -- que é excelente! -- também precisamos ver se nossa infra aguenta. Teremos uma reunião de pessoas mantenedoras na quinta (sinta-se convidado, é no Discord), e trago uma atualização! 

Como o @ayharano foi mt sagaz em criar a tarefa em forma de checklist, você pode apenas dar check nas cidades que pretende incluir nesse início e, consequentemente, vamos ter um controle de quais faltam também.

**Comment by almeidadm** [comment]
Parece ser bem possível resolver esse problema utilizando uma API do Google Drive. As soluções são bem simples e podem ser resolvidas com a construção de uma pipeline própria para o Download dos dados utilizando a API.

Aqui um exemplo de como usar a API:
https://developers.google.com/drive/api/guides/manage-downloads?hl=pt-br#python

Agora sobre a construção de Pipeline. Acredito que a pipeline nesse caso deveria dar conta dos itens coletados de maneira convencional, assim como dos itens coletados através da API. Acredito também que, por não haver muitos casos, a pipeline poderia ser habilitada através do custom_settings de cada spider. Dessa forma não só fica evidente os casos em que esse problema ocorre, mas também evita de gerar conflitos com o restante das spiders.

**Comment by ogecece** [comment]
@almeidadm, peguei os exemplos que você listou aqui. Me parece que fazendo acesso a URL no formato `https://plenussistemas.dioenet.com.br/uploads/diario/<hash>` (ex: `https://plenussistemas.dioenet.com.br/uploads/diario/1FVZ4h6gb6OzLf5lZF1X727zFhko-RVoU` é possível pegar o PDF diretamente. O hash está disponível na própria URL nos casos anteriores a 2023 ou então na página de resposta da requisição nos casos atuais.

Pode confirmar aí se consegue desenrolar o raspador assim?

**Comment by almeidadm** [comment]
Oi!
Eu vi mesmo que o site atualizou! Está possível desenvolver da maneira que está. Vou me organizar para desenvolver esse fim de semana ;)
