### ISSUE TITLE
[Novo spider base]: Siganet

### ISSUE THREAD

**Issue by ayharano** [okfn-brasil/querido-diario#755]
Ao verificar o PR#746 de @lucasocarvalhos, foi possível ver no rodapé da página inicial consta uma nota de copyright mencionando uma empresa ou produto chamado [Siganet](https://www.siganet.net.br/)

Baseado nos resultados das busca em Google por `Siganet site:gov.br diário prefeitura`, temos alguns municípios que parecem utilizar o mesmo sistema:

- [ ] 2100907 Araioses, MA (último diário: 2022-10-20)
https://transparencia.araioses.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2101251 Bacabeira, MA (último diário: 2022-09-28)
https://transparencia.bacabeira.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2101350 Bacurituba, MA (último diário: 2022-10-20)
https://transparencia.bacurituba.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2101400 Balsas, MA (último diário: 2022-10-21 - PR #746)
https://transparencia.balsas.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2101806 Benedito Leite, MA (último diário: 2022-10-20)
https://transparencia.beneditoleite.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2102804 Carolina, MA (último diário: 2022-10-19)
https://transparencia.carolina.ma.gov.br/acessoInformacao/diario/diario
- [x] 2103604 Coroatá, MA (último diário: 2022-10-19)
https://transparencia.coroata.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2104073 Feira Nova do Maranhão, MA (último diário: 2022-10-14)
https://transparencia.feiranovadomaranhao.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2104107 Fortaleza dos Nogueiras, MA (último diário: 2022-10-21)
https://transparencia.fortalezadosnogueiras.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2104800 Grajaú, MA (último diário: 2022-10-21)
https://transparencia.grajau.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2106607 Matões, MA (último diário: 2022-10-20)
https://www.transparencia.matoes.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2107258 Nova Colinas, MA (último diário: 2022-10-21)
https://transparencia.novacolinas.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2107407 Olho d'Água das Cunhãs, MA (último diário: 2022-10-20)
https://transparencia.olhodaguadascunhas.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2108058 Paulino Neves, MA (último diário: 2022-10-17)
https://transparencia.paulinoneves.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2108306 Penalva, MA (último diário: 2022-10-21)
https://transparencia.penalva.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2109007 Porto Franco, MA (último diário: 2016-12-11 !!!!!!)
https://transparencia.portofranco.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2109601 Rosário, MA (último diário: 2022-10-21)
https://www.transparencia.rosario.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2110039 Santa Luzia do Paruá, MA (último diário: 2022-10-21)
https://transparencia.santaluziadoparua.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2110658 São Domingos do Azeitão, MA (último diário: 2022-10-21)
https://transparencia.saodomingosdoazeitao.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2110906 São Francisco do Maranhão, MA (último diário: 2022-10-17)
https://transparencia.saofranciscodomaranhao.ma.gov.br/acessoInformacao/diario/diario
- [x] 2111250 São José dos Basílios, MA (último diário: 2022-10-20)
https://transparencia.saojosedosbasilios.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2111573 São Pedro dos Crentes, MA (último diário: 2022-10-18)
https://transparencia.saopedrodoscrentes.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2112506 Tutóia, MA (último diário: 2022-10-18)
https://transparencia.tutoia.ma.gov.br/acessoInformacao/diario/diario
- [ ] 2112803 Viana, MA (último diário: 2022-10-21)
https://transparencia.viana.ma.gov.br/acessoInformacao/diario/diario

Essa issue seria sobre criar um spider base para Siganet ou refatorar o criado para Balsas, MA.

**Comment by giuliocc** [comment]
Verifiquei que o diário é uma republicação do que é publicado no [diário oficial da federação de municípios do estado do Maranhão](https://www.diariooficial.famem.org.br/). Então o siganet seria incompatível :(

**Comment by trevineju** [comment]
por conta do comentário de Giulio, estou fechando esta issue enquanto não temos um segmentador pra FAMEM

**Comment by trevineju** [comment]
Opa, reabrindo esta issue pois há cidades que usam o siganet, porém não associadas à Federação do Maranhão. Exemplos são: #873 e #758

**Comment by trevineju** [comment]
Base adicionada por #746
