### ISSUE TITLE
Campo Belo-MG

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#792]
O município utiliza um sistema publicador com o spider base já em produção (INSTAR), para adicionar a cidade bastaria replicar o raspador de `sp_vinhedo` e fazer adaptações. 
Este repositório conta também com um spider antigo deste município que pode ser revisado, caso já esteja herdando a spider base do INSTAR.

**Comment by ayharano** [comment]
Conforme conversado offline, logo mais abro um PR para essa issue, juntando as issues de MG de INSTAR

cc @trevineju
