### ISSUE TITLE
Arraial do Cabo-RJ

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#796]
O município utiliza um sistema publicador com o spider base já em produção (INSTAR), para adicionar a cidade bastaria replicar o raspador de sp_vinhedo e fazer adaptações.
Este repositório conta também com um spider antigo deste município que pode ser revisado, caso já esteja herdando a spider base do INSTAR.

**Comment by LuccaBortoloso** [comment]
Estou trabalhando nesta issue
