### ISSUE TITLE
Camaquã-RS

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#797]
O município utiliza um sistema publicador com o spider base já em produção (INSTAR), para adicionar a cidade bastaria replicar o raspador de sp_vinhedo e fazer adaptações.

**Comment by marcospscruz** [comment]
Vou tentar fazer esse issue. Será o meu primeiro! Espero que dê certo.

**Comment by trevineju** [comment]
Resolvido por #804
