### ISSUE TITLE
Diário Oficial de Bacabal-MA indisponível

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#826]
A última edição do Diário Oficial disponível no site de Bacabal-MA foi publicado no dia 16/12/2022. Até o dia de hoje (13/02/2023), não houve nenhuma nova publicação. Não há indicação de que a prefeitura está publicando os Diários em uma nova URL: https://www.bacabal.ma.gov.br/diario

Estamos recebendo notificações no canal de monitoramento já que não temos diários a mais de 7 dias, então temporariamente devemos desabilitar esse spider, porém é necessário monitorar para voltar a coletar os Diários assim que a prefeitura volte a publicá-los na página **e/ou** alguém entrar em contato oficialmente com a prefeitura afim de descobrir o que está acontecendo.

**Comment by trevineju** [comment]
@rennerocha vou entrar em contato com a prefeitura, mas minha impressão é que ela demora muito tempo pra publicar diários, e ainda pública diário retroativamente. 

Olhando todo o histórico da Zyte pra cidade (ver: [histórico](https://app.zyte.com/p/631875/82)), não tem uma única vez que o raspador diário coletou item, com exceção de quando virou o ano, em 02/01/23 (ver: [job](https://app.zyte.com/p/631875/82/21)). Foi uma nova raspagem completa nessa data, ne?

Acho que a Zyte mostra só o histórico recente, então não tem mais muitos logs no histórico, porém usando o canal #qd-monitoramento no Discord, é possível reparar o mesmo padrão: não tem nenhuma raspagem com sucesso, com exceção desse dia já visto na zyte 
![image](https://user-images.githubusercontent.com/44185775/223449041-8fc0f2c8-3b55-487b-85c1-ad278075ef73.png)

E o dia que o raspador entrou em produção: 
![image](https://user-images.githubusercontent.com/44185775/223449282-8468b4e3-ab36-4aae-9f8d-3829fedc9a7e.png)

Tem cerca de 1 mês (dezembro) de distância entre essas duas raspagens, e só 2 diários novos foram coletados, sendo nenhum de dezembro (pq a última edição que temos no QD é de 25/11/22 (conferir em: [pesquisa no QD](https://queridodiario.ok.org.br/pesquisa?city=2101202&sort_by=descending_date)). Hoje, no site da prefeitura, constam 7 edições em dezembro. 

Sem contar que do momento que vc abriu essa issue pra hoje, um novo diário está disponível lá, de 06/01/2023. Porém estamos em março e o diário que está sendo publicado é de janeiro. Muito tempo. 

Rodei localmente na minha máquina hoje e obtive 895 arquivos (contra os  798 do QD atualmente). (ver: [log_bacabal.txt](https://github.com/okfn-brasil/querido-diario/files/10910521/log_bacabal.txt) e [bacabal.csv](https://github.com/okfn-brasil/querido-diario/files/10910523/bacabal.csv))

Você acha que uma boa intermediação dessa situação poderia ser fazer uma raspagem completa de bacabal 1x por mês?

cc @giuliocc

**Comment by rennerocha** [comment]
@giuliocc acho que precisamos ter a possibilidade de controlar essas execuções, mas acho que o `enabled_spiders` não é o melhor. Ele é uma solução boa para uma dezena de spiders mas ruim para centenas. Acho que podemos tentar avançar com https://github.com/okfn-brasil/querido-diario/pull/597 para podermos fazer esse controle de uma maneira mais adequada.

**Comment by giuliocc** [comment]
Faz sentido @rennerocha !

**Comment by trevineju** [comment]
Estou fechando esta issue visto que optamos por tirar Bacabal de produção e a página de cidades disponíveis do QD está transparecido que temos diários apenas até o fim de 2022; além da conversa sobre a melhor forma de controlar as rotinas de raspagem já estar sendo endereçada em outro lugar.
