### ISSUE TITLE
[Revisão retroativa] Caucaia-CE

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#842]
### Objetivo da Issue

Neste repositório, há muitos códigos de raspadores que foram desenvolvidos no começo do projeto e não estão sendo usados. Para passar a usar o raspador deste município, é necessário testar para verificar se segue funcionando e revisá-lo caso não esteja.

### URL

https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/ce_caucaia.py

### É um município replicado?

Não, o código utiliza BaseGazetteSpider.

### Período de publicação

O site raspado segue sendo o atual publicador de diários do município

### Lista de testes

Checklist de referência para testes:
- [   ]  Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [   ]  Você executou uma extração por período (start_date e end_date definidos) ao menos uma vez e os dados retornados estavam corretos.
- [   ]  Você verificou que não existe nenhum erro nos logs (log/ERROR igual a zero).
- [   ]  Você definiu o atributo de classe start_date no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [   ]  Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

**Comment by engFelipeMonteiro** [comment]
irei atuar nesta issue durante a sprint D1

**Comment by giuliocc** [comment]
Esse município faz parte do sistema aDiarios de #870

**Comment by trevineju** [comment]
Fechando a issue, pois o município incorporado na listagem de #1082
