### ISSUE TITLE
[Revisão retroativa] Santos-SP

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#845]
### Objetivo da Issue

Neste repositório, há muitos códigos de raspadores que foram desenvolvidos no começo do projeto e não estão sendo usados. Para passar a usar o raspador deste município, é necessário testar para verificar se segue funcionando e revisá-lo caso não esteja.

### URL

https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/sp_santos.py

### É um município replicado?

Não, o código utiliza BaseGazetteSpider.

### Período de publicação

É o atual site publicador de diários do município. Porém o código do raspador começa em 2015, enquanto no site parece ter diários desde 2001

### Lista de testes

Checklist de referência para testes:
- [   ]  Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [   ]  Você executou uma extração por período (start_date e end_date definidos) ao menos uma vez e os dados retornados estavam corretos.
- [   ]  Você verificou que não existe nenhum erro nos logs (log/ERROR igual a zero).
- [   ]  Você definiu o atributo de classe start_date no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [   ]  Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

**Comment by bmortella** [comment]
Vou dar uma olhada nesse.

**Comment by bmortella** [comment]
@trevineju dei uma olhada e notei que todos os arquivos são baixados sem a extensão pdf. Isso seria um problema?

Fora isso, o script parece funcionar perfeitamente para datas anteriores a 2015. Vou fazer um PR depois de testar por completo.

**Comment by trevineju** [comment]
Oi, @bmortella! Isso é um problema, mas não um problema do raspador, então pode desenvolver o raspador normalmente. 

Quem não desenvolve em Linux, o arquivo não ter a extensão impediria a pessoa de verificar os arquivos baixados e, mais importante, no site, nós temos um "baixe o arquivo original aqui" que baixa um arquivo sem a extensão. Quanto aos devs testando, não soube de ninguém passando por isso na nossa comunidade, tô assumindo que usem Linux, mas já tivemos pessoas usuárias do site que tiveram problemas. 

Vou abrir uma issue sobre o assunto, mas Giulio sinalizou que vai resolver isso tratando esses casos em alguma etapa da pipeline.

Boa! Obrigada por pegar a tarefa!
