### ISSUE TITLE
[Novo Spider] Jeremoabo-BA

### ISSUE THREAD

**Issue by Diegiwg** [okfn-brasil/querido-diario#852]
## Dados para cadastro

Selecione o município: `Jeremoabo (BA)`
Existe uma fonte de publicação disponível online? `SIM`
Qual a data do arquivo mais antigo disponível online? `08/07/2010`
Qual o formato dos arquivos? `PDF texto`
Informe uma fonte de publicação de arquivos: <https://www.jeremoabo.ba.gov.br/Site/DiarioOficial>

## Informações extras de raspagem

O site utiliza a seguinte API para acesso aos documentos `https://www.jeremoabo.ba.gov.br/Handler.ashx?f=diario&query=1&c=_ID_NUMERICO_DOCUMENTO_&m=0`.

No sistema de buscas do site, o arquivo mais antigo disponível possui o `ID 427`, o que me levou a simplesmente testar colocar valores abaixo.

Para minha surpresa, existem documentos desde do `ID 1`, e estão disponíveis para download normalmente.

Então, tecnicamente, a data de documentos disponíveis no Diário Oficial seria `29 de julho de 2005`, a data do documento com `ID 1`.

**Comment by trevineju** [comment]
oi @Diegiwg! Obrigada pela pesquisa!! 

Se você não conseguiu adicionar é porque já foi cadastrado e está na fila de validação. Porém, estamos em processo de desativar o censo, pq percebemos que entre realizar a pesquisa de links e, de fato, desenvolver aquele raspador, os links mapeados mudavam e fomos descobrindo outras características dos sites que o censo não vinha mapeando (e achamos elas ao desenvolver os raspadores). Então não precisa se preocupar. 

Você pretende desenvolver o raspador pra essa cidade? Não precisa cadastrar no censo pra isso. Se for, pode seguir com as infos que você já tem; mas se não puder, pensei em editar essa issue para ser uma issue de raspador (já que já achou até a API) ao invés de erro. o que vc acha?

**Comment by Diegiwg** [comment]
Opa, pode editar a issue. Obrigado pela resposta ^^

**Comment by trevineju** [comment]
Estou fechando esta issue já que a cidade publica em um sistema replicável, e já será endereçada no contexto de outra issue. #907
