### ISSUE TITLE
Spider de pr_maringa fazendo muitas requisições

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#856]
## Histórico 
Jobs 10 ao 13: Na Zyte, foi possível acompanhar que o raspador posto em produção pelo #850 não estava fazendo nenhuma request por bloqueio de IP. 

Job 14: Por isso, habilitei o smart_proxy em #854, o que resolveu. Foram feitas 535 requests após a modificação. Entretanto, nenhum arquivo foi baixado e a execução do raspador interrompeu depois de 1h. (esta questão do limite está endereçada na issue #853) 

Job 15: Como pr_maringa está habilitado, a rotina diária de raspagem foi acionada esta manhã e o raspador coletou 1 edição (a de ontem, 19/05/2023) com sucesso. 

Job 16 e 17: Vendo o sucesso da raspagem de 1 dia, solicitei manualmente duas raspagem; nenhuma completa, mas para o intervalo de 2023->hoje (job 16) e 2021->hoje (job 17), este também sendo cancelado depois de 1h de execução.

![image](https://github.com/okfn-brasil/querido-diario/assets/44185775/a15bd949-2779-4c99-9914-1b40e533741b)

## Questões
Acredito que além de dar uma atenção para a issue #853 para contornar essa interrupção por limite de execução, o raspador para `pr_maringa` está fazendo excessivas requisições, demandando manutenção para mitigar o problema. 

Ainda não desabilitei o raspador de produção visto que a raspagem cotidiana deu certo no job 15; porém é necessário ter em vista essa melhoria não só para a rotina diária, mas também para completarmos a raspagem completa que ficou esburacada.

**Comment by rennerocha** [comment]
@trevineju 
O spider está finalizando em 1 hora porque estamos utilizando uma unit free do Scrapy Cloud. Então eles limitam o tempo de execução de qualquer spider em 1 hora. A quantidade de requests não está me parecendo fora do normal, então acredito que não exista realmente a necessidade de alterar o spider.
