### ISSUE TITLE
[Novo spider base]: Solução aDiarios

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#870]
### URL

https://www.buriticupu.ma.gov.br/diariooficial.php
https://www.itapecurumirim.ma.gov.br/diariooficial.php

### Municípios replicados

```bash
1. Buriticupu-MA
2. Itapecuru Mirim-MA
3. Caucaia-CE
```

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Detalhes do site de publicação

O comentário a seguir utiliza a página de diários do município de Buriticupu-MA como referência, mas por ser um padrão, serve para os demais também. 

O sistema funciona com uma listagem paginada simples com os links (das edições e das próximas páginas) disponíveis no próprio HTML de resposta.

Pesquisando por `https://www.buriticupu.ma.gov.br/diariooficial.php?dtini=07/05/2018&dtfim=07/06/2023&Esf=1&pagina=0` (alterando as datas inicial e final) é possível obter como resultado a mesma listagem paginada que a página principal.

Há uma página intermediária para a edição. Nela, o conteúdo do arquivo é apresentado em HTML.

### Observações

Há edições do "executivo", "legislativo" e "terceiros" e isso pode ser identificado como filtro na própria busca ou no HTML da resposta.

A primeira página dos arquivos PDF é sempre uma menção ao objetivo do Diário Oficial e a validade do documento assinado eletronicamente.

O diário publica um arquivo mesmo que não hajam atos no dia. É possível identificar quais datas não tem edições procurando pelo texto "NESTE DIA NÃO HOUVE PUBLICAÇÃO DE ATOS OFICIAIS" na página intermediária.

### Não existe uma issue aberta sobre isso

- [X] Eu verifiquei e não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo sistema.

**Comment by Jefersonalves** [comment]
Olá! Começei a trabalhar nessa issue como parte da Sprint do Querido Diário & Amazônia Legal
