### ISSUE TITLE
[Novo spider base]: sistema AdminLTE

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#871]
### URL

https://diariooficial.pmsaraguaia.pa.gov.br/
http://diariooficial.gurupi.to.gov.br/

### Municípios replicados

```bash
1. Santana do Araguaia-PA 
2. Gurupi-TO 
```

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Detalhes do site de publicação

O comentário a seguir utiliza a página de diários do município de Santana do Araguaia-PA como referência, mas por ser um padrão, serve para os demais também. 

Para requisitar as edições é necessário utilizar o filtro por data da seguinte forma:
```python
formdata = {"data_inicial": "2023-01-12", "data_final": "2023-06-12", "pagina": "0", "opcao": "opcao_b"}
req = scrapy.FormRequest("https://diariooficial.pmsaraguaia.pa.gov.br/pesquisa/", formdata=formdata)
```
Assim, o resultado é uma listagem paginada simples onde os links dos arquivos estão no próprio HTML da resposta.

### Observações
- Não foi encontrado o nome do sistema replicável em uma primeira análise. Caso isso se mantenha, pode nomear a classe base por `sistema um` mesmo.

### Não existe uma issue aberta sobre isso

- [X] Eu verifiquei e não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo sistema.

**Comment by claromes** [comment]
Trabalhando nessa issue.
