### ISSUE TITLE
Coroatá-MA

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#873]
### URL da forma de consulta

https://coroata.ma.gov.br/diario/diario/

### Período de publicação

28/07/2017 - hoje

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação 

Este município publica utilizando um sistema replicável conhecido e mapeado na issue #757. Uma vez que a classe base para este sistema seja integrada, este município poderá ser adicionado ao Querido Diário. 

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by giuliocc** [comment]
Fechando issue por razão de #746
