### ISSUE TITLE
Gurupi-TO

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#878]
### URL da forma de consulta

http://diariooficial.gurupi.to.gov.br/

### Período de publicação

28/05/2020 - atualmente

### Formato da publicação

Os diários oficiais são publicados em PDF (texto)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Este município publica utilizando um sistema replicável conhecido e mapeado na issue #871. Uma vez que a classe base para este sistema seja desenvolvida, este município poderá ser adicionado ao Querido Diário. 

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by claromes** [comment]
Trabalhando nessa issue via #871
