### ISSUE TITLE
Melhorias de documentação

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#881]
Como a Hacktoberfest, assim como outros eventos, trouxe várias pessoas novas, recebemos muitas perguntas sobre como algo relacionado a raspadores funciona ou onde estão algumas informações. Isso mostra limitações da nossa documentação. 
Peço para adicionarem nesta issue essa natureza de comentário. 

Quem tiver sugestões, ótimo, mas não precisam se preocupar em ser propositivos. Mesmo um "tive dificuldades de saber ou achar tal coisa" já serviria aqui para nos guiar. 

Instalação em Windows
```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    twisted-iocpsupport<2,>=1.0.2 from https://files.pythonhosted.org/packages/41/b0/a3855abf7f5cf46f8696011b9bdde6af74f028fb24f3d78ed05a2b25ccbb/twisted_iocpsupport-1.0.3-cp310-cp310-win_amd64.whl#sha256=1ea2c3fbdb739c95cc8b3355305cd593d2c9ec56d709207aa1a05d4d98671e85 (from twisted==22.10.0->-r data_collection/requirements-dev.txt (line 1017))
```
1. Adicionar uso de `--no-deps` no tutorial de instalação, etapa do pip, para windows

**Comment by Luisa-Coelho** [comment]
Fazendo esse ^^

**Comment by Luisa-Coelho** [comment]
https://github.com/okfn-brasil/querido-diario-data-processing/pull/49

No novo READme do querido-diario-data-processing(esse PR colado) tem uma seção de "Configurando o ambiente do querido-diario" que eu acho que poderia incluir nos dois repositórios.
