### ISSUE TITLE
[Manutenção] Peritoró - MA

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#897]
Em #880, o raspador que até então tinhamos para Peritoró - MA foi desativado pois a cidade mudou o site publicador. 

Precisa-se reconstruir o arquivo `ma_peritoro.py` para raspar o novo site. 
> https://dom.peritoro.ma.gov.br/

**Comment by rafaelgotts** [comment]
Olá, eu gostaria de pegar essa issue, e aproveito para tirar duas dúvidas:

Existe algum outro padrão/modelo para seguir, no lugar do `BaseAplusSpider` ou tem que criar um do zero mesmo?

A outra dúvida, que seria mais sobre o funcionamento da ferramenta eu acho, é como ficam os diários mais antigos dessa cidade, pois eu percebi pela data do código fonte, que tem diários de 2020.

**Comment by trevineju** [comment]
oi, @rafaelgotts! Tem que criar do zero. O `BaseAplusSpider` que tem lá no arquivo da cidade não é mais usado, o site mudou.  Como o site simplesmente não existe mais diários no link antigo, não precisa criar um novo arquivo (tipo `ma_peritoro_2.py`) pode simplesmente reescrever o código no arquivo existente. 

Isso é uma excelente pergunta. É um problema grave dessa prefeitura, quando trocou o site simplesmente sumiu com os diários e ficou um buraco. Temos um registro dessa questão aqui: #https://github.com/okfn-brasil/querido-diario-comunidade/issues/62. 

@ogecece você acha melhor configurar o `start_date` pra quando, tendo em vista que esse é o caso no qual já temos de 04-01-21 até 04-04-23?

**Comment by trevineju** [comment]
aliás, acabo de ver que esse site de Peritoró tem um problema na paginação. Diz ali que só tem 5 páginas, mas dá pra ver as outras páginas seguindo o padrão da url (https://dom.peritoro.ma.gov.br/page/7/)

**Comment by rafaelgotts** [comment]
Blz, vou seguir essas orientações. Obrigado pela resposta e pelas dicas.

**Comment by trevineju** [comment]
@rafaelgotts, o site de diários de peritoró-MA mudou de novo :( 

http://www.transparenciadministrativa.com.br/diario/diariov2.xhtml?token=9de645b503b922df799865ffcb07a6ec7b9cb53e

**Comment by trevineju** [comment]
vi que você já fez o PR pra fazer a correção que precisava (muito obrigada!!), mas o PR também já não serve mais 😢 

você pretende continuar trabalhando nisso?

**Comment by rafaelgotts** [comment]
Oi @trevineju pretendo continuar sim!

Vou ajustar o PR depois. Obrigado por avisar!

**Comment by trevineju** [comment]
Estou liberando esta issue para quem estiver interessada(o) em contribuir (: 

Reforçando que o atual link de Peritoró-MA é: http://www.transparenciadministrativa.com.br/diario/diariov2.xhtml?token=9de645b503b922df799865ffcb07a6ec7b9cb53e

**Comment by trevineju** [comment]
Substituída pela issue #1247
