### ISSUE TITLE
[Novo spider]: Barra dos Coqueiros - SE

### ISSUE THREAD

**Issue by Hudson-Hud** [okfn-brasil/querido-diario#922]
### URL da forma de consulta

https://sai.io.org.br/se/barradoscoqueiros/Site/DiarioOficial

### Período de publicação

janeiro/2013 até outubro/2022

### Formato da publicação

Os diários oficiais são publicados em PDF (imagem scanneada)

### Conteúdo da publicação

Diário único: documento publicado é uma edição completa do diário oficial

### Detalhes do site de publicação

Possui paginação, Possui filtro por data

### Não existe uma issue aberta para esse município

- [X] Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.

**Comment by trevineju** [comment]
oi @Hudson-Hud! Bem-vindo ao projeto!  
Você pretende trabalhar nessa issue?

**Comment by trevineju** [comment]
Barra dos Coqueiros publica em dois locais: 
parte da série histórica de diários está em SAI (#979) e parte está em Município Online (#949) 

Fecho esta issue pois o município já está coberto por estas outras issues

**Comment by trevineju** [comment]
Tranquilo, @Hudson-Hud. Obrigada pela interesse (: 

Se lá por dezembro você quiser contribuir, será bem-vindo 😃

**Comment by Hudson-Hud** [comment]
Eu que agradeço a gentileza Juliana.
Fica com Deus e boa noite.

Em qui., 26 de out. de 2023 17:48, Juliana Trevine ***@***.***>
escreveu:
