### ISSUE TITLE
Alterar estrutura de diretórios dos spiders

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#938]
Referência: https://github.com/okfn-brasil/querido-diario/pull/921#issuecomment-1683924081

Atualmente todos os spiders estão localizados em `/data_collection/spiders/`. Com centenas de arquivos, esse diretório se tornou um pouco complexo e difícil de navegar. A sugestão é fazer uma modificação na estrutura desse diretório, movendo os spiders para um diretório para cada Estado.

Baseado na sugestão da @trevineju , os spiders ficariam organizados da seguinte maneira:

```
--- spiders
    |--- ac
        |--- ac_rio_branco.py
        |--- ... outros raspadores do AC
    |--- ba
        |--- ba_salvador.py
        |--- ... outros raspadores da BA
    ... vários diretórios por UF e seus raspadores
```

Essa movimentação precisa ser feito usando `git mv` para que o histórico dos arquivos não sejam perdidos e PRs abertos tbm não percam a referência.

**Comment by trevineju** [comment]
Resolvido pelo #939
