### ISSUE TITLE
[Revisão retroativa]: Raspadores de DOEM

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#947]
### Objetivo da Issue

Neste repositório, [há muitos códigos de raspadores que utilizam o DOEM](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/ba) que foram desenvolvidos no começo do projeto. Eles não estão sendo usados. Para passar a usar o raspador deste município, é necessário testar para verificar se segue funcionando e fazer as adaptações necessárias para que passe a funcionar. 

Exemplo de raspador que utiliza o DOEM que está funcionando: [ba_acajutiba](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/ba/ba_acajutiba.py)

**IMPORTANTE:** Como são muitos, proponho que eles sejam revistos aos poucos. Abaixo tem o agrupamento. Um PR deve ser aberto por grupo. Esta issue estará completa uma vez que todos os grupos forem feitos. Quem quiser contribuir pode pegar pegar a issue toda para si (fazendo os 5 PRs) ou apenas algum (alguns) grupos.

### Lista
- [x] Grupo 1: Alcobaca-BA, Antônio Cardoso-BA, Banzaé-BA, Barra do Choca-BA, Barrocas-BA
- [x] Grupo 2: Brotas de Macaubas-BA, Cachoeira-BA, Cacule-BA, Camamu-BA, Catolândia-BA
- [x] Grupo 3: Catu-BA, Cícero Dantas-BA, Floresta Azul-BA, Inhambupe-BA, Ipiau-BA
- [x] Grupo 4: Irara-BA, Ituacu-BA, Laje-BA, Macajuba-BA, Medeiros Neto-BA, Mucuri-BA
- [x] Grupo 5: Ribeira do Pombal-BA, Santa Cruz Cabralia-BA, Santo Amaro-BA, Sento Sé-BA, Tabocas do Brejo Velho-BA, Teixeira de Freitas-BA

### Validação
Lembrando o repositório tem uma [checklist de testes](https://github.com/okfn-brasil/querido-diario/blob/main/.github/pull_request_template.md) que devem ser verificados.

**Comment by natanluiz99** [comment]
Vou começar a fazer o primeiro grupo com as 5 cidades

**Comment by JohnatanLicar** [comment]
A princípio vou está fazendo o Grupo 2 :tada:

**Comment by natanluiz99** [comment]
Estou tendo erros constantes nesses raspadores em especifico, esse é log que está se repetindo nas outras cidades: 

```
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] ------------------------------ MONITORS ------------------------------
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] Comparison Between Executions/Days without gazettes... FAIL
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] Requests/Items Ratio/Ratio of requests over items scraped count... OK
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] Error Count Monitor/test_stat_monitor... SKIPPED (Unable to find 'log_count/ERROR' in job stats.)
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] Finish Reason Monitor/Should have the expected finished reason(s)... OK
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] Item Validation Monitor/test_stat_monitor... SKIPPED (Unable to find 'spidermon/validation/fields/errors' in job stats.)
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] ----------------------------------------------------------------------
2023-10-05 21:22:48 [ba_antonio_cardoso] ERROR: [Spidermon] 
======================================================================
FAIL: Comparison Between Executions/Days without gazettes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\TCC\querido-diario-agoravai\data_collection\gazette\monitors.py", line 69, in test_days_without_gazettes
    self.assertNotEqual(
AssertionError: 0 == 0 : No gazettes scraped in the last 7 days.

2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] 5 monitors in 0.005s
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] FAILED (failures=1, skipped=2)
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] -------------------------- FINISHED ACTIONS --------------------------
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] ----------------------------------------------------------------------
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] 0 actions in 0.000s
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] OK
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] --------------------------- PASSED ACTIONS ---------------------------
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] ----------------------------------------------------------------------
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] 0 actions in 0.000s
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] OK
2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] --------------------------- FAILED ACTIONS ---------------------------
2023-10-05 21:22:48 [spidermon.contrib.actions.discord] INFO: *ba_antonio_cardoso* finished
- Finish time: *2023-10-06 00:22:48.657889+00:00*
- Gazettes scraped: *0*
- 🔥 1 failures 🔥

``` 

nas cidades do grupo 1, estou utilizando o windows e testei outros raspadores para ver ser poderia ser uma questão de problema na instalação  mas outros raspadores funcionaram normalmente, poderia ser a possibilidade da issue #347 mas já foi resolvido antes, estou vendo outras possibilidades, e utilizar o Wsl para testar no linux

**Comment by trevineju** [comment]
@natanluiz99 pra essa cidade, pode renomear o arquivo para `ba_antonio_cardoso_2017.py`. O motivo do erro é que o monitoramento verifica se teve diários nos últimos 7 dias (ou seja, de 28/09/23 até 05/10/23). Olhei o site (https://doem.org.br/ba/antoniocardoso/diarios) e realmente, não tem mais diários desde 2020, eles publicaram lá de janeiro/2017 até dezembro/2020.

**Comment by Carine-Neris** [comment]
Vou pegar o grupo 3.

**Comment by carlosfrodrigues** [comment]
Irei trabalhar no Grupo 4

**Comment by OseOliv** [comment]
Grupo 5

**Comment by natanluiz99** [comment]
> @natanluiz99 pra essa cidade, pode renomear o arquivo para `ba_antonio_cardoso_2017.py`. O motivo do erro é que o monitoramento verifica se teve diários nos últimos 7 dias (ou seja, de 28/09/23 até 05/10/23). Olhei o site (https://doem.org.br/ba/antoniocardoso/diarios) e realmente, não tem mais diários desde 2020, eles publicaram lá de janeiro/2017 até dezembro/2020.
> 
> Sugeri renomear o arquivo pra adicionar o `_2017` justamente por ver que é em 2017 que começa a publicação no site

comecei a procura pelo ano de 2017 como foi sugerido, mas surgiu uma dúvida relacionada ao DOEM dessa cidade em específico já que vai de 2017 até 2020 no DOEM e de 2021 até 2023 em um outro endereço (https://pmantoniocardoso.transparenciaoficialba.com/diariooficial/)
Devo levar em consideração somente a parte relacionada ao DOEM de fato ou devo relatar sobre os diários estarem sendo hospedados em dois endereços diferentes.

**Comment by natanluiz99** [comment]
se possível queria fazer umas perguntas que auxiliaria muito na revisão, compreendi a questão da revisão mas gostaria de confirmar se é de fato da forma como estou pensando, vou tentar deixar elas bem resumidas para também não ficar perguntando mil e uma coisas

<1>Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.

Nesse caso eu faço scrapy estadosigla_cidade -s LOG_FILE=log_nomedacidade.txt e 
verifico se há algum erro ? no caso do que fica no final do log.txt (log_count/ERROR igual a zero).

<2>Você executou uma extração por período (start_date e end_date definidos) ao menos uma vez e os dados retornados estavam corretos.

Nessa parte posso definir um período onde existem diários, por exemplo um mês aleatórios dos anos que tem no site
e faço a comparação dos dados do diário e da saída do raspador? no caso CSV como exemplo.

<3>Você verificou que não existe nenhum erro nos logs (log_count/ERROR igual a zero).

Essa verificação é relativa tanto ao teste do período pego quanto a extração completa ?

<4>Você definiu o atributo de classe start_date no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.

Nessa situação aqui eu faço um spider da cidade, ou reutilizo o código do spider dessa cidade e adiciono só o start_date para fazer o teste

<5>Você garantiu que todos os campos que poderiam ser extraídos foram extraídos de acordo com a documentação.

Essa verificação é relativa tanto ao teste do período pego quanto a extração completa ?

**Comment by natanluiz99** [comment]
@JohnatanLicar @carlosfrodrigues  @OseOliv @Carine-Neris  Estão utilizando o windows para a revisão? se sim estão tendo o mesmo erro da issue #962 ?

**Comment by JohnatanLicar** [comment]
> @JohnatanLicar @carlosfrodrigues @OseOliv @Carine-Neris Estão utilizando o windows para a revisão? se sim estão tendo o mesmo erro da issue #962 ?

Não, uso estou usando Linux

**Comment by trevineju** [comment]
> <1>Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
> Nesse caso eu faço scrapy estadosigla_cidade -s LOG_FILE=log_nomedacidade.txt e verifico se há algum erro ? no caso do que fica no final do log.txt (log_count/ERROR igual a zero).

Nesse caso, você faz `scrapy uf_municipio -s LOG_FILE=uf_municipio.txt -o uf_municipio.csv`. Aí verifica no `.csv` se os metadados foram preenchidos, se pegou todos os arquivos da série histórica (como é uma tabela, só ordenar ela por data e ver quando começa, quando termina), também dá pra ordenar por número da edição e ver se pegou todas as edições.

> <2>Você executou uma extração por período (start_date e end_date definidos) ao menos uma vez e os dados retornados estavam corretos.> 
> Nessa parte posso definir um período onde existem diários, por exemplo um mês aleatórios dos anos que tem no site e faço a comparação dos dados do diário e da saída do raspador? no caso CSV como exemplo.

Isso! Escolhe duas datas quaisquer e tenta baixar (uma semana, um mês...). Vc já vai saber que o raspador está coletando diários por ter feito o teste (1). Aqui, é pra testar se os filtros por data estão funcionando também.

> <3>Você verificou que não existe nenhum erro nos logs (log_count/ERROR igual a zero).
> Essa verificação é relativa tanto ao teste do período pego quanto a extração completa ?

Nessa hora você verifica o `.txt` e sim, como você vai ter ambas coletas, verifica se não tem erros em ambas.

> <4>Você definiu o atributo de classe start_date no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.> 
> Nessa situação aqui eu faço um spider da cidade, ou reutilizo o código do spider dessa cidade e adiciono só o start_date para fazer o teste

Isso, é o caso de ver se no código (seja de um raspador novo ou um sendo revisado) se tem o metadado `start_date`. 
Se não me engano, todos estes raspadores de `DOEM` não tem e é uma modificação que precisa ser acrescentada.

> <5>Você garantiu que todos os campos que poderiam ser extraídos foram extraídos de acordo com a documentação.
> Essa verificação é relativa tanto ao teste do período pego quanto a extração completa?

Nesse caso, tanto faz. Mas a extração completa tem mais dados, então verificar ela pode ser melhor (pensando que a extração completa incluí o período também).

**Comment by trevineju** [comment]
Já comentei em #962, porém se vcs se depararem com o erro mencionado em Windows, pode mandar a PR mesmo assim.

**Comment by JohnatanLicar** [comment]
> > <1>Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
> > Nesse caso eu faço scrapy estadosigla_cidade -s LOG_FILE=log_nomedacidade.txt e verifico se há algum erro ? no caso do que fica no final do log.txt (log_count/ERROR igual a zero).
> 
> Nesse caso, você faz `scrapy uf_municipio -s LOG_FILE=uf_municipio.txt -o uf_municipio.csv`. Aí verifica no `.csv` se os metadados foram preenchidos, se pegou todos os arquivos da série histórica (como é uma tabela, só ordenar ela por data e ver quando começa, quando termina), também dá pra ordenar por número da edição e ver se pegou todas as edições. Aqui é importante também ver se os arquivos que foram baixado é no formato de `pdf`

eu não estou executando o comando assim!
estou me baseando nesse [aqui](https://github.com/okfn-brasil/querido-diario/tree/main#como-executar)

`scrapy crawl <nome_do_raspador>       //exemplo: scrapy crawl ba_acajutiba`

Executei agora deu até um erro de comando desconhecido!

> Scrapy 2.11.0 - active project: gazette
>
> Unknown command: ba_brotas_de_macaubas
>
> Use "scrapy" to see available commands

**Comment by trevineju** [comment]
> eu não estou executando o comando assim! estou me baseando nesse [aqui](https://github.com/okfn-brasil/querido-diario/tree/main#como-executar)
> 
> `scrapy crawl <nome_do_raspador> //exemplo: scrapy crawl ba_acajutiba`

Opa! Obrigada, @JohnatanLicar, ficou faltando o `crawl` ali na minha msg mesmo. 

> Executei agora deu até um erro de comando desconhecido!
> > > Scrapy 2.11.0 - active project: gazette
> > Unknown command: ba_brotas_de_macaubas
> > Use "scrapy" to see available commands 

Você está executando esse comando em qual diretório? Se for na raiz, não funciona. Precisa ser dentro do diretório `/data_collection`

**Comment by trevineju** [comment]
vc conseguiu instalar as dependências? pq aqui consegui executar o raspador pra essa cidade 
(coloquei uma data qualquer só pra engatilhar) 
![image](https://github.com/okfn-brasil/querido-diario/assets/44185775/2c4473b3-0bc0-490f-a077-9bafe6ba32cf)

**Comment by JohnatanLicar** [comment]
> vc conseguiu instalar as dependências? pq aqui consegui executar o raspador pra essa cidade (coloquei uma data qualquer só pra engatilhar) ![image](https://user-images.githubusercontent.com/44185775/273598697-2c4473b3-0bc0-490f-a077-9bafe6ba32cf.png)

Não moça, estava me referindo ao comando que estava faltando, ta tudo certo aqui 😄

**Comment by trevineju** [comment]
aaah, beleza

**Comment by JohnatanLicar** [comment]
![image](https://github.com/okfn-brasil/querido-diario/assets/10299254/95985716-3e16-494c-8694-e1abf058a433)

estou criando os arquivos de LOG

**Comment by OseOliv** [comment]
> Estou tendo erros constantes nesses raspadores em especifico, esse é log que está se repetindo nas outras cidades:
> 
> ```
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] ------------------------------ MONITORS ------------------------------
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] Comparison Between Executions/Days without gazettes... FAIL
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] Requests/Items Ratio/Ratio of requests over items scraped count... OK
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] Error Count Monitor/test_stat_monitor... SKIPPED (Unable to find 'log_count/ERROR' in job stats.)
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] Finish Reason Monitor/Should have the expected finished reason(s)... OK
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] Item Validation Monitor/test_stat_monitor... SKIPPED (Unable to find 'spidermon/validation/fields/errors' in job stats.)
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] ----------------------------------------------------------------------
> 2023-10-05 21:22:48 [ba_antonio_cardoso] ERROR: [Spidermon] 
> ======================================================================
> FAIL: Comparison Between Executions/Days without gazettes
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "D:\TCC\querido-diario-agoravai\data_collection\gazette\monitors.py", line 69, in test_days_without_gazettes
>     self.assertNotEqual(
> AssertionError: 0 == 0 : No gazettes scraped in the last 7 days.
> 
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] 5 monitors in 0.005s
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] FAILED (failures=1, skipped=2)
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] -------------------------- FINISHED ACTIONS --------------------------
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] ----------------------------------------------------------------------
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] 0 actions in 0.000s
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] OK
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] --------------------------- PASSED ACTIONS ---------------------------
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] ----------------------------------------------------------------------
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] 0 actions in 0.000s
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] OK
> 2023-10-05 21:22:48 [ba_antonio_cardoso] INFO: [Spidermon] --------------------------- FAILED ACTIONS ---------------------------
> 2023-10-05 21:22:48 [spidermon.contrib.actions.discord] INFO: *ba_antonio_cardoso* finished
> - Finish time: *2023-10-06 00:22:48.657889+00:00*
> - Gazettes scraped: *0*
> - 🔥 1 failures 🔥
> ```
> 
> nas cidades do grupo 1, estou utilizando o windows e testei outros raspadores para ver ser poderia ser uma questão de problema na instalação mas outros raspadores funcionaram normalmente, poderia ser a possibilidade da issue #347 mas já foi resolvido antes, estou vendo outras possibilidades, e utilizar o Wsl para testar no linux.

==============================================================================
==============================================================================
Também estou me deparando com o mesmo erro em duas cidades do grupo 5 (Ribeira do Pombal-BA e Santo Amaro-BA), mesmo erro tanto no Windows quanto no WSL (Ubuntu). Segui algumas recomendações que encontrei aqui e não obtive sucesso.
- Ja verifiquei e teve diarios nos ultimos 7 dias em ambas as cidades.


`2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] ------------------------------ MONITORS ------------------------------
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] Comparison Between Executions/Days without gazettes... FAIL
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] Requests/Items Ratio/Ratio of requests over items scraped count... OK
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] Error Count Monitor/test_stat_monitor... SKIPPED (Unable to find 'log_count/ERROR' in job stats.)
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] Finish Reason Monitor/Should have the expected finished reason(s)... OK
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] Item Validation Monitor/test_stat_monitor... SKIPPED (Unable to find 'spidermon/validation/fields/errors' in job stats.)
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] ----------------------------------------------------------------------
2023-10-10 15:44:32 [ba_santo_amaro] ERROR: [Spidermon] 
======================================================================
FAIL: Comparison Between Executions/Days without gazettes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/dev/okbr/querido-diario/data_collection/gazette/monitors.py", line 69, in test_days_without_gazettes
    self.assertNotEqual(
AssertionError: 0 == 0 : No gazettes scraped in the last 7 days.

2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] 5 monitors in 0.044s
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] FAILED (failures=1, skipped=2)
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] -------------------------- FINISHED ACTIONS --------------------------
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] ----------------------------------------------------------------------
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] 0 actions in 0.002s
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] OK
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] --------------------------- PASSED ACTIONS ---------------------------
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] ----------------------------------------------------------------------
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] 0 actions in 0.001s
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] OK
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] --------------------------- FAILED ACTIONS ---------------------------
2023-10-10 15:44:32 [spidermon.contrib.actions.discord] INFO: *ba_santo_amaro* finished
- Finish time: *2023-10-10 18:44:32.877727+00:00*
- Gazettes scraped: *0*
- 🔥 1 failures 🔥
===== FAILURES =====
Comparison Between Executions/Days without gazettes: 0 == 0 : No gazettes scraped in the last 7 days.
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] CustomSendDiscordMessage... OK
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] ----------------------------------------------------------------------
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] 1 action in 0.005s
2023-10-10 15:44:32 [ba_santo_amaro] INFO: [Spidermon] OK
2023-10-10 15:44:33 [scrapy.statscollectors] INFO: Dumping Scrapy stats:`

**Comment by trevineju** [comment]
@OseOliv vc pode abrir a PR com as suas modificações e os logs? tudo bem não ter terminado a PR, mas aí fica mais fácil de ver e te ajudar (sem ficar bagunçando esta issue). Também sugiro fazer uma execução com
``` scrapy crawl uf_cidade -s LOG_FILE=log_municipio.txt``` e aí pegar esse `.txt` e adicionar em uma mensagem (exemplo: #955). Basta anexar

**Comment by JohnatanLicar** [comment]
Olá. Guys Beautiful! 🥰  
 
:white_check_mark: **ba_brotas_de_macaubas**  está baixando os diários da data `2019-08-13` ate a data atual `2023-10-11`

:anger: **ba_cachoeira** está baixando os diários da data `2018-01-09` ate a data `2021-01-27` sem mais registros atualizados  e isso acontece com os outros municípios
:anger: **ba_catolandia** ultimo diário: `2020-12-29`
:anger: **ba_camamu** ultimo diário: `2020-12-31`
:anger: **ba_cacule** ultimo diario:`2020-12-30`

Porem encontrei esse site https://www.cachoeira.ba.gov.br/Site/DiarioOficial que tem o diário atualizado para **ba_cachoeira** ate a data atual `2023-10-11`,
https://www.camamu.ba.gov.br/site/diariooficial ultimo diario: `2023-10-10`,
https://www.procedebahia.com.br/ba/cacule/diarios ultimo diario: `2023-10-11`,
http://ba.portaldatransparencia.com.br/prefeitura/catolandia/ ultimo diario: `2023-10-10`

os sites ...ba.gov.br disponibiliza um arquivo JSON (**Relatorio.json**) na pesquisa avançada mudando o seletor de formato de "Em Tela" para "Exporta para .JSON", que pode se extrair informações que tem no link do PDF

> parte do arquivo JSON encontramos :
> `"cod_cliente":119,"`, `"cod_documento":1714`, `"dat_criacao":"2023-10-11T00:00:00"`

e como exemplo de um link do documento pdf: https://www.cachoeira.ba.gov.br/Handler.ashx?f=diario&query=1714&c=119&m=0
que tem o `c=1714`  mesmo do `"cod_cliente":1714` e o `query=119` com `"cod_documento":119`

encontrei uma issue #907 que tem a "mesma" situação

📂 arquivos:
[ba_brotas_de_macaubas.csv](https://github.com/okfn-brasil/querido-diario/files/12918208/ba_brotas_de_macaubas.csv)
[ba_cachoeira.csv](https://github.com/okfn-brasil/querido-diario/files/12918210/ba_cachoeira.csv)
[ba_cacule.csv](https://github.com/okfn-brasil/querido-diario/files/12918211/ba_cacule.csv)
[ba_camamu.csv](https://github.com/okfn-brasil/querido-diario/files/12918212/ba_camamu.csv)
[ba_catolandia.csv](https://github.com/okfn-brasil/querido-diario/files/12918214/ba_catolandia.csv)
[Relatorio.json](https://github.com/okfn-brasil/querido-diario/files/12918335/Relatorio.json)


Obs.: todos os raspadores estão "funcionando normalmente", apenas desatualizados, que acredito não resolve muita coisa :smile:

**Comment by trevineju** [comment]
Pendências: 
Medeiros Neto - BA: revisado, no aguardo de #907 para raspar série histórica completa
