### ISSUE TITLE
[Revisão Retroativa] Raspadores de Instar

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#948]
### Objetivo da Issue
Neste repositório, [há muitos códigos de raspadores que utilizam o INSTAR](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/sp) que foram desenvolvidos no começo do projeto. Eles não estão sendo usados. Para passar a usar o raspador destes municípios, é necessário testar para verificar se segue funcionando ou fazer as adaptações necessárias para que passe a funcionar.

Exemplo de raspador que utiliza o INSTAR que está funcionando: [sp_barao_de_antonina](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/sp/sp_barao_de_antonina.py)

**IMPORTANTE**: Como são muitos, proponho que eles sejam revistos aos poucos. Abaixo tem o agrupamento. Um PR deve ser aberto por grupo. Esta issue estará completa uma vez que todos os grupos forem feitos. Quem quiser contribuir pode pegar pegar a issue toda para si ou apenas um dos grupos.

### Lista
- [ ] Grupo 1: Alto Alegre-SP, Aracariguama-SP, Coronel Macedo-SP, Glicério-SP, Itapirapua Paulista-SP, Lavínia-SP
- [ ] Grupo 2: Monte Alto-SP, Parisi-SP, Patrocínio Paulista-SP, Pratania-SP, Santa Ernestina-SP, São Manuel-SP, Sarutaia-SP

### Validação
Lembrando o repositório tem uma [checklist de testes](https://github.com/okfn-brasil/querido-diario/blob/main/.github/pull_request_template.md) que devem ser verificados.

**Comment by jaswdr** [comment]
Vou trabalhar nessa issue, farei os testes nos próximos dias e caso encontre algum erro, mando novas PRs corrigindo.
