### ISSUE TITLE
Novos municípios que usam o sistema DOSP

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#950]
### Objetivo
Adicionar 20 novas cidades que usam o sistema replicável DOSP. Estas cidades foram agrupadas em 4 grupos para que seja feito 1 PR por grupo 

- [x] Grupo 1:
São Bernardo do Campo	SP  -- atende a milestone de maiores cidades do Brasil
Itapevi	SP -- atende a milestone de maiores cidades do Brasil
Rio Claro	SP
Cabrobó    PE                         --  cidade de interesse no QD-Educação
Bragança Paulista	SP

- [ ] Grupo 2:
Itu	SP
Mogi Guaçu	SP
Salto	SP
Jaú	SP
Sertãozinho	SP

- [x] Grupo 3:
Birigui	SP
Jandira	SP
Catanduva	SP
Votuporanga	SP
Itajubá	MG

- [ ] Grupo 4:
Avaré	SP
Itapeva	SP
Campo Limpo Paulista	SP
Araçatuba	SP
Horizonte	CE

**Comment by trevineju** [comment]
@Winzen tua hacktoberfest toda aqui

**Comment by Winzen** [comment]
Pior que é mesmo :sparkles: :rofl: @trevineju 

PR do grupo 1 já foi :triumph:
