### ISSUE TITLE
Adicionar novas cidades que usam SAI

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#979]
Todas as cidades abaixo usam um sistema replicável conhecido (SAI) que está em desenvolvimento: https://github.com/okfn-brasil/querido-diario/issues/907

Esta issue só pode ser atacada uma vez que o spider base para `sai` estiver integrado. 

Barra do Choça - BA: https://sai.io.org.br/ba/barradochoca/Site/DiarioOficial
Cachoeira - BA: https://www.cachoeira.ba.gov.br/Site/DiarioOficial
Camamu - BA: https://www.camamu.ba.gov.br/site/diariooficial
Floresta Azul - BA: https://www.florestaazul.ba.gov.br/Site/DiarioOficial
Medeiros Neto - BA: https://www.medeirosneto.ba.gov.br/site/diariooficial
Ribeira do Pombal - BA: https://sai.io.org.br/ba/ribeiradopombal/Site/DiarioOficial
Teixeira de Freitas - BA: https://sai.io.org.br/ba/teixeiradefreitas/Site/DiarioOficial
Barra dos Coqueiros - SE: https://sai.io.org.br/se/barradoscoqueiros/Site/DiarioOficial

**Comment by victorfernandesraton** [comment]
@trevineju irei adicionar estes raspadores em uma segunda PR para não bagunçar o desenvolvimento atual, estou concluindo os testes ainda para os municípios citados em #907

**Comment by trevineju** [comment]
Municípios contemplados em #1115
