### ISSUE TITLE
Adicionar novas cidades de Instar

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#987]
Tarefa aberta para o workshop na EACH-USP. 

Toda lista de cidades são do sistema replicável instar

Exemplo de raspador instar funcional: [sp_barao_de_antonina.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/sp/sp_barao_de_antonina.py)

- [ ] Andradina	SP:  https://www.andradina.sp.gov.br/portal/diario-oficial
- [ ] Dracena	SP: https://www.dracena.sp.gov.br/portal/diario-oficial
- [ ] Presidente Epitácio	SP: https://www.presidenteepitacio.sp.gov.br/portal/diario-oficial
- [ ] Itápolis	SP: https://www.itapolis.sp.gov.br/portal/diario-oficial
- [ ] São Pedro	SP: https://www.saopedro.sp.gov.br/portal/diario-oficial

**Comment by Anemaygi** [comment]
Oi! Vou fazer essa issue :)
