### ISSUE TITLE
Adicionar 20 novas cidades de sistemas replicáveis

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#999]
Exemplo de raspador instar funcional: [sp_barao_de_antonina.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/sp/sp_barao_de_antonina.py)

## Descrição
As cidades abaixo utilizam o sistema replicável conhecido e já implementado Instar. A tarefa aqui é enviar PRs com todos os raspadores das cidades abaixo usando de referência o exemplo acima, que usa o mesmo sistema

Como estas cidades serão adicionadas ao projeto, cada PR precisa incluir, também, a modificação da [lista de spiders em funcionamento](https://github.com/okfn-brasil/querido-diario/blob/main/scripts/enabled_spiders.py)

### Task 1
Junqueirópolis	SP																			https://www.junqueiropolis.sp.gov.br/portal/diario-oficial
Palmital	SP																			https://www.palmital.sp.gov.br/portal/diario-oficial
Mirante do Paranapanema	SP																			https://www.mirantedoparanapanema.sp.gov.br/portal/diario-oficial
Charqueada	SP																			https://www.charqueada.sp.gov.br/portal/diario-oficial
Itariri	SP																			 https://www.itariri.sp.gov.br/portal/diario-oficial

### Task 2
Pindorama	SP																			https://www.pindorama.sp.gov.br/portal/diario-oficial
Itapuí	SP																			https://www.itapui.sp.gov.br/portal/diario-oficial
Eldorado	SP																			https://www.eldorado.sp.gov.br/portal/diario-oficial
Joanópolis	SP																			https://www.joanopolis.sp.gov.br/portal/diario-oficial
Avanhandava	SP																			https://www.avanhandava.sp.gov.br/portal/diario-oficial

### Task 3
Porangaba	SP																			https://www.porangaba.sp.gov.br/portal/diario-oficial
General Salgado	SP																			https://www.generalsalgado.sp.gov.br/portal/diario-oficial
Nhandeara	SP																			https://www.nhandeara.sp.gov.br/portal/diario-oficial
Itobi	SP																			https://www.itobi.sp.gov.br/portal/diario-oficial
Tapiraí	SP																			https://www.tapirai.sp.gov.br/portal/diario-oficial

### Task 4
Terra Roxa	SP																			https://www.terraroxa.sp.gov.br/portal/diario-oficial
Iepê	SP																			https://www.iepe.sp.gov.br/portal/diario-oficial
Macaubal	SP																			https://macaubal.sp.gov.br/portal/diario-oficial
Irapuru	SP																			https://www.irapuru.sp.gov.br/portal/diario-oficial
Barbosa	SP																			https://www.barbosa.sp.gov.br/portal/diario-oficial

**Comment by ItzGuuh** [comment]
Vou fazer

**Comment by trevineju** [comment]
@ItzGuuh editei a issue para incluir 4 tasks ;)
